- plugin/video-player/Controller/VideoPlayerController.php
Works better and is simpler to use !
> changed StreamResponse to BinaryFileResponse

- main/core/Library/Installation/Plugin/DatabaseWriter.php
setDescription method doesn't exist anymore
> [CoreBundle] Removing broken setter

- README.md
- main/core/Repository/ToolRepository.php
- plugin/badge/Controller/AdministrationController.php
- plugin/badge/Entity/Badge.php
- plugin/badge/Form/Handler/BadgeHandler.php
- plugin/badge/Hydrators/PairHydrator.php
- plugin/badge/Resources/config/services.yml
- plugin/badge/Resources/public/js/add.js
- plugin/badge/Resources/public/js/profile.js
- plugin/badge/Resources/translations/icap_badge.en.yml
- plugin/badge/Resources/translations/icap_badge.es.yml
- plugin/badge/Resources/translations/icap_badge.fr.yml
- plugin/badge/Resources/views/Administration/edit.html.twig
- plugin/badge/Resources/views/Profile/badge.html.twig
- plugin/badge/Resources/views/Profile/badges.html.twig
- plugin/badge/Resources/views/Template/list_badges.html.twig
- plugin/badge/Resources/views/Template/list_badges_shared.html.twig
- plugin/badge/Resources/views/less/badge.less
Also added some enhancements in BadgeBundle.
> Some bug fixes on BadgeBundle and ToolRepository in core bundle. 

- main/core/Manager/IniFileManager.php
Set "true"/"false" instead of "1"/"")
> [CoreBundle] Ini file mananager update

- main/core/Repository/ToolRepository.php
It crashed when entering in a WS without being admin or ws manager.
> fix tool dql

- main/core/Manager/UserManager.php
- main/core/Resources/translations/platform.en.yml
- main/core/Resources/translations/platform.fr.yml
- main/core/Resources/views/Administration/Users/importForm.html.twig
- main/core/Validator/Constraints/CsvUserValidator.php
> [CoreBundle] User import allows to set a group.

- main/core/Resources/modules/groups/Controller/UserListController.js
> [CoreBundle] Fixing add user to group success placeholder.

- plugin/survey/Controller/SurveyController.php
- plugin/survey/Manager/SurveyManager.php
- plugin/survey/Repository/Answer/MultipleChoiceQuestionAnswerRepository.php
- plugin/survey/Resources/translations/survey.en.yml
- plugin/survey/Resources/translations/survey.fr.yml
- plugin/survey/Resources/views/Survey/questionEditForm.html.twig
- plugin/survey/Resources/views/Survey/showMultipleChoiceQuestionResults.html.twig
- plugin/survey/Resources/views/Survey/showOpenEndedQuestionResults.html.twig
- Includes comments when exporting results
- Adds a warning alert when editing a question
> [SurveyBundle] Includes comments when exporting results

- README.md
- main/core/Repository/UserRepository.php
- main/core/Repository/WidgetHomeTabConfigRepository.php
- main/core/Repository/WidgetInstanceRepository.php
- plugin/agenda/Repository/EventRepository.php
- plugin/badge/Repository/BadgeClaimRepository.php
- plugin/forum/Installation/Updater/Updater020200.php
- plugin/portfolio/Installation/Updater/Updater050002.php
None of them actually presented a security risk, but fixing them led to a cleaner, shorter and sometimes more efficient code.
This should get us the bronze medal.
> [SensioInsight] Fix critical issues

- main/core/Manager/IniFileManager.php
Set true/false when disabling/enabling plugin in bundles.ini
> [CoreBundle] ini parse_ini_file handling.

- .travis.yml
- main/core/Library/Installation/Plugin/Installer.php
- main/core/Library/PluginBundle.php
- main/core/Library/PluginBundleInterface.php
- main/core/Manager/PluginManager.php
- plugin/badge/IcapBadgeBundle.php
- plugin/blog/IcapBlogBundle.php
- plugin/collecticiel/InnovaCollecticielBundle.php
- plugin/dropzone/IcapDropzoneBundle.php
- plugin/ldap/ClarolineLdapBundle.php
- plugin/lesson/IcapLessonBundle.php
- plugin/portfolio/IcapPortfolioBundle.php
- plugin/wiki/IcapWikiBundle.php
Refactors the plugin manager to avoid access to undefined array entries when checking plugin requirements. Also adds a bit of doc and cleans/renames where appropriate.
> Fix plugin requirements handling

- main/core/Resources/scripts/build-themes.js
Another attempt at solving the issue mentioned in #257.
> Build themes asynchronously

- composer.json
No more bad surprise with composer updates if the version is fixed.
> Fixing composer version

- .travis.yml
- main/core/Resources/scripts/build-themes.js
- main/dev/Resources/travis/fetch-deps.bash
This should reduce significantly the build time.
@LaurentGruber, this PR is dead without a server access.
> Add a dependency cache layer in travis builds

- plugin/exo/Resources/public/js/angular/Exercise/Partials/player.html
- plugin/exo/Resources/public/js/angular/Question/Controllers/Type/GraphicQuestionCtrl.js
This branch fixes an issue on the formative version of the graphic questions' player.
The answers proposed by the student were not validated if true, due to the centering of the picture, the answer zones not being set from the same panel as the student's answers.
> Fix issue on immediate feedbacks on graphic questions

- main/core/Resources/public/js/administration/roleList.js
> [CoreBundle] Fixing administration role name edition callback.

- plugin/exo/Resources/public/js/angular/Paper/Partials/show.html
If there is no score set in the Paper we display a "?", but if the user obtains 0 to his paper, it was miscatch as undefined.
> fix display of 0 score

- main/core/Form/Field/ContentType.php
- main/core/Manager/HomeManager.php
- plugin/ldap/Controller/LdapController.php
- plugin/ldap/Manager/LdapManager.php
- plugin/lesson/Controller/LessonController.php
- plugin/lesson/Manager/ChapterManager.php
This is currently untested
This is supposed to fix #284 and #99 
ref #284 
ref #99
> [SensioInsight] Changes all 'and' to '&&'

- plugin/exo/Controller/QuestionController.php
fix error (incorrect management of steps) when trying to duplicate a question from the bank
> [ExoBundle] Fix duplication of Questions in the bank

- .travis.yml
Travis script error again... (there's no easy way to test this, sorry).
> Ensure environment variables are exported

- main/core/Resources/views/Workspace/layout.html.twig
- plugin/announcement/Controller/AnnouncementController.php
- [AnnouncementBundle] Fixes deprecated items
- [CoreBundle] Fixes bug in workspace layout
> [AnnouncementBundle] Fixes deprecated items

- bower.json
To get a fix on pluralization available in v1.0.1
> update angular-ui-translation lib

- bower.json
It's requested by @ngodfraind in #226 and I want to use it in ExoBundle (I think I can use it to order Steps and Questions in Exercise #113 ).
> Add dragula to front dependencies

- main/core/Controller/API/Admin/LocaleController.php
- main/core/Controller/ResourceRightsController.php
- main/core/DataFixtures/BatchInsert/LoadUsersData.php
- main/core/DataFixtures/Optional/LoadGroupData.php
- main/core/DataFixtures/Optional/LoadRoleData.php
> [SensioInsight] Removed unused uses

- plugin/exo/Controller/Api/StepController.php
- plugin/exo/Entity/Step.php
- plugin/exo/Manager/ExerciseManager.php
- plugin/exo/Manager/StepManager.php
- plugin/exo/Resources/public/js/angular/Common/Services/TinyMceService.js
- plugin/exo/Resources/public/js/angular/Exercise/Controllers/ExerciseMetadataCtrl.js
- plugin/exo/Resources/public/js/angular/Exercise/Controllers/ExercisePlayerCtrl.js
- plugin/exo/Resources/public/js/angular/Exercise/Partials/player.html
- plugin/exo/Resources/public/js/angular/Step/Controllers/StepListCtrl.js
- plugin/exo/Resources/public/js/angular/Step/Controllers/StepMetadataCtrl.js
- plugin/exo/Resources/public/js/angular/Step/Controllers/StepShowCtrl.js
- plugin/exo/Resources/public/js/angular/Step/Partials/list.html
- plugin/exo/Resources/public/js/angular/Step/Partials/metadata.html
- plugin/exo/Resources/public/js/angular/Step/Partials/show.html
- plugin/exo/Resources/public/js/angular/Step/Services/StepService.js
- plugin/exo/Resources/translations/ujm_exo.en.yml
- plugin/exo/Resources/translations/ujm_exo.fr.yml
- plugin/exo/Transfer/Json/Validator.php
* Export metadata of the step in a `meta` property (like the Exercise)
* Display a modal in step list to edit step metadata
For now only the parameters `description` and `maxAttempts` are managed as the others are not implemented.
@LaurentGruber : you can simulate a step with only `Content` items by adding a description HTML to step without adding questions.
> [ExoBundle] Step metadata

- main/core/Controller/Administration/ParametersController.php
- main/core/Form/Administration/MaintenanceMessageType.php
- main/core/Resources/translations/platform.en.yml
- main/core/Resources/translations/platform.fr.yml
- main/core/Resources/views/Administration/Parameters/maintenance.html.twig
- main/core/Resources/views/Administration/Parameters/maintenanceMessageEditForm.html.twig
- main/core/Resources/web/maintenance.php
- Allows to edit maintenance message
- Closes #56
> [CoreBundle] Allows to edit maintenance message

- main/core/Manager/HomeManager.php
- main/core/Resources/views/Home/types/default.html.twig
- Fixes bug at home page content creation
- Removes "... time ago" message in home page contents footer
- Closes #83
> [CoreBundle] Home page gui + bugfix

- plugin/path/Manager/PathManager.php
- Fixes AccessDeniedException path
- Fixes deprecated ResourceCollection
- closes #318
> [PathBundle] Fixes AccessDeniedException path & deprecated ResourceCollection

- main/core/Menu/Builder.php
- main/core/Menu/ExceptionActionEvent.php
- main/core/Resources/views/Exception/error400.html.twig
- main/core/Resources/views/Exception/error403.html.twig
- main/core/Resources/views/Exception/error404.html.twig
- main/core/Resources/views/Exception/error500.html.twig
- main/core/Resources/views/Exception/error503.html.twig
- main/core/Resources/views/Exception/layout.html.twig
- plugin/support/Listener/SupportListener.php
- Only allows ticket creation for error 400 & 500
- Closes #444
> [CoreBundle][SupportBundle] Only allows ticket creation for error 400 & 500

- main/core/Library/Installation/Settings/SettingChecker.php
> [CoreBundle] Fixing installation settings

- plugin/flashcard/Entity/CardLearning.php
- plugin/flashcard/Entity/CardLog.php
- plugin/flashcard/Entity/FieldValue.php
- plugin/flashcard/Entity/Session.php
- plugin/flashcard/Entity/UserPreference.php
I hope I didn't miss anything.
> [FlashCardBundle] Typing hint.

- main/core/Controller/ResourceController.php
- main/core/Listener/Tool/ResourceManagerListener.php
- main/core/Manager/UserManager.php
- main/core/Resources/public/js/resource/manager/manager.js
- main/core/Resources/public/js/resource/manager/views/resource/actions.js
- main/core/Resources/public/js/resource/manager/views/resource/nodes.js
- main/core/Resources/views/Tool/desktop/resource_manager/resources.html.twig
- main/core/Resources/views/Tool/workspace/resource_manager/resources.html.twig
- Registers last view mode of resources manager
- closes #207
> [CoreBundle] Registers last view mode of resources manager

- .travis.yml
- plugin/exo/Manager/PaperManager.php
- plugin/exo/Resources/public/js/angular/Correction/Controllers/OpenCorrectionCtrl.js
- plugin/exo/Resources/public/js/angular/Correction/Partials/open.html
- plugin/exo/Transfer/Json/QuestionHandler/HoleHandler.php
As reported by @claroline/ujm there is a bug in the last fix done to manage deleted questions.
I have not detected it due to my test data sorry for that :s.
Can we include it in the 7.0.0 ? Because it's a major bug.
> [ExoBundle][Urgent] fixes management of deleted questions

- main/core/Controller/ProfileController.php
This route is required.
It still has some issues (see #519)
> [CoreBundle] Fix public profile route

- plugin/exo/Services/classes/QTI/QcmImport.php
> Add a control for the QCM import

- .travis.yml
- plugin/exo/Resources/less/question/question.less
- plugin/exo/Resources/less/step.less
- plugin/exo/Resources/public/js/angular/Exercise/Partials/overview.html
- plugin/exo/Resources/public/js/angular/Exercise/Partials/player.html
- plugin/exo/Resources/public/js/angular/Image/Services/ImageAreaService.js
- plugin/exo/Resources/public/js/angular/Question/Controllers/Type/ChoiceQuestionCtrl.js
- plugin/exo/Resources/public/js/angular/Question/Controllers/Type/ClozeQuestionCtrl.js
- plugin/exo/Resources/public/js/angular/Question/Controllers/Type/GraphicQuestionCtrl.js
- plugin/exo/Resources/public/js/angular/Question/Directives/Type/AbstractQuestionDirective.js
- plugin/exo/Resources/public/js/angular/Question/Directives/Type/GraphicQuestionDirective.js
- plugin/exo/Resources/public/js/angular/Question/Directives/Type/MatchQuestionDirective.js
- plugin/exo/Resources/public/js/angular/Question/Partials/Type/graphic.html
- plugin/exo/Resources/public/js/angular/Question/Partials/show.html
- plugin/exo/Resources/public/js/angular/Question/Services/Type/ChoiceQuestionService.js
- plugin/exo/Resources/public/js/angular/Question/Services/Type/MatchQuestionService.js
- plugin/exo/Resources/public/js/angular/Step/Partials/show.html
- plugin/exo/Resources/translations/ujm_sequence.en.yml
- plugin/exo/Resources/translations/ujm_sequence.fr.yml
- plugin/exo/Transfer/Json/QuestionHandler/QcmHandler.php
Trying to solve #568 build issue.
> [ExoBundle] bugfixes

- plugin/exo/Resources/public/js/angular/Common/Filters/DateStringFilter.js
- plugin/exo/Resources/public/js/angular/Common/module.js
- plugin/exo/Resources/public/js/angular/Correction/module.js
- plugin/exo/Resources/public/js/angular/Exercise/module.js
- plugin/exo/Resources/public/js/angular/Image/module.js
- plugin/exo/Resources/public/js/angular/Paper/module.js
- plugin/exo/Resources/public/js/angular/Question/module.js
- plugin/exo/Resources/public/js/angular/Step/module.js
- plugin/exo/Resources/public/js/angular/Timer/module.js
- plugin/exo/Resources/public/js/angular/app.js
@stefk 
To simplify ES6/Webpack modules creation.
> [ExoBundle] create correct DI tree in angular modules

- main/core/Controller/ResourceController.php
- main/core/Manager/ResourceManager.php
- plugin/audio-recorder/Manager/AudioRecorderManager.php
- plugin/video-recorder/Manager/VideoRecorderManager.php
Can download a 'non file' resource that is... a file...
> Allow a non file resource to be downloaded according to it's mime type

- plugin/scorm/Resources/views/scorm12MenuSco.html.twig
- plugin/scorm/Resources/views/scorm2004MenuSco.html.twig
The allowfullscreen attribute somehow fixed some fullscreen issue with firefox & IE11 for me.
https://developer.mozilla.org/en/docs/Web/HTML/Element/iframe
> [ScormBundle] Full screen mode.

- plugin/exo/Tests/Data/json/question/valid/complete/qcm-1.json
- plugin/exo/Tests/Data/json/question/valid/complete/qcm-2.json
- plugin/exo/Tests/Data/json/question/valid/complete/qcm-3.json
- plugin/exo/Tests/Data/json/question/valid/complete/qcm-4.json
- plugin/exo/Tests/Data/json/question/valid/complete/qcm-5.json
- plugin/exo/Tests/Data/json/question/valid/evaluation/qcm-1.json
- plugin/exo/Tests/Data/json/question/valid/evaluation/qcm-2.json
- plugin/exo/Tests/Data/json/question/valid/evaluation/qcm-3.json
- plugin/exo/Tests/Data/json/question/valid/evaluation/qcm-4.json
- plugin/exo/Tests/Data/json/question/valid/evaluation/qcm-5.json
- plugin/exo/Tests/Manager/QuestionManagerTest.php
- plugin/exo/Transfer/Json/QuestionHandler/QcmHandler.php
> [exobundle] Add detail for score in the QCM

- main/core/Listener/Resource/FileListener.php
- main/core/Manager/FileManager.php
Should fix missing files in #609
> [CoreBundle] Adding missing return in file listener.

- main/installation/Bundle/InstallableBundle.php
> [InstallationBundle] Fix for external plugins.

- bower.json
@om64 would like to use some new icons.
> [CoreBundle] Update font awesome.

- main/core/Resources/modules/facets/Form/Field.js
- main/core/Resources/modules/form/Field/Select/SelectController.js
- main/core/Resources/modules/form/Field/Select/select.html
- main/core/Resources/modules/profile/Controller/ProfileController.js
- plugin/flashcard/Resources/modules/flashcard/CreateNoteCtrl.js
- plugin/flashcard/Resources/modules/flashcard/createNote.partial.html
- plugin/flashcard/Resources/modules/flashcard/editNote.partial.html
- plugin/flashcard/Resources/modules/flashcard/flashcard.js
- Uses the core select form for the buggy select.
- Select improved (it has a choice_value option and will select the by default object).
- Redirect at the note creation.
> [FlashCardBundle] Fixing flashcard creation.

- main/core/Controller/Tool/WorkspaceParametersController.php
> [CoreBundle] Fixing workspace anonymous registration.

- plugin/video-player/Resources/public/js/watch_video.js
Tech order changed (flash is now the fallback).
Fixes #615 
Tested on prod server, it worked for us.
> [VideoPlayerBundle] Tech order

- plugin/dropzone/Manager/DropzoneManager.php
> [DropzoneBundle] download copies patch

- main/core/Controller/Tool/RolesController.php
- main/core/Resources/views/Administration/Users/index.html.twig
- main/core/Resources/views/Administration/Users/userCreationForm.html.twig
- plugin/path/Resources/public/js/Path/Service/PathService.js
- Fixed bug in workspace users import with csv
- Added flashbox to users list in admin
- Changed path summary from default "pinned" to default "unpinned"
> Fixed bug with csv workspace import, added flashbox in users admin list

- plugin/exo/Resources/modules/exercise/Partials/metadata.html
- plugin/exo/Resources/modules/step/Partials/show.html
- plugin/exo/Resources/translations/ujm_exo.en.yml
- plugin/exo/Resources/translations/ujm_exo.fr.yml
- plugin/exo/Resources/translations/ujm_sequence.en.yml
- plugin/exo/Resources/translations/ujm_sequence.fr.yml
Change terminologies according to JJQ's demands.
https://github.com/claroline/Distribution/issues/797
https://github.com/claroline/Distribution/issues/799
https://github.com/claroline/Distribution/issues/802
https://github.com/claroline/Distribution/issues/812
> Exo terminologies changes

- plugin/exo/Resources/modules/question/Controllers/Type/MatchQuestionCtrl.js
This PR fixes the following issue:
https://github.com/claroline/Distribution/issues/803
Reseted proposals couldn't be moved again. This bug gets fixed.
> Exo fixes pairing

- bower.json
- main/core/Entity/User.php
- plugin/scorm/Controller/API/ScormController.php
- plugin/scorm/Controller/ScormController.php
- plugin/scorm/Entity/Scorm12Sco.php
- plugin/scorm/Entity/Scorm12ScoTracking.php
- plugin/scorm/Entity/Scorm2004Sco.php
- plugin/scorm/Entity/Scorm2004ScoTracking.php
- plugin/scorm/Event/Log/LogScorm12ResultEvent.php
- plugin/scorm/Event/Log/LogScorm2004ResultEvent.php
- plugin/scorm/Manager/ScormManager.php
- plugin/scorm/Repository/Scorm12ScoTrackingRepository.php
- plugin/scorm/Repository/Scorm2004ScoTrackingRepository.php
- plugin/scorm/Resources/config/routing.yml
- plugin/scorm/Resources/modules/Results/Controller/ScormResultsCtrl.js
- plugin/scorm/Resources/modules/Results/Directive/ScormResultsDirective.js
- plugin/scorm/Resources/modules/Results/Partial/scormResults.html
- plugin/scorm/Resources/modules/Results/Service/ScormResultsService.js
- plugin/scorm/Resources/modules/Results/results.js
- plugin/scorm/Resources/public/css/scormResults.css
- plugin/scorm/Resources/translations/scorm.en.yml
- plugin/scorm/Resources/translations/scorm.fr.yml
- plugin/scorm/Resources/views/scorm12.html.twig
- plugin/scorm/Resources/views/scorm12MenuSco.html.twig
- plugin/scorm/Resources/views/scorm2004.html.twig
- plugin/scorm/Resources/views/scorm2004MenuSco.html.twig
- plugin/scorm/Resources/views/scormResults.html.twig
- plugin/scorm/assets.json
- Closes #732
- Imports ng-table library
- Adds a page with all results of a scorm resource. Only accessible for users with EDIT right on the scorm resource.
> [ScormBundle] Allows to view scorm results from resource

- plugin/exo/Resources/modules/timer/module.js
> [ExoBundle] fixes #847

- plugin/collecticiel/Resources/views/Document/renderReturnReceipt.html.twig
- plugin/collecticiel/Resources/views/Document/returnReceipt.html.twig
- plugin/collecticiel/Resources/views/Drop/Listing/dropsListing.html.twig
fix claroline/Distribution#867 bug return receipt values
> [Collecticiel]Issue867 : return receipt values

- plugin/collecticiel/Controller/DocumentController.php
> [CollecticielBundle] Adding use to DocumentController.php

- plugin/path/Controller/StepConditionController.php
I found this while looking for something else. This is not the correct entity full name.
> [PathBundle] Wrong entity path

- plugin/o365/Controller/OfficeConnectController.php
I think it's what's missing.
It should fix #817.
> [o365Bundle] Fixing auth statistics

- main/core/Entity/Organization/Organization.php
- main/core/Manager/Organization/OrganizationManager.php
- main/core/Resources/modules/organization/Partial/organizations_main.html
> [CoreBundle] Default organization can not be removed.

- main/core/Resources/views/layout.html.twig
I'll add an SSL parameter in the platform_options.yml later because the sf2 detection isn't always reliable (because proxies mess up everything).
> [CoreBundle] homePath SSL was wrong

- .travis.yml
Ensure there's no files to be analysed.
> Fix travis static analysis config

- main/core/Manager/WidgetManager.php
- main/core/Repository/WidgetHomeTabConfigRepository.php
Handles the case were the widget name is not unique.
> [CoreBundle] Fixing cli widget update.

- plugin/path/Resources/views/Wizard/layout.html.twig
- plugin/path/Resources/views/manageResults.html.twig
Removes the last reference to the FrontEndBundle.
> [PathBundle] removes FrontEndBundle dependency

- plugin/blog/Resources/views/less/style.less
> [BlogBundle] Fixed display issues

- plugin/notification/Manager/NotificationManager.php
> [NotificationBundle] Fixed RSS feed parameters bug

- main/core/Resources/views/Tool/workspace/parameters/model/groupShare.html.twig
Wrong parameters (probably copy pasted).
> [CoreBundle] model group sharing twig fixes

- plugin/exo/Resources/modules/question/Controllers/Type/MatchQuestionCtrl.js
- plugin/exo/Resources/modules/question/Partials/show.html
Various urgent fixes on exo bundle:
- "Reset" button on match questions fixed
- remove visible html tags on additional fields
- enlarge iframes for "objects of the question"
> [ExoBundle] Fix mutliple issues

- plugin/path/EventListener/Resource/PathListener.php
- plugin/path/Resources/modules/path/Controller/PathEditCtrl.js
- plugin/path/Resources/modules/path/Service/PathService.js
- plugin/path/Resources/modules/summary/Controller/SummaryBaseCtrl.js
- plugin/path/Resources/modules/summary/Controller/SummaryEditCtrl.js
- plugin/path/Resources/modules/summary/Directive/SummaryItemEditDirective.js
- plugin/path/Resources/modules/summary/Partial/edit-item.html
- Fixes bad condition in the copy if there are deleted resources in the path
- Disables delete button for root step
- Fixes #1066
> [PathBundle] various fixes

- main/core/Controller/Administration/UsersController.php
- main/core/Manager/UserManager.php
Removes some copy/paste code (2 methods merged).
Also fixes some of the users missing properties for the update (groups, roles).
> [CoreBundle] csv user update

- plugin/exo/Resources/modules/exercise/Controllers/ExercisePlayerCtrl.js
- plugin/exo/Resources/modules/question/Partials/show.html
- plugin/exo/Resources/modules/step/Controllers/StepShowCtrl.js
- plugin/exo/Resources/translations/ujm_exo.en.yml
- plugin/exo/Resources/translations/ujm_exo.fr.yml
- plugin/exo/Resources/translations/ujm_sequence.en.yml
- plugin/exo/Resources/translations/ujm_sequence.fr.yml
These are the fixes required for the ENPA update.
It fixes the following issues:
claroline/Distribution#1091
claroline/Distribution#543
claroline/Distribution#1094
claroline/Distribution#1095
> [ExoBundle] Urgent ENPA fixes

- plugin/media-resource/Resources/modules/modals/Partials/optionsModal.html
Remove to restrictive constraints from media resource help link
Just check for http(s):// prefix
solve #1108
> help link pattern check for http(s):// prefix only

- plugin/exo/Listener/ExerciseListener.php
- plugin/exo/Resources/modules/exercise/Controllers/ExercisePlayerCtrl.js
- plugin/exo/Resources/views/Scorm/export.html.twig
- plugin/path/EventListener/Resource/PathListener.php
- plugin/path/Resources/views/Scorm/export.html.twig
- plugin/pdf-player/Listener/PdfPlayerListener.php
- plugin/pdf-player/Resources/views/Scorm/export.html.twig
- plugin/scorm/Event/ExportScormResourceEvent.php
- plugin/scorm/Library/Export/RichTextExporter.php
- plugin/scorm/Manager/ExportManager.php
- plugin/scorm/Resources/views/Export/layout.html.twig
- plugin/video-player/Listener/VideoPlayerListener.php
- plugin/video-player/Resources/views/Scorm/export.html.twig
- plugin/web-resource/Listener/WebResourceListener.php
- plugin/web-resource/Resources/views/Layout/javascripts.html.twig
- plugin/web-resource/Resources/views/Layout/javascripts_header.html.twig
- plugin/web-resource/Resources/views/Scorm/export.html.twig
- plugin/web-resource/Resources/views/webResource.html.twig
This PR contains : 
- some code refactoring of the SCORM export.
- fixes for a few bugs on resources when they are played in SCORM.
- export of videos contained in HTML contents
- export of WebResource
**Known issue :**
There is a scaling problem (too large) for video embedded in step descriptions.
> Various fixes on SCORM exports

- plugin/collecticiel/Controller/CorrectionController.php
- plugin/collecticiel/Controller/DropController.php
- plugin/collecticiel/Resources/views/Document/viewNotation.html.twig
resolve https://github.com/claroline/Distribution/issues/1057
resolve https://github.com/claroline/Distribution/issues/1078
> [Collecticiel] - collecticiel student valuation detail modal

- plugin/exo/Controller/Api/ExerciseController.php
- plugin/exo/Manager/PaperManager.php
- plugin/exo/Resources/modules/app.js
- plugin/exo/Resources/modules/exercise/Controllers/ExercisePlayerCtrl.js
- plugin/exo/Resources/modules/exercise/Partials/player.html
- plugin/exo/Resources/modules/exercise/module.js
- plugin/exo/Resources/modules/paper/Controllers/PaperShowCtrl.js
- plugin/exo/Resources/modules/paper/Partials/show.html
- plugin/exo/Resources/modules/paper/Services/PaperService.js
- plugin/exo/Resources/modules/paper/Services/UserPaperService.js
- plugin/exo/Resources/modules/paper/module.js
- plugin/exo/Resources/modules/step/Controllers/StepShowCtrl.js
- plugin/exo/Resources/modules/step/Directives/StepShowDirective.js
- plugin/exo/Resources/modules/step/Partials/show.html
- plugin/exo/Tests/Controller/Api/ExerciseControllerCommonTest.php
This PR fixes the display of scores (and feedback) in the corrections.
> [ExoBundle] fixes scores in corrections

- plugin/exo/Services/classes/QTI/HoleImport.php
There was a SQL error when trying to import an Exercise with a Question with holes.
> [ExoBundle] fixes Hole import

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
> Add issue and pr templates

- package.json
> [CoreBundle] adds file-loader to npm dependencies

- plugin/scorm/Resources/modules/Results/Service/ScormResultsService.js
> Fixes undefined time conversion. Closes #1166

- plugin/scorm/Resources/public/js/scorm_2004_api.js
> Fixes undefined index bug when setting value

- main/core/Command/Import/RegisterUserToWorkspaceFromCsvCommand.php
The script to register users into workspace via a csv has been updated to allow also groups registration.
> [CoreBundle] Updates script for registration of users into WS via csv

- package.json
- plugin/portfolio/Form/Type/Widgets/ExperienceType.php
- plugin/portfolio/Resources/modules/checklist-model.js
- plugin/portfolio/Resources/public/js/portfolio/controllers/portfolioController.js
- plugin/portfolio/Resources/public/js/portfolio/controllers/widgetController.js
- plugin/portfolio/Resources/public/js/portfolio/controllers/widgetPickerController.js
- plugin/portfolio/Resources/public/js/portfolio/portfolioApp.js
- plugin/portfolio/Resources/public/js/portfolio/services/widgetsManager.js
- plugin/portfolio/Resources/views/Portfolio/view.html.twig
- plugin/portfolio/Resources/views/less/interface.less
- plugin/portfolio/Resources/views/templates/form/experience.html.twig
- plugin/portfolio/assets.json
| Fixed tickets | fixes #991 
- Rendered website url in experience widget optional
- Added back button to view mode (so as user can return to edit mode)
- User can now insert multiple widgets of the same type at once
> [PortfolioBundle] Portfolio improvements

- plugin/exo/Resources/modules/question/Partials/show.html
- plugin/exo/Resources/translations/ujm_exo.en.yml
- plugin/exo/Resources/translations/ujm_exo.fr.yml
| Bug fix     | yes
| Fixed tickets | #1191,#1184
resolve #1191
resolve #1184
> [ExoBundle] unwanted description title and minimal correction label

- main/core/Resources/views/base.html.twig
- plugin/exo/Resources/modules/app.js
- plugin/exo/Resources/views/Exercise/open.html.twig
| Fixed tickets | #1105
Add id ```#claroline-base-layout-body``` to claroline base.html.twig body tag.
This allow angular applications to use a common element to scroll to when route changes.
> [ExoBundle] - anchor scroll

- plugin/exo/Resources/modules/question/Controllers/Type/ClozeQuestionCtrl.js
- plugin/exo/Resources/modules/question/Services/Type/ClozeQuestionService.js
| Fixed tickets | #1204
Check if answer exists before using it.
> [ExoBundle] - Cloze question answer undefined in correction

- main/core/Resources/modules/aDisabled/module.js
- main/core/Resources/modules/anchor/module.js
- plugin/exo/Resources/modules/exercise/Partials/exercise.html
- plugin/exo/Resources/modules/exercise/module.js
| Fixed tickets | #1199
Core directive that allow to add a "disable" attribute on a link
> [CoreBundle] - directive allowing to disable a link. closes #1199

- plugin/exo/Resources/translations/ujm_exo.en.yml
- plugin/exo/Resources/translations/ujm_exo.fr.yml
- plugin/exo/Resources/views/Question/new.html.twig
| New feature?  |no
| Fixed tickets | #1206
> [ExoBundle] - EN translation problem

- plugin/website/Resources/views/Website/edit.html.twig
Increased max banner and footer height to 1000px from 200px
> [WebsiteBundle] Increased max banner and footer height to 1000px

- plugin/website/Resources/views/Website/Edit/banner_footer_options.html.twig
- plugin/website/Resources/views/Website/edit.html.twig
Website options gave an error on save if banner richtext was added. This was caused due to extra parameters passed to query, hence form validation was failing.
> [WebsiteBundle] Fixed website options save issue

- main/core/Resources/views/Workspace/layout.html.twig
> [CoreBundle] - Check for undefined workspace in workspace layout

- main/core/Controller/Widget/MyWorkspacesWidgetController.php
- main/core/Resources/views/Widget/desktopWidgetMyWorkspaces.html.twig
- main/core/Resources/views/Widget/displayMyWorkspacesWidget.html.twig
| Fixed tickets | #1158 
It fixes the bug in which "My workspaces" widget is locked on the default mode.
> Fixes my workspaces widget. Closes #1158

- main/core/Repository/AdministrationToolRepository.php
> [CoreBundle] Fixing administration tool list

- main/core/Resources/views/Administration/WorkspaceRegistration/groupListPager.html.twig
- main/core/Resources/views/Log/view_list_item_receiver_group.html.twig
> [CoreBundle] Fixing administration group link.

- composer.json
It causes issue with php 7.0 and doctrine otherwise.
> [CoreBundle] Fixing bundle version

- main/core/Resources/translations/platform.fr.yml
Small correction of a translation issue reported by a user.
> [CoreBundle] fix french translation

- main/core/Resources/views/Layout/javascripts.html.twig
> [CoreBundle] Fixes unscrollable modal issue. Closes #215

- main/core/Manager/UserManager.php
> [CoreBundle] Fixing user csv removal.

- plugin/support/Resources/translations/support.nl.yml
- plugin/support/Resources/translations/tools.fr.yml
- plugin/support/Resources/translations/tools.nl.yml
Translations of plugins into Dutch.
> Support.nl.yml

- main/core/Resources/config/suggested/assetic.yml
Otherwise assetic doesn't generate the nl js files.
> [CoreBundle] nl js translations

- plugin/exo/Command/QuestionProprietaryUpdateCommand.php
> [UJMExoBundle] CLI tools to change questions users.

- plugin/exo/Controller/QtiController.php
- plugin/exo/Manager/PaperManager.php
- plugin/exo/Repository/QuestionRepository.php
- plugin/exo/Resources/modules/paper/Services/UserPaperService.js
- plugin/exo/Transfer/ExoImporter.php
- plugin/exo/Transfer/Json/QuestionHandler/QcmHandler.php
| Fixed tickets | #1257
There was a bug in the update of the question with solutions.
The scores exported for Choice type with fixed score were wrongs too.
> [ExoBundle] fixes show solutions in formative exercise

- main/core/Library/Transfert/ConfigurationBuilders/Tools/ResourceManagerImporter.php
- main/core/Library/Transfert/ConfigurationBuilders/Tools/Resources/FileImporter.php
- main/core/Library/Transfert/Importer.php
- main/core/Manager/TransferManager.php
| Bug fix?      | yes/
| Fixed tickets | #883
> [CoreBundle] Fixing partial import

- main/core/Controller/Widget/ResourcesWidgetController.php
- main/core/DataFixtures/Required/Data/LoadWidgetData.php
- main/core/Entity/Widget/ResourcesWidgetConfig.php
- main/core/Form/ResourcesWidgetConfigurationType.php
- main/core/Library/Installation/AdditionalInstaller.php
- main/core/Library/Installation/Updater/Updater080000.php
- main/core/Listener/ResourcesWidgetListener.php
- main/core/Manager/ResourceManager.php
- main/core/Manager/ResourcesWidgetManager.php
- main/core/Migrations/pdo_mysql/Version20160929141007.php
- main/core/Repository/ResourceNodeRepository.php
- main/core/Repository/ResourceQueryBuilder.php
- main/core/Resources/public/js/resourceinput.js
- main/core/Resources/translations/platform.en.yml
- main/core/Resources/translations/platform.fr.yml
- main/core/Resources/translations/widget.en.yml
- main/core/Resources/translations/widget.fr.yml
- main/core/Resources/views/Widget/resourcesWidget.html.twig
- main/core/Resources/views/Widget/resourcesWidgetConfigureForm.html.twig
- plugin/tag/Manager/TagManager.php
- plugin/tag/Repository/TaggedObjectRepository.php
> [CoreBundle] Widget resources

- main/core/Event/DisplayWidgetEvent.php
> [CoreBundle] Adds missing var declaration

- plugin/announcement/Controller/AnnouncementController.php
- plugin/announcement/Manager/AnnouncementManager.php
- plugin/announcement/Repository/AnnouncementRepository.php
- plugin/announcement/Resources/public/js/announcements_list.js
- plugin/announcement/Resources/translations/announcement.en.yml
- plugin/announcement/Resources/translations/announcement.fr.yml
- plugin/announcement/Resources/views/announcementsDesktopWidgetPager.html.twig
- plugin/announcement/Resources/views/announcementsList.html.twig
- plugin/announcement/Resources/views/createForm.html.twig
- Adds a button to send an announcement by mail 
- Adds a tooltip in announcement form to explain why the notification option can be disabled
> [AnnouncementBundle] Send announcement by mail

- plugin/path/Resources/modules/path/Controller/PathEditCtrl.js
| Fixed tickets | https://github.com/claroline/Distribution/issues/1305
Fix the bad redirection to the Unlock manager
> Path unlock fix

- main/core/Resources/views/Resource/multipleRightsPage.html.twig
Checking if the array have the correct keys because it appears to not always be the case.
> [CoreBundle] Fixing tags in workspace list.

- main/core/Entity/AbstractRoleSubject.php
- main/core/Resources/modules/users/Controller/UserController.js
> [CoreBundle] Administration users choice fixed (fixes #1304).

- main/core/Command/Import/CreateWorkspaceFromCsvCommand.php
- main/core/Library/Transfert/ConfigurationBuilders/ToolsImporter.php
- main/core/Manager/ToolManager.php
- main/core/Manager/ToolRightsManager.php
- main/core/Manager/WorkspaceManager.php
- main/core/Manager/WorkspaceModelManager.php
- main/core/Tests/Unit/Manager/ToolManagerTest.php
- main/core/Validator/Constraints/CsvWorkspace.php
- main/core/Validator/Constraints/CsvWorkspaceValidator.php
- plugin/exo/Resources/modules/exercise/Controllers/ExercisePlayerCtrl.js
This PR allows workspaces to be edited with a csv file. 
Update with a model will only handle the workspace tool permissions (wich is the most common use case).
> [CoreBundle] Workspaces can be edited with csv.

- plugin/path/Entity/Path/Path.php
- plugin/path/EventListener/Resource/PathListener.php
> [PathBundle] fixes #1273

- plugin/path/Controller/StepConditionController.php
> [PathBundle] fixes broken team conditions

- main/core/Resources/modules/profile/Controller/ProfileController.js
- main/core/Resources/modules/profile/Partial/profile.html
- plugin/cursus/Controller/API/AdminManagementController.php
- plugin/cursus/Controller/API/CursusController.php
- plugin/cursus/Entity/CourseSession.php
- plugin/cursus/Resources/modules/Management/Controller/GeneralParametersCtrl.js
- plugin/cursus/Resources/modules/Management/Partial/general_parameters.html
- plugin/cursus/Resources/translations/cursus.en.yml
- plugin/cursus/Resources/translations/cursus.fr.yml
> [CursusBundle] Adds a link to workspace in training tab of profile

- plugin/cursus/Resources/modules/Management/Partial/course_management.html
> [CursusBundle] Removes unused buttons

- plugin/exo/Resources/modules/question/Directives/Type/MatchQuestionDirective.js
(Re)allow to connect one proposal to multiple labels for ToBind questions
> [ExoBundle] To bind connect one proposal to multiple labels

- .travis.yml
> Fix cd on custom branch in travis config

- plugin/exo/Serializer/Question/QuestionSerializer.php
> [exo-v2] fixes Question deserialization

- composer.json
| Bug fix?      | Not sure...
If we're lucky this might have something to do with broken builds.
> Remove duplicate entry in composer.json

- plugin/exo/Form/InteractionOpenType.php
- plugin/exo/Listener/Log/DisplayLogListener.php
- Remove unused orthographyCorrect form entry from InteractionOpenType 
- Change duplicate service names between log / resource listeners
> Exo v2 listeners

- composer.json
| BC breaks?    no
@stefk let's try this
> [CoreBundle] Fixed claroline/claroline travis build.

- plugin/exo/Controller/Api/ExerciseController.php
- plugin/exo/Entity/Exercise.php
- plugin/exo/Entity/Question.php
- plugin/exo/Entity/Step.php
- plugin/exo/Installation/AdditionalInstaller.php
- plugin/exo/Installation/Updater/Updater080000.php
- plugin/exo/Library/Testing/Persister.php
- plugin/exo/Migrations/pdo_mysql/Version20161010214401.php
- plugin/exo/Serializer/ExerciseSerializer.php
- plugin/exo/Serializer/Question/QuestionSerializer.php
- plugin/exo/Serializer/StepSerializer.php
- plugin/exo/Tests/Controller/Api/ExerciseControllerChoiceTest.php
- plugin/exo/Tests/Controller/Api/ExerciseControllerCommonTest.php
- plugin/exo/Tests/Controller/Api/ExerciseControllerMatchTest.php
- plugin/exo/Tests/Controller/Api/HintControllerTest.php
- plugin/exo/Tests/Controller/Api/PaperControllerTest.php
- plugin/exo/Tests/Data/json/exercise/valid/with-steps.json
- plugin/exo/Tests/Data/json/hint/valid/full.json
- plugin/exo/Tests/Data/json/misc/keyword/valid/full.json
- plugin/exo/Tests/Repository/QuestionRepositoryTest.php
- plugin/exo/Tests/Serializer/ExerciseSerializerTest.php
- plugin/exo/Tests/Serializer/HintSerializerTest.php
- plugin/exo/Tests/Serializer/Misc/KeywordSerializerTest.php
- Adds UUIDs on Exercise and Steps and uses it.
- Generate UUIDs from mysql in updater
- Change updater conditions
@pitrackster @stefk
> [exo-v2] adds UUID and cleans Additional Installer

- main/core/Converter/AuthenticatedUserConverter.php
- main/core/Converter/CurrentUserConverter.php
- main/core/Converter/MultipleIdsConverter.php
- main/core/Converter/StrictIdConverter.php
- main/core/Library/Installation/Plugin/ConfigurationChecker.php
- main/core/Tests/Unit/Converter/AuthenticatedUserConverterTest.php
- main/core/Tests/Unit/Converter/CurrentUserConverterTest.php
- main/core/Tests/Unit/Converter/MultipleIdsConverterTest.php
- main/core/Tests/Unit/Converter/StrictIdConverterTest.php
- main/core/Tests/Unit/Library/Configuration/PlatformConfigurationHandlerTest.php
- main/core/Tests/Unit/Library/Installation/OperationExecutorTest.php
- main/core/Tests/Unit/Library/Installation/Plugin/ConfigurationCheckerTest.php
- main/core/Tests/Unit/Library/Installation/Plugin/DatabaseWriterTest.php
- main/core/Tests/Unit/Library/Installation/Plugin/InstallerTest.php
- main/core/Tests/Unit/Persistence/ObjectManagerTest.php
- phpunit.xml
- plugin/badge/Tests/Unit/Rule/Constraints/ActionConstraintTest.php
- plugin/badge/Tests/Unit/Rule/Constraints/BadgeConstraintTest.php
- plugin/badge/Tests/Unit/Rule/Constraints/DoerConstraintTest.php
- plugin/badge/Tests/Unit/Rule/Constraints/OccurenceConstraintTest.php
- plugin/badge/Tests/Unit/Rule/Constraints/ReceiverConstraintTest.php
- plugin/badge/Tests/Unit/Rule/Constraints/ResourceConstraintTest.php
- plugin/badge/Tests/Unit/Rule/Constraints/ResultConstraintTest.php
- plugin/badge/Tests/Unit/Rule/ValidatorTest.php
> Tests restoration

- plugin/announcement/Manager/AnnouncementManager.php
| Fixed tickets | #1276 
- Workspace code has been added in the mail object
- Workspace code and name have been added at the end of the mail content
> [AnnouncementBundle] Adds workspace code and name in sent mail

- plugin/path/Resources/modules/path/Controller/PathEditCtrl.js
As said in https://github.com/claroline/Distribution/pull/1394, this is the correct way to handle publication in path. The TODO is not needed.
> [PathBundle] remove TODO

- plugin/video-player/Resources/translations/videojs.en.yml
- plugin/video-player/Resources/translations/videojs.fr.yml
- plugin/video-player/Resources/views/player.html.twig
> [VideoPlayerBundle] The generated html is now easily editable.

- main/core/Manager/UserManager.php
> [CoreBundle] Fixing import with code.

- main/core/Command/Import/CreateUserFromCsvCommand.php
- main/core/Manager/UserManager.php
> [CoreBundle] Users logs

- main/core/Resources/modules/homeTabs/Partial/admin_home_tabs.html
- main/core/Resources/modules/homeTabs/Partial/desktop_home_tabs.html
- main/core/Resources/modules/homeTabs/Partial/workspace_home_tabs.html
- main/core/Resources/modules/homeTabs/Service/HomeTabService.js
- main/core/Resources/modules/widgets/Partial/admin_widgets.html
- main/core/Resources/modules/widgets/Partial/widgets.html
- main/core/Resources/modules/widgets/Partial/workspace_widgets.html
- main/core/Resources/modules/widgets/Service/WidgetService.js
> [CoreBundle] Interprets html in hometab & widget title

- composer.json
> [AgendaBundle] update composer.json

- main/core/Manager/MailManager.php
> [CoreBundle] Fixing mailer on user delete.

- plugin/image-player/Resources/public/css/images.css
- plugin/image-player/Resources/views/image.html.twig
> [ImagePlayerBundle] Real size image + remove gray borders (Fixes #1432)

- plugin/image-player/Listener/ImagePlayerListener.php
- plugin/image-player/Resources/views/image.html.twig
- plugin/text-player/Listener/TextPlayerListener.php
- plugin/text-player/Resources/views/text.html.twig
- plugin/video-player/Listener/VideoPlayerListener.php
- plugin/video-player/Resources/views/video.html.twig
> Hides download button for Image, Video & Text player if not authorized

- plugin/collecticiel/Controller/DropController.php
> [CollecticielBundle] Fixes notation

- main/core/Command/Removal/EmptyWorkspaceCommand.php
- main/core/Entity/Role.php
- main/core/Manager/MailManager.php
- main/core/Manager/RoleManager.php
- main/core/Repository/GroupRepository.php
- main/core/Repository/UserRepository.php
| Fixed tickets | #1438 
This is the CLI part of #1438
> [CoreBundle] CLI tool for emptying workspace roles.

- plugin/path/Entity/Path/Path.php
- plugin/path/Form/AbstractPathType.php
- plugin/path/Manager/PathManager.php
- plugin/path/Migrations/pdo_mysql/Version20161017161733.php
- plugin/path/Resources/modules/path/Partial/edit.html
- plugin/path/Resources/modules/path/Service/PathService.js
- plugin/path/Resources/modules/step/Controller/StepBaseCtrl.js
- plugin/path/Resources/modules/step/Partial/show.html
- plugin/path/Resources/modules/summary/Directive/SummaryItemShowDirective.js
- plugin/path/Resources/modules/summary/Partial/show-item.html
- plugin/path/Resources/translations/messages.en.yml
- plugin/path/Resources/translations/messages.fr.yml
- plugin/path/Resources/translations/path_wizards.en.yml
- plugin/path/Resources/translations/path_wizards.fr.yml
Added option to path settings to allow/forbid users to manually set/change his/her progression.
> [path] manual progression allowed

- plugin/exo/Resources/modules/exercise/Partials/overview.html
> [ExoBundle] fixes #1048

- main/core/Rule/Constraints/ResultConstraint.php
- plugin/badge/Resources/translations/icap_badge.en.yml
- plugin/badge/Resources/translations/icap_badge.es.yml
- plugin/badge/Resources/translations/icap_badge.fr.yml
- plugin/badge/Resources/views/Form/rules.html.twig
- plugin/dropzone/Event/Log/LogDropGradeAvailableEvent.php
- plugin/dropzone/Repository/DropRepository.php
- Adds message for advanced option "result" in rules
- Allows automatic badge attribution to Peer evaluation based on note/result score
- Fixes problem with correctors in case wher corrector has no drops (admin)
> [Dropzone Bundle] Fixes, integrated automatic badge award based on result/grade

- plugin/media-resource/Resources/modules/modals/Partials/optionsModal.html
> [EnrichedActiveListening] wrong pattern in url field

- plugin/video-player/Resources/views/player.html.twig
> [VideoPlayerBundle] video size

- plugin/path/Resources/less/loading-bar.less
- plugin/path/Resources/less/wizards.less
- plugin/path/Resources/modules/app.js
- plugin/path/Resources/modules/appModuleBase.js
- plugin/path/Resources/modules/editor.js
- plugin/path/Resources/modules/player.js
| Fixed tickets | #1133
For consistency, added the same spinner than dashboard and exercise.
Removed also the object creation in the editor and the player since PathApp has no attribute.
> [path] Add a progress loader for player and editor

- plugin/exo/Controller/QuestionController.php
- plugin/exo/Installation/Updater/Updater080000.php
- plugin/exo/Library/Question/QuestionType.php
- plugin/exo/Listener/Entity/QuestionListener.php
- plugin/exo/Resources/modules/editor/components/modals.jsx
- plugin/exo/Serializer/Question/Type/ChoiceTypeSerializer.php
- plugin/exo/Serializer/Question/Type/PairTypeSerializer.php
- plugin/exo/Serializer/Question/Type/SetTypeSerializer.php
- plugin/exo/Services/classes/QTI/GraphicImport.php
- plugin/exo/Services/classes/QTI/HoleImport.php
- plugin/exo/Services/classes/QTI/MatchingImport.php
- plugin/exo/Services/classes/QTI/OpenImport.php
- plugin/exo/Services/classes/QTI/OpenLongImport.php
- plugin/exo/Services/classes/QTI/OpenOneWordImport.php
- plugin/exo/Services/classes/QTI/OpenShortImport.php
- plugin/exo/Services/classes/QTI/QcmImport.php
- plugin/exo/Services/classes/QTI/QtiImport.php
- plugin/exo/Tests/Data/json/question/set/invalid/incoherent-solution-member-ids.json
- plugin/exo/Tests/Data/json/question/set/invalid/incoherent-solution-set-ids.json
- plugin/exo/Tests/Serializer/ExerciseSerializerTest.php
- plugin/exo/Tests/Serializer/HintSerializerTest.php
- plugin/exo/Tests/Serializer/Question/QuestionSerializerTest.php
- plugin/exo/Tests/Serializer/StepSerializerTest.php
- plugin/exo/Tests/Validator/JsonSchema/Question/Type/MatchTypeValidatorTest.php
- plugin/exo/Tests/Validator/JsonSchema/Question/Type/SetTypeValidatorTest.php
- plugin/exo/Validator/JsonSchema/Question/Type/MatchTypeValidator.php
- plugin/exo/Validator/JsonSchema/Question/Type/PairTypeValidator.php
- plugin/exo/Validator/JsonSchema/Question/Type/SetTypeValidator.php
- Adds Pair, Set, Match types (serialization is WIP)
- Migrates old Match data (needs a plugin update)
- Fixes QTI import (this are just quick fixes, the whole system needs to be updated)
> [exo-v2] API updates

- .travis.yml
- composer.json
ping @ngodfraind, @stefk, @LaurentGruber.
> abandon support of PHP 5.5

- plugin/cursus/Controller/API/AdminManagementController.php
- plugin/cursus/Manager/CursusManager.php
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
> [CursusBundle] Fixes bool value in string

- plugin/exo/Resources/modules/step/Partials/show.html
> [ExoBundle] fixes #1487

- plugin/exo/Resources/public/js/interactionHole.js
- plugin/exo/Resources/views/InteractionGraphic/edit.html.twig
- plugin/exo/Resources/views/InteractionGraphic/new.html.twig
| Fixed tickets | #1481
Fixes some JS errors in the question editor.
This fixes the graphic question creation/edition. The other parts of the issue are not fixed yet.
@CPASimUSante.
> [ExoBundle] fixes js errors in editor

- .travis.yml
- main/core/Entity/User.php
> [travis] Fix composer target for stable branches

- main/core/Resources/less/layout.less
- main/core/Resources/views/Administration/Parameters/generalForm.html.twig
| Fixed tickets | https://github.com/claroline/Distribution/issues/1406
This PR is on 8.x because it's a fix
> fix markup and css for portfolio admin page

- .travis.yml
- main/core/Entity/User.php
- main/core/Resources/less/layout.less
- main/core/Resources/views/Administration/Parameters/generalForm.html.twig
> Merge 8.x fixes

- main/core/Controller/Tool/WorkspaceParametersController.php
- main/core/Form/WorkspaceEditType.php
- main/core/Resources/translations/platform.en.yml
- main/core/Resources/translations/platform.fr.yml
> (8.x) [CoreBundle] Worskpace acces dates

- plugin/exo/Controller/Api/PaperController.php
- plugin/exo/Manager/PaperManager.php
Shuffle proposals and labels when needed
> [ExoBundle] Match question shuffle items

- composer.json
- plugin/exo/Entity/Exercise.php
- plugin/exo/Entity/Question.php
- plugin/exo/Entity/Step.php
- plugin/exo/Services/classes/QTI/QtiImport.php
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
Fixes creation of Exercise, Step and Questions in old editors.
> [exo-v2] auto generate UUIDs in entities

- main/core/Resources/views/Layout/javascripts.html.twig
Add es6-shim to ensure old browser compatibility (IE11)
> [CoreBundle] cdnjs es6-shim added to ensure backward compatibility

- plugin/exo/Resources/modules/editor/items/open.js
- plugin/exo/Resources/modules/editor/items/open.jsx
- plugin/exo/Resources/modules/editor/items/open.test.js
Add open question to editor
Player is still missing
> [ExoBundle] Editor v2 open question

- plugin/cursus/Controller/CursusController.php
- plugin/cursus/Resources/views/Cursus/sessionInformationsModal.html.twig
- plugin/cursus/Resources/views/Widget/coursesRegistrationWidget.html.twig
- plugin/cursus/Resources/views/Widget/myCoursesWidget.html.twig
> Displays all events in session information modal from registration widget

- main/core/Form/HomeTabType.php
> Allows to choose User role in ws tab config

- plugin/cursus/Controller/CursusController.php
> Makes courses list widget accessible to anonymous

- main/core/Resources/server/webpack/shared.js
- webpack.test.js
> Exo update master

- main/core/Resources/server/webpack/shared.js
- webpack.test.js
> [exo-v2] fixes webpack config

- plugin/exo/Resources/modules/editor/items/words.js
- plugin/exo/Resources/modules/editor/items/words.jsx
- plugin/exo/Resources/modules/editor/items/words.test.js
- plugin/exo/Resources/modules/editor/style.css
- plugin/exo/Resources/translations/ujm_exo.en.yml
- plugin/exo/Resources/translations/ujm_exo.fr.yml
- Add negative-score positive-score css classes depending on the item score
- Replace keyword textarea field with simple text input
- Translations
> [ExoBundle] Words question form minor changes

- plugin/cursus/Controller/API/AdminManagementController.php
- plugin/cursus/Manager/CursusManager.php
Fixes string('false') casted as bool(true)
> [8.x] Fixes bool cast

- main/core/Manager/UserManager.php
- main/core/Validator/Constraints/CsvUserValidator.php
Updates password of existing users during csv import only if password is not empty
> User password update via csv

- plugin/cursus/Manager/CursusManager.php
> [CursusManager] typo

- .travis.yml
Increase allocated memory to composer.
> increases composer memory in travis

- main/core/Resources/less/layout.less
> [Theme] fixes body padding

- plugin/cursus/Resources/modules/DocumentModel/Partial/document_model_selection_modal.html
> Change "ok" button's name for "send"

- main/core/Resources/views/layout.html.twig
- plugin/scorm/Controller/ScormController.php
- plugin/scorm/Entity/Scorm12Resource.php
- plugin/scorm/Entity/Scorm2004Resource.php
- plugin/scorm/Entity/ScormResource.php
- plugin/scorm/Form/ScormConfigType.php
- plugin/scorm/Manager/ScormManager.php
- plugin/scorm/Migrations/pdo_mysql/Version20161213092816.php
- plugin/scorm/Resources/translations/scorm.en.yml
- plugin/scorm/Resources/translations/scorm.fr.yml
- plugin/scorm/Resources/views/scorm12ConfigurationModalForm.html.twig
- plugin/scorm/Resources/views/scorm12MenuSco.html.twig
- plugin/scorm/Resources/views/scorm2004ConfigurationModalForm.html.twig
- plugin/scorm/Resources/views/scorm2004MenuSco.html.twig
Allows to configure a SCORM resource to hide the topbar
> Allows to configure scorm display

- main/core/Resources/modules/library/Configuration/Configuration.js
- main/core/Resources/modules/users/Controller/UserController.js
- plugin/cursus/Resources/config/config.js
> Adds custom action to access courses management in users admin

- main/core/Controller/Tool/WorkspaceParametersController.php
- main/core/Resources/translations/platform.de.yml
- main/core/Resources/translations/platform.en.yml
- main/core/Resources/translations/platform.es.yml
- main/core/Resources/translations/platform.fr.yml
- main/core/Resources/translations/platform.nl.yml
| Fixed tickets | #1601 
Fixes anonymous user registration via workspace form with "validation" option. Shows message to user that his account has been created however he won't be able to access the workspace unless an administrator validates his enrollment.
> [CoreBundle] Fixed anonymous subscription with validation

- main/core/Resources/views/Tool/desktop/home/desktopHome.html.twig
> fixes html markup in desktop home

- main/dev/Resources/travis/fetch-deps.bash
> [travis] ignore npm-shrinkwrap

- main/dev/Resources/travis/fetch-deps.bash
> [exo-v2] merge master

- plugin/exo/Resources/modules/quiz/components/quiz.jsx
> [ExoV2] fix navbar nav

- plugin/exo/Resources/modules/quiz/normalizer.js
> [ExoV2] Clean denormalizer

- plugin/claco-form/Manager/ClacoFormManager.php
> Fixes access to entries from another resource

- main/core/Resources/modules/users/Controller/UserController.js
> Change icone for personnal ws

- main/core/Library/Installation/AdditionalInstaller.php
- main/core/Library/Installation/Updater/DocUpdater.php
| Fixed tickets | #1424 
Fixes #1424
> [CoreBundle] Doc url updater

- plugin/exo/Resources/modules/quiz/components/quiz.jsx
- plugin/exo/Resources/modules/quiz/components/top-bar.jsx
- plugin/exo/Resources/modules/quiz/components/top-bar.test.js
- plugin/exo/Resources/modules/quiz/decorators.js
- plugin/exo/Resources/modules/quiz/decorators.test.js
- plugin/exo/Resources/modules/quiz/editor/actions.test.js
- plugin/exo/Resources/modules/quiz/editor/reducers.js
- plugin/exo/Resources/modules/quiz/editor/selectors.js
- plugin/exo/Resources/modules/quiz/editor/selectors.test.js
- plugin/exo/Resources/modules/quiz/enums.js
- plugin/exo/Resources/modules/quiz/papers/components/papers.jsx
- plugin/exo/Resources/modules/quiz/player/selectors.js
- plugin/exo/Resources/modules/quiz/selectors.js
- plugin/exo/Resources/modules/quiz/store.js
- plugin/exo/Resources/modules/quiz/store.test.js
> Fix main reducer + papers WIP

- plugin/exo/Resources/modules/quiz/decorators.test.js
- plugin/exo/Resources/modules/quiz/defaults.js
- plugin/exo/Resources/modules/quiz/editor/components/item-form.jsx
Replace Item info field with description field
> [ExoV2] Fields missing

- plugin/exo/Resources/modules/quiz/decorators.js
- plugin/exo/Resources/modules/quiz/defaults.js
Add empty items array to default step
> [ExoV2] Default step bug

- plugin/exo/Resources/modules/components/form/radios.jsx
- plugin/exo/Resources/modules/components/form/radios.test.js
- plugin/exo/Resources/modules/items/choice/editor.jsx
- plugin/exo/Resources/modules/quiz/editor/style.css
- plugin/exo/Resources/modules/quiz/enums.js
- plugin/exo/Resources/translations/ujm_exo.en.yml
- plugin/exo/Resources/translations/ujm_exo.fr.yml
- Change the checkbox "réponses multiples" for 2 radio buttons : "réponse multiple"/"réponse unique" on the same line
- Change the label "résultat fixe" by "score global"
- Add colours to choice items containers depending on there score (red for =< 0 or green >0)
> [ExoV2] Choice form update

- plugin/exo/Resources/modules/quiz/editor/components/thumbnail.jsx
- plugin/exo/Resources/modules/quiz/editor/selectors.js
- plugin/exo/Resources/modules/quiz/editor/selectors.test.js
- plugin/exo/Resources/modules/quiz/editor/style.css
- Get back to original sizes
- Display title when "big screen"
- Display an icon in  "small screen"
> [ExoV2] Thumbnails

- main/core/Controller/WorkspaceController.php
- plugin/cursus/Resources/views/Widget/myCoursesListForWidget.html.twig
- plugin/cursus/Resources/views/Widget/myCoursesListForWidgetChronologic.html.twig
> [CursusBundle] Fixing the resource opening.

- plugin/exo/Resources/modules/items/choice/editor.js
- plugin/exo/Resources/modules/items/choice/editor.test.js
- plugin/exo/Resources/modules/quiz/store.js
> [exo-v2] fixes choice question creation

- main/core/Manager/ToolRightsManager.php
> [CoreBundle] Access to resource manager also update root permissions.

- plugin/exo/Resources/less/items/choice.less
- plugin/exo/Resources/modules/items/choice/paper.jsx
May need some methods renaming
> [exo-v2] ChoicePaper css.

- plugin/exo/Resources/less/quiz/player.less
- plugin/exo/Resources/modules/quiz/player/components/item-player.jsx
- plugin/exo/Resources/modules/quiz/player/components/player.jsx
- Remove question panel header
- Replace deprecated <content> markups with<div>
- Remove unused styles
> [ExoV2] Reapply some style changes

- plugin/exo/Resources/modules/api/README.md
- plugin/exo/Resources/modules/quiz/player/actions.js
- Adds small doc on how to use the api middleware
- Fixes test mode which was broken by my last PR.
> [exo-v2] fixes test mode + adds api middleware doc

- plugin/exo/Resources/less/quiz/index.less
- plugin/exo/Resources/less/quiz/papers.less
- plugin/exo/Resources/modules/quiz/papers/components/paper.jsx
- plugin/exo/Resources/modules/quiz/papers/components/papers.jsx
> [ExoV2] padding on paper list and paper details

- plugin/exo/Resources/modules/quiz/player/actions.js
- plugin/exo/Resources/translations/ujm_exo.en.yml
- plugin/exo/Resources/translations/ujm_exo.fr.yml
> [exo-v2] fixes player navigation when no answer to save

- plugin/claco-form/Resources/modules/ClacoForm/Controller/EntryViewCtrl.js
- plugin/claco-form/Resources/modules/ClacoForm/Partial/entry_view.html
- plugin/claco-form/Resources/modules/ClacoForm/clacoForm.js
> Fixes date field format

- plugin/claco-form/Resources/modules/ClacoForm/Partial/entry_form.html
- plugin/claco-form/Resources/translations/clacoform.en.yml
- plugin/claco-form/Resources/translations/clacoform.fr.yml
> Disables entry creation if no field is defined

- plugin/exo/Entity/Exercise.php
- plugin/exo/Resources/modules/quiz/player/components/player.jsx
> [exo-v2] bug fixes

- plugin/exo/Resources/less/items/words.less
- plugin/exo/Resources/less/main.less
- plugin/exo/Resources/modules/items/choice/feedback.jsx
- plugin/exo/Resources/modules/items/choice/paper.jsx
- plugin/exo/Resources/modules/items/components/feedback-btn.jsx
- plugin/exo/Resources/modules/items/components/metadata.jsx
- plugin/exo/Resources/modules/items/components/score.jsx
- plugin/exo/Resources/modules/items/words/feedback.jsx
- plugin/exo/Resources/modules/items/words/index.js
- plugin/exo/Resources/modules/items/words/paper.jsx
- plugin/exo/Resources/modules/items/words/player.jsx
- plugin/exo/Resources/modules/items/words/player.test.js
- plugin/exo/Resources/modules/items/words/utils/highlight.jsx
- plugin/exo/Resources/modules/items/words/utils/utils.js
- plugin/exo/Resources/modules/items/words/utils/utils.test.js
- plugin/exo/Resources/modules/quiz/player/actions.js
> Exo words question

- plugin/cursus/Resources/views/Widget/myCoursesListForWidgetChronologic.html.twig
> [8.x] Fixes chronologic view of widget when workspace is missing

- plugin/exo/Resources/less/quiz/add-item-modal.less
- plugin/exo/Resources/less/quiz/editor.less
- plugin/exo/Resources/less/quiz/index.less
> [ExoV2] Fix question modal css

- plugin/exo/Resources/less/main.less
- plugin/exo/Resources/less/quiz/editor.less
- plugin/exo/Resources/less/quiz/overview.less
- plugin/exo/Resources/less/quiz/papers.less
- plugin/exo/Resources/less/quiz/player.less
- plugin/exo/Resources/less/variables.less
- plugin/exo/Resources/modules/quiz/overview/overview.jsx
- Harmonize width in player / editor / overview / paper list / paper view
- add variables.less for the bundle
> same width for  editor / player / papers / overview

- plugin/exo/Resources/less/items/match.less
- plugin/exo/Resources/modules/items/match/editor.jsx
Fix the popover position compution in match editor
> [exo-v2] Match question editor popover fix

- composer.json
- doc/remote-user-synchronization/README.md
- main/core/Form/Administration/SecurityTokenType.php
- main/core/Library/Installation/Plugin/Installer.php
- main/core/Library/PluginBundle.php
- main/core/Library/PluginBundleInterface.php
- main/core/Manager/PluginManager.php
- main/core/Tests/Unit/Library/Installation/Plugin/InstallerTest.php
- plugin/remote-user-synchronization/ClarolineRemoteUserSynchronizationBundle.php
- plugin/remote-user-synchronization/Controller/RemoteUserSynchronizationController.php
- plugin/remote-user-synchronization/Resources/config/config.yml
- plugin/remote-user-synchronization/Resources/config/routing.yml
> Adds RemoteUserSynchronizationBundle to distribution

- main/core/Resources/modules/users/Partial/user_content.html
> Fixes actions that don't appear in users management table

- main/core/Manager/WorkspaceManager.php
Fixing GUI workspace import (no logger so a condition is needed)
> [CoreBundle] Fixing GUI Workspace import.

- main/core/Controller/AuthenticationController.php
- main/core/Resources/modules/authentication/index.js
- main/core/Resources/modules/fos-js-router/index.js
- main/core/Resources/modules/fos-js-router/module.js
- main/core/Resources/views/Authentication/authenticated.html.twig
- package.json
- plugin/exo/Resources/modules/api/middleware.js
- plugin/exo/Resources/translations/ujm_exo.en.yml
- plugin/exo/Resources/translations/ujm_exo.fr.yml
- adds a core function to handle authentication in a separate window/tab
- uses it in the quiz api middleware
- works fine with standard login auth, needs live/docker testing for other authentication means
> [ExoV2] Reauth window

- main/core/Manager/WorkspaceManager.php
> [CoreBundle] Fixing GUI Workspace import. (#1813)

- main/core/Listener/Resource/TextListener.php
- plugin/text-player/Listener/TextPlayerListener.php
Fixes the text opening (wrong file was changed).
> [CoreBundle] Fix open text

- plugin/exo/Controller/Api/CorrectionController.php
- plugin/exo/Controller/Api/PaperController.php
- plugin/exo/Entity/Attempt/Answer.php
- plugin/exo/Entity/Attempt/Paper.php
- plugin/exo/Library/Testing/Persister.php
- plugin/exo/Manager/Attempt/AnswerManager.php
- plugin/exo/Manager/Attempt/PaperManager.php
- plugin/exo/Manager/CorrectionManager.php
- plugin/exo/Manager/ExerciseManager.php
- plugin/exo/Migrations/pdo_mysql/Version20170120131422.php
- plugin/exo/Migrations/pdo_mysql/Version20170120150009.php
- plugin/exo/Repository/PaperRepository.php
- plugin/exo/Resources/config/routing.yml
- plugin/exo/Resources/modules/quiz/player/reducers.js
- plugin/exo/Serializer/Attempt/AnswerSerializer.php
- plugin/exo/Serializer/Question/Type/ClozeQuestionSerializer.php
- plugin/exo/Tests/Controller/Api/CorrectionControllerTest.php
- plugin/exo/Tests/Manager/CorrectionManagerTest.php
- plugin/exo/Tests/Repository/PaperRepositoryTest.php
- ID in answers export
- Api for manual correction (retrieve the list of questions/answers to correct and submit correction).
- Tests
> [exo-v2] api for manual correction

- plugin/exo/Resources/modules/quiz/editor/components/quiz-editor.jsx
Fixes translation for the property "Anonymize papers" in the quiz editor.
> [exo-v2] fixes translations

- plugin/exo/Resources/modules/items/components/paper-tabs.jsx
- Remove uneeded state handling
- Add a callback that allow parent components to handle tab change event
> [exo-v2] paper-tabs component minor changes

- plugin/exo/Listener/Resource/ExerciseListener.php
> [exo-v2] Fixes wasPublishedOnce initialization

- plugin/exo/Controller/Api/AttemptController.php
- plugin/exo/Controller/Api/PaperController.php
- plugin/exo/Entity/Misc/Hole.php
- plugin/exo/Entity/QuestionType/OpenQuestion.php
- plugin/exo/Manager/Attempt/PaperManager.php
- plugin/exo/Manager/AttemptManager.php
- plugin/exo/Resources/modules/items/words/editor.js
- plugin/exo/Serializer/Attempt/AnswerSerializer.php
- plugin/exo/Serializer/Question/Type/ChoiceQuestionSerializer.php
> [exo-v2] fixes keyword management

- plugin/exo/Resources/modules/quiz/decorators.js
- plugin/exo/Resources/modules/quiz/quiz.js
> [exo-v2] Fixes exo access for non-admin

- plugin/exo/Entity/Misc/Hole.php
- plugin/exo/Entity/QuestionType/ClozeQuestion.php
- plugin/exo/Installation/Updater/Updater090000.php
- plugin/exo/Library/Question/Definition/ClozeDefinition.php
- plugin/exo/Validator/JsonSchema/Attempt/AnswerData/ClozeAnswerValidator.php
- Fixes cloze answers migrations
- Adds missing method in cloze api
- Minor fixes
> [exo-v2] updates cloze questions api

- plugin/exo/Serializer/Question/Type/GraphicQuestionSerializer.php
> [exo-v2] fixes graphic serializer

- plugin/exo/Migrations/pdo_mysql/Version20170123050000.php
> [exo-v2] adds missing uuids in migration

- plugin/exo/Migrations/pdo_mysql/Version20161128104517.php
> [exo-v2] migrates missing data for steps

- plugin/exo/Resources/less/items/graphic.less
- plugin/exo/Resources/less/quiz/player.less
- plugin/exo/Resources/modules/items/graphic/components/pointable-image.jsx
- plugin/exo/Resources/modules/items/graphic/editor.js
- plugin/exo/Resources/modules/items/graphic/editor.test.js
- plugin/exo/Resources/modules/items/graphic/feedback.jsx
- plugin/exo/Resources/modules/items/graphic/player.js
- plugin/exo/Resources/modules/items/graphic/player.jsx
- plugin/exo/Resources/modules/items/graphic/player.test.js
- plugin/exo/Resources/modules/quiz/player/components/item-player.jsx
- plugin/exo/Resources/translations/ujm_exo.en.yml
- plugin/exo/Resources/translations/ujm_exo.fr.yml
- plugin/exo/Serializer/Question/Type/GraphicQuestionSerializer.php
> [ExoV2] graphic fixes + feedback basics

- plugin/exo/Resources/modules/items/match/editor.jsx
- plugin/exo/Resources/modules/items/pair/editor.js
- plugin/exo/Resources/modules/items/pair/editor.jsx
- plugin/exo/Resources/modules/items/set/editor.jsx
- plugin/exo/Resources/translations/ujm_exo.en.yml
- plugin/exo/Resources/translations/ujm_exo.fr.yml
> [exo-v2] association questions translations update

- plugin/exo/Controller/Api/ExerciseController.php
- plugin/exo/Entity/Misc/GridItem.php
- plugin/exo/Entity/QuestionType/PairQuestion.php
- plugin/exo/Resources/modules/items/pair/editor.js
- plugin/exo/Resources/modules/items/pair/editor.jsx
- plugin/exo/Resources/translations/ujm_exo.fr.yml
- plugin/exo/Serializer/Question/Type/PairQuestionSerializer.php
- plugin/exo/Validator/JsonSchema/Question/Type/PairQuestionValidator.php
> [exo-v2] Save pair question

- main/core/Manager/TransferManager.php
> Fixed problem in TransferManager

- plugin/exo/Manager/Question/QuestionManager.php
> [exo-v2] fixes bug in attempt

- .eslintrc.json
> [eslint] requires space before anon func

- plugin/exo/Resources/less/items/pair.less
> [exo-v2] Fixes long text in pair question

- plugin/exo/Resources/modules/items/pair/player.jsx
- plugin/exo/Resources/modules/items/pair/utils/utils.js
An `_` lodash import was causing a bug in tinymce resource picker
> [exo-v2] change lodash import

- main/core/Manager/FacetManager.php
- main/core/Repository/FieldFacetRepository.php
- plugin/blog/Resources/views/widget/blog.html.twig
- plugin/claco-form/Resources/modules/ClacoForm/Partial/menu.html
| Fixed tickets | #1814, #1839, #1861
> Small fixes

- plugin/exo/Resources/modules/items/pair/player.jsx
- plugin/exo/Resources/modules/items/pair/utils/utils.js
> [exo-v2] Fixes times import in Pair question player

- .travis.yml
disable phpunit : memory error
> Disable phpunit (tmp)

- plugin/exo/Resources/modules/quiz/correction/components/answers.jsx
- plugin/exo/Resources/modules/quiz/correction/components/questions.jsx
- plugin/exo/Resources/translations/ujm_exo.en.yml
- plugin/exo/Resources/translations/ujm_exo.fr.yml
> [exo-v2] Adds message if no manual correction is available

- plugin/exo/Resources/modules/quiz/editor/components/quiz-editor.jsx
- plugin/exo/Resources/modules/quiz/player/actions.js
- plugin/exo/Resources/modules/quiz/player/selectors.js
- plugin/exo/Resources/modules/utils/date.js
> [Exo] corrections at the end of exercise

- plugin/exo/Library/Question/Definition/GraphicDefinition.php
- plugin/exo/Resources/less/quiz/editor.less
- plugin/exo/Resources/modules/api/README.md
- plugin/exo/Resources/modules/api/middleware.js
- plugin/exo/Resources/modules/bank/actions/search.js
- plugin/exo/Resources/modules/items/graphic/feedback.jsx
- plugin/exo/Resources/modules/items/graphic/player.jsx
- plugin/exo/Resources/modules/quiz/components/top-bar.jsx
- plugin/exo/Resources/modules/quiz/correction/actions.js
- plugin/exo/Resources/modules/quiz/editor/actions.js
- plugin/exo/Resources/modules/quiz/editor/components/quiz-editor.jsx
- plugin/exo/Resources/modules/quiz/editor/components/step-editor.jsx
- plugin/exo/Resources/modules/quiz/player/actions.js
- plugin/exo/Resources/modules/quiz/player/components/nav-bar.jsx
> [ExoV2] bugfixes

- .travis.yml
- plugin/exo/Entity/QuestionType/AbstractQuestion.php
- plugin/exo/Installation/Updater/Updater090000.php
- plugin/exo/Migrations/pdo_mysql/Version20170123160000.php
> [exo-v2] cloze migration + fixes

- plugin/exo/Resources/modules/items/cloze/utils/utils.js
- plugin/exo/Resources/modules/quiz/papers/actions.js
- plugin/exo/Resources/modules/quiz/papers/reducer.js
- plugin/exo/Resources/modules/quiz/player/actions.js
- plugin/exo/Resources/modules/quiz/player/normalizer.js
> correction

- plugin/exo/Controller/Api/Question/QuestionController.php
- plugin/exo/Manager/Question/QuestionManager.php
- plugin/exo/Resources/modules/quiz/editor/components/import-items-modal.jsx
- plugin/exo/Resources/modules/quiz/editor/reducers.js
> [exo-v2] Editor question import

- plugin/exo/Resources/modules/quiz/actions.js
- plugin/exo/Resources/modules/quiz/editor/reducers.js
- plugin/exo/Resources/modules/quiz/reducers.js
- plugin/exo/Resources/modules/quiz/router.js
- plugin/exo/Resources/modules/quiz/selectors.js
> [ExoV2] Redirect on first step if quiz is empty

- plugin/exo/Resources/modules/items/pair/editor.js
- plugin/exo/Resources/translations/ujm_exo.en.yml
- plugin/exo/Resources/translations/ujm_exo.fr.yml
- can delete odd items
- add error messages random / no pinned item
> [exo-v2] pair question update

- plugin/exo/Resources/modules/quiz/editor/save-guard.js
> [ExoV2] Fix save guard

- plugin/exo/Resources/modules/quiz/editor/components/step-form.jsx
> [ExoV2] Remove max attempts on steps

- plugin/exo/Resources/modules/items/cloze/editor.js
- plugin/exo/Resources/modules/items/cloze/editor.jsx
- plugin/exo/Resources/translations/ujm_exo.en.yml
- plugin/exo/Resources/translations/ujm_exo.fr.yml
> Cloze errors

- plugin/exo/Resources/modules/quiz/editor/reducers.js
- plugin/exo/Resources/modules/quiz/overview/overview.jsx
> [ExoV2] Quiz max attempts

- plugin/exo/Resources/modules/items/pair/utils/utils.js
- plugin/exo/Resources/modules/quiz/papers/actions.js
- plugin/exo/Resources/modules/quiz/papers/reducer.js
- plugin/exo/Resources/modules/quiz/player/actions.js
- plugin/exo/Resources/modules/quiz/selectors.js
> [exo-v2] Allows to check paper just after submission

- plugin/exo/Resources/modules/items/cloze/utils/highlight.jsx
> Fixing feedback

- .docker/mysql/my.conf
- docker-compose.yml
> [WIP] Create docker-compose.yml

- plugin/exo/Resources/modules/items/cloze/editor.js
- plugin/exo/Resources/modules/items/cloze/feedback.jsx
- plugin/exo/Resources/modules/items/cloze/utils/highlight.jsx
> Fixing cloze feedback

- plugin/exo/Installation/Updater/Updater090000.php
> [ExoBundle] fixes answers migration

- plugin/exo/Tests/Controller/Api/CorrectionControllerTest.php
- plugin/exo/Tests/Manager/CorrectionManagerTest.php
Answer must have property "type"
> Fixes tests for exo

- plugin/exo/Resources/less/quiz/add-item-modal.less
- plugin/exo/Resources/modules/quiz/editor/components/add-item-modal.jsx
Change the way question types are displayed in the add-item-modal
> [ExoBundle] revamped add-item-modal

- plugin/website/Resources/views/Website/view.html.twig
| Fixed tickets | #1950 
Fixes #1950
> [WebsiteBundle] Added missing dlls and core js

- plugin/blog/Resources/views/layout.angular.twig
Blog info contains html code and needs to be escaped.
> [BlogBundle] Infopanel bugfix

- main/core/Resources/server/webpack/libraries.js
- main/core/Resources/views/Layout/javascripts.html.twig
> Move es6 polyfills to dll

- main/core/Controller/RegistrationController.php
I'm not sure it fixes #1937 but handling this exception better can't be a bad thing.
> [CoreBundle] No more exception on wrong link

- plugin/blog/Controller/API/ApiController.php
- plugin/blog/Resources/modules/blog/blog.controller.js
- plugin/blog/Resources/modules/blog/blog.service.js
- plugin/blog/Resources/views/layout.angular.twig
> Update layout.angular.twig (#1956)

- plugin/collecticiel/Resources/translations/collecticiel.fr.yml
- plugin/collecticiel/Resources/translations/innova_collecticiel.fr.yml
- plugin/dropzone/Resources/translations/icap_dropzone.fr.yml
> [Translations] Fixing translation typo

- plugin/website/Resources/views/Website/view.html.twig
- plugin/website/Resources/views/less/edit.less
- plugin/website/Resources/views/less/view.less
> [WebsiteBundle] Fix website view issue

- plugin/cursus/Resources/views/Mail/certificate.html.twig
- plugin/cursus/Resources/views/Mail/certificates.html.twig
- plugin/cursus/Resources/views/Mail/event_certificate.html.twig
Urls need to be absolute when sent by email.
> [CursusBundle] Fixing email urls.

- main/core/Event/Log/LogResourceCreateEvent.php
- main/core/Event/Log/LogResourcePublishEvent.php
- main/core/Event/Log/ResourceNotifiableTrait.php
@clarophil 
This should solve most of your issues.
> [Notifications] resource placed in a unpublished directory doesn't trigger notifications

- plugin/badge/Resources/views/Profile/badges.html.twig
This button has no effect and it looks like there is no import/export implementation
> [BadgeBundle] Remove useless button

- main/core/Library/Configuration/PlatformConfiguration.php
| Fixed tickets | #1984
Fixes #1984
> [CoreBundle] Fixing PlatformConfiguration

- main/core/Resources/translations/platform.es.json
- plugin/announcement/Resources/translations/announcement.es.json
> Merging again

- plugin/remote-user-synchronization/Controller/RemoteUserSynchronizationController.php
> [9.x][RemoteUserSynchronizationBundle] Checks if user exists even if userId is missing

- main/core/Resources/translations/platform.es.json
- plugin/presence/Resources/translations/presences.nl.json
> Weblate merge (last conflicts)

- plugin/exo/Migrations/pdo_mysql/Version20170118143154.php
| Fixed tickets | #1994
Same as the last one : those who have not hit the bug do not need the fix so it's safe to edit the existing migration file.
> [ExoBundle] fixes pair items migration

- plugin/agenda/Resources/views/Widget/event_widget.html.twig
- plugin/exo/Installation/AdditionalInstaller.php
- plugin/exo/Installation/Updater/Updater090000.php
- plugin/exo/Installation/Updater/Updater090002.php
- plugin/exo/Migrations/pdo_mysql/Version20170118143154.php
- plugin/remote-user-synchronization/Controller/RemoteUserSynchronizationController.php
> Merges 9.x into master

- plugin/blog/Transfer/BlogImporter.php
> [BlogBundle] fixes typo in importer

- main/core/Controller/API/User/UserController.php
- main/core/Controller/ProfileController.php
- main/core/Controller/UserController.php
- main/core/Library/Installation/AdditionalInstaller.php
- main/core/Library/Installation/Updater/Updater090200.php
- main/core/Library/Testing/Persister.php
- main/core/Manager/RoleManager.php
- main/core/Manager/UserManager.php
- main/core/Repository/RoleRepository.php
| Fixed tickets | #2057 
When the username changes, the user role is now correctly renamed.
(For the personal WS this was already correct).
This PR includes a migration to resynchronize user roles with the current user names.
This will require a **9.2.0** tag.
ping @ptsavdar
> [CoreBundle] fixes #2057

- main/core/Controller/ResourceController.php
- main/core/Listener/AuthenticationSuccessListener.php
Fixes problem with some resources that would not hide breadcrumb when the option is active in Workspace parameters.
> [CoreBundle] Fixed workspace details in view

- doc/remote-user-synchronization/README.md
- doc/remote-user-synchronization/user-token.md
- plugin/remote-user-synchronization/ClarolineRemoteUserSynchronizationBundle.php
- plugin/remote-user-synchronization/Controller/RemoteUserSynchronizationController.php
- plugin/remote-user-synchronization/Entity/RemoteUserToken.php
- plugin/remote-user-synchronization/Library/Security/Token/UserToken.php
- plugin/remote-user-synchronization/Manager/RemoteUserTokenManager.php
- plugin/remote-user-synchronization/Migrations/pdo_mysql/Version20170309095629.php
- plugin/remote-user-synchronization/Repository/RemoteUserTokenRepository.php
[RemoteUserSynchronizationBundle]
- Removes mandatory condition on password
- Adds option to disable unregistration to workspaces
- Allows to generate and associate a token to an user
- Allows to authenticate an user with a token
> [RemoteUserSynchronizationBundle] Allows to authenticate an user with a token

- plugin/exo/Manager/Attempt/AnswerManager.php
- plugin/exo/Manager/AttemptManager.php
- plugin/exo/Manager/CorrectionManager.php
- plugin/exo/Manager/Item/ItemManager.php
- plugin/exo/Validator/JsonSchema/Attempt/AnswerValidator.php
For now answers are validated against the current question version which can lead to unexpected errors.
> [ExoBundle] validates answers against paper question

- plugin/claco-form/Resources/modules/ClacoForm/Controller/EntryCreationCtrl.js
- plugin/claco-form/Resources/modules/ClacoForm/Controller/EntryEditionCtrl.js
- plugin/claco-form/Resources/modules/ClacoForm/Controller/TemplateManagementCtrl.js
- plugin/claco-form/Resources/modules/ClacoForm/Partial/template_management.html
> [ClacoForm] Fixes quote issue in template

- plugin/cursus/Entity/CourseSession.php
> [CursusBundle] Adds an option to session

- plugin/claco-form/ClarolineClacoFormBundle.php
> Fixing ClacoForm deps

- plugin/exo/Resources/modules/contents/components/content-thumbnail.jsx
- plugin/exo/Resources/modules/items/ordering/editor.jsx
- plugin/exo/Resources/modules/items/ordering/player.jsx
- plugin/exo/Resources/modules/items/pair/editor.jsx
- plugin/exo/Resources/modules/items/pair/player.jsx
- plugin/exo/Resources/modules/items/set/editor.jsx
- plugin/exo/Resources/modules/items/set/player.jsx
- plugin/exo/Resources/modules/quiz/editor/components/step-editor.jsx
- plugin/exo/Resources/modules/quiz/editor/components/thumbnail.jsx
> [ExoBundle] fixes #2067

- main/core/Library/Security/ExternalAuthenticator.php
- plugin/ldap/Manager/LdapManager.php
> Ldap hidden flag

- main/core/Controller/Administration/InternationalizationController.php
- main/core/Form/Administration/InternationalizationType.php
- main/core/Manager/LocaleManager.php
- main/core/Resources/translations/platform.en.json
- main/core/Resources/translations/platform.fr.json
- main/core/Resources/views/Administration/Internationalization/form.html.twig
| Fixed tickets | #2070, #2116
- Fixes browser page title
- Fixes security check
- Applies new layout
- Fixes form not rendered
Note : the display of checkboxes is still broken. This is a more general problem introduced by new themes. It requires more work to fix it and will have its own PR. However the form is usable.
ping @om64
> [Administration] Fixes i18n parameters

- plugin/exo/Installation/AdditionalInstaller.php
Add missing use in AdditionalInstaller
> [ExoBundle] missing use in updater

- main/core/Resources/less/tools/resource-manager.less
- main/core/Resources/public/js/resource/manager/views/resource/actions.js
- main/core/Resources/views/Tool/desktop/resource_manager/resources.html.twig
- main/core/Resources/views/Tool/workspace/resource_manager/resources.html.twig
- main/core/Resources/views/layout.html.twig
- plugin/exo/Resources/modules/items/boolean/feedback.jsx
- plugin/exo/Resources/modules/items/boolean/paper.jsx
- plugin/exo/Resources/modules/items/boolean/player.jsx
- plugin/exo/Resources/styles/quiz/papers.less
- Fixes the display of HTML content in boolean questions (ping @om64).
- Fixes ResourceManager not rendered in Desktop (ping @stefk).
> fixes ResourceManager and boolean questions

- plugin/exo/Resources/modules/components/layout/page-actions.jsx
> [ExoBundle] disables save button if no changes

- plugin/exo/Library/Item/Definition/MatchDefinition.php
resolve https://github.com/claroline/Distribution/issues/2130
> [ExoBundle] handle no answer in match question

- plugin/exo/Installation/AdditionalInstaller.php
- plugin/exo/Installation/Updater/Updater090000.php
- plugin/exo/Installation/Updater/Updater090200.php
- plugin/exo/Serializer/Question/Type/GraphicQuestionSerializer.php
| Fixed tickets | #2077
- Adds more logs in 9.0 updater.
- Deletes truncated questions from DB. On some instances there are partial questions (that are not working) in the DB which make the bank crashes.
> [ExoBundle] improves and fixes updaters

- plugin/exo/Serializer/Question/QuestionSerializer.php
| Fixed tickets | 2140
resolve https://github.com/claroline/Distribution/issues/2140
> [ExoBundle] ensure question's author is persisted

- plugin/exo/Resources/modules/items/components/score-box.jsx
- plugin/exo/Resources/modules/items/set/feedback.jsx
- plugin/exo/Resources/modules/items/set/paper.jsx
> [ExoBundle] handle no asnwer case in set question paper and feedback

- plugin/wiki/Controller/WikiController.php
- plugin/wiki/Resources/modules/wiki/wiki.controller.js
- plugin/wiki/Resources/modules/wiki/wiki.partial.html
- Wiki title displays html special chars correctly
- PDF Export is re-enabled
> [WikiBundle] Text and PDF display fixes

- main/core/Resources/views/Layout/javascripts.html.twig
The import is not needed in dev env. The condition should not have been removed.
> Fixes webpack commons

- plugin/exo/Resources/modules/items/pair/editor.js
- plugin/exo/Resources/modules/items/pair/editor.jsx
- plugin/exo/Resources/modules/items/pair/feedback.jsx
- plugin/exo/Resources/modules/items/pair/paper.jsx
- plugin/exo/Resources/modules/items/pair/player.jsx
- plugin/exo/Resources/modules/items/pair/utils/utils.js
- plugin/exo/Resources/styles/items/pair.less
- plugin/exo/Serializer/Item/Type/PairQuestionSerializer.php
| Fixed tickets | 2100
resolve https://github.com/claroline/Distribution/issues/2100
also resolve : 
- when random set to true pair items where not properly rendered
- paper your-answers and feedback layout problems
- properly handle no coords in items
> [ExoBundle] resolve multiple problems with pair questions

- plugin/exo/Repository/ItemRepository.php
- plugin/exo/Serializer/Item/ItemSerializer.php
| Fixed tickets | 2153
resolves https://github.com/claroline/Distribution/issues/2153
- save user with the content item created
- exclude from question bank all items whose mimeTypes does not begins with `application`
> [ExoBundle] exclude content items from question bank results

- plugin/support/FormaLibreSupportBundle.php
> [SupportBundle] Adds dependency declaration to MessageBundle

- plugin/exo/Resources/styles/contents/content-thumbnail.less
> [ExoBundle] Fixes style for question objects

- main/core/Library/Transfert/RichTextFormatter.php
Adds support for hyperlink target attribute in importer richtext parser, adds a "target" option to placeholder tag. e.g: [[uid=3098,target='_blank']]
Default behaviour stays the same (links open in _self).
> Add support for hyperlink target attribute in importer parser

- main/core/Resources/server/themes/bin/index.js
Old regex was buggy if there wa a "-" in the custom theme path.
> [CoreBundle] fixes custom theme compilation

- main/core/Resources/less/widgets/slideshow.less
> [CoreBundle] fixes slideshow widgets in safari

- plugin/claco-form/Resources/modules/ClacoForm/Controller/EntryCreationCtrl.js
- plugin/claco-form/Resources/modules/ClacoForm/Controller/EntryEditionCtrl.js
- plugin/claco-form/Resources/modules/ClacoForm/Controller/EntryViewCtrl.js
- plugin/claco-form/Resources/modules/ClacoForm/Controller/TemplateManagementCtrl.js
- plugin/claco-form/Resources/modules/ClacoForm/Partial/template_management.html
- plugin/claco-form/Resources/modules/ClacoForm/Service/ClacoFormService.js
> [9.x][ClacoForm] Fixes quotes & accents in template management

- plugin/forum/Resources/views/Forum/messages.html.twig
- plugin/forum/Resources/views/searchResults.html.twig
> [ForumBundle] Fixes icon html

- plugin/exo/Resources/modules/items/cloze/editor.js
- plugin/exo/Resources/modules/items/cloze/editor.jsx
_id property added to the answer attribute to discriminate them in the editor.
> [ExoBundle] Fixing weird behaviour on equal answers for clozes

- plugin/claco-form/Controller/ClacoFormController.php
- plugin/claco-form/Manager/ClacoFormManager.php
- plugin/claco-form/Resources/modules/ClacoForm/Controller/EntriesListCtrl.js
- plugin/claco-form/Resources/modules/ClacoForm/Partial/entries_list.html
- plugin/claco-form/Resources/modules/Entry/Service/EntryService.js
- plugin/claco-form/Resources/translations/clacoform.en.json
- plugin/claco-form/Resources/translations/clacoform.fr.json
- Also copy entries when copying resource
- Adds a button to delete all entries
> [ClacoForm] Improves resource copy

- plugin/claco-form/Resources/modules/ClacoForm/Controller/CategoriesManagementCtrl.js
- plugin/claco-form/Resources/modules/ClacoForm/Controller/EntriesListCtrl.js
- plugin/claco-form/Resources/modules/ClacoForm/Controller/EntryCreationCtrl.js
- plugin/claco-form/Resources/modules/ClacoForm/Controller/EntryEditionCtrl.js
- plugin/claco-form/Resources/modules/ClacoForm/Controller/EntryViewCtrl.js
- plugin/claco-form/Resources/modules/ClacoForm/Controller/FieldsManagementCtrl.js
- plugin/claco-form/Resources/modules/ClacoForm/Controller/GeneralConfigurationCtrl.js
- plugin/claco-form/Resources/modules/ClacoForm/Controller/KeywordsManagementCtrl.js
- plugin/claco-form/Resources/modules/ClacoForm/Controller/MenuCtrl.js
- plugin/claco-form/Resources/modules/ClacoForm/Controller/TemplateManagementCtrl.js
- plugin/claco-form/Resources/modules/ClacoForm/Partial/categories_management.html
- plugin/claco-form/Resources/modules/ClacoForm/Partial/entries_list.html
- plugin/claco-form/Resources/modules/ClacoForm/Partial/entry_form.html
- plugin/claco-form/Resources/modules/ClacoForm/Partial/entry_view.html
- plugin/claco-form/Resources/modules/ClacoForm/Partial/fields_management.html
- plugin/claco-form/Resources/modules/ClacoForm/Partial/general_configuration.html
- plugin/claco-form/Resources/modules/ClacoForm/Partial/keywords_management.html
- plugin/claco-form/Resources/modules/ClacoForm/Partial/menu.html
- plugin/claco-form/Resources/modules/ClacoForm/Partial/template_management.html
- plugin/claco-form/Resources/modules/ClacoForm/clacoForm.js
- plugin/claco-form/Resources/public/css/clacoform.css
> [ClacoForm] Moves export & delete buttons of all entries

- plugin/claco-form/Resources/views/ClacoFormWidget/clacoFormWidgetOpen.html.twig
> [ClacoForm] Fixes multiple display of picture in widget

- main/core/Resources/views/Activity/index.html.twig
> [CoreBundle] hides layout in activity iframes

- main/core/Resources/less/layout/components/iframes.less
> [CoreBundle] fixes iframe display

- main/core/Library/Security/ExternalAuthenticator.php
- plugin/blog/Controller/API/ApiController.php
- plugin/blog/Controller/BlogController.php
- plugin/blog/Resources/modules/app.js
- plugin/blog/Resources/modules/blog/blog.controller.js
- plugin/blog/Resources/modules/blog/blog.partial.html
- plugin/blog/Resources/modules/blog/blog.service.js
- plugin/blog/Resources/modules/post/confirmCommentDeletion.partial.html
- plugin/blog/Resources/modules/post/post.controller.js
- plugin/blog/Resources/modules/post/post.partial.html
- plugin/blog/Resources/views/layout.angular.twig
- plugin/claco-form/ClarolineClacoFormBundle.php
- plugin/cursus/ClarolineCursusBundle.php
- plugin/exo/Installation/Updater/Updater090000.php
- plugin/exo/Installation/Updater/Updater090200.php
- plugin/exo/Serializer/Item/ItemSerializer.php
- plugin/exo/Serializer/Item/Type/GraphicQuestionSerializer.php
- plugin/forum/Resources/views/Forum/messages.html.twig
- plugin/forum/Resources/views/searchResults.html.twig
- plugin/ldap/Manager/LdapManager.php
- plugin/message/Resources/views/Message/listReceived.html.twig
- plugin/wiki/Controller/WikiController.php
- plugin/wiki/Resources/modules/wiki/wiki.controller.js
- plugin/wiki/Resources/modules/wiki/wiki.partial.html
> Merge 9.x to master

- plugin/exo/Resources/modules/quiz/papers/components/paper.test.js
- plugin/exo/Resources/modules/quiz/papers/components/papers.test.js
This will fix https://travis-ci.org/claroline/Claroline/builds/221171929.
> [ExoBundle] fixes tests

- main/core/Migrations/pdo_mysql/Version20170403165005.php
> Fixes migrations

- plugin/exo/Resources/modules/items/selection/editors/find.js
- plugin/exo/Resources/modules/items/selection/player.jsx
- plugin/exo/Resources/modules/items/selection/utils/utils.js
> [ExoBundle:Selections] Some bugfixes

- plugin/exo/Resources/modules/quiz/papers/components/papers.jsx
- plugin/exo/Resources/modules/quiz/player/components/attempt-end.jsx
- plugin/exo/Resources/modules/quiz/selectors.js
Missing selector was causing an error when user finishes it's attempt.
We need to know if this selector was consciously removed and why before merging.
> [ExoBundle] re-add editable quiz selector

- plugin/exo/Resources/modules/items/selection/player.jsx
- plugin/exo/Resources/translations/question_types.en.json
- plugin/exo/Resources/translations/question_types.fr.json
- plugin/exo/Resources/translations/ujm_exo.fr.json
…s in one page)
- Add translations
- Fix the player find mode if multiple questions in one page
> [ExoBundle:Selection] player find mode fix

- plugin/exo/Resources/modules/items/boolean/editor.js
A wrong reference to makeId method was causing an error when creating a boolean question
> [ExoBundle] wrong reference to makeId method

- plugin/exo/Resources/modules/items/words/utils/highlight.jsx
> [ExoBundle] color fix

- main/core/Manager/LocaleManager.php
- main/core/Resources/config/suggested/assetic.yml
> [CoreBundle] German translations available

- main/core/Manager/ResourceManager.php
> [CoreBundle] Fixing resource reordering.

- main/core/Resources/less/themes/default/variables.less
- main/core/Resources/modules/layout/page/components/page-actions.jsx
- main/core/Resources/translations/platform.en.json
- main/core/Resources/translations/platform.fr.json
- main/core/Resources/views/Authentication/login.html.twig
- main/core/Resources/views/Layout/javascripts.html.twig
- main/core/Resources/views/Widget/embed/iframe.html.twig
- main/core/Resources/views/Widget/embed/widget.html.twig
- plugin/path/Resources/modules/path/Controller/PathBaseCtrl.js
- plugin/path/Resources/modules/path/Partial/edit.html
- plugin/path/Resources/modules/path/Partial/show.html
- plugin/path/Resources/modules/resource-primary/Partial/edit.html
- plugin/path/Resources/modules/resource-secondary/Partial/edit.html
- plugin/path/Resources/modules/summary/Partial/edit-item.html
- plugin/path/Resources/modules/summary/Partial/show-item.html
- plugin/path/Resources/styles/components/breadcrumbs.less
- plugin/path/Resources/styles/components/resources.less
- plugin/path/Resources/styles/components/summary.less
- plugin/path/Resources/styles/mixins.less
- plugin/path/Resources/styles/variables.less
- plugin/pdf-player/Resources/modules/pdf/Partial/view_pdf.html
- plugin/pdf-player/Resources/styles/components/player.less
- plugin/pdf-player/Resources/views/pdf.html.twig
- plugin/scorm/Resources/styles/resources/scorm.less
- plugin/scorm/Resources/views/scorm12MenuSco.html.twig
- plugin/scorm/Resources/views/scorm2004MenuSco.html.twig
- plugin/scorm/assets.json
- Use new styles for path actions bar.
- Update styles for breadcrumbs (aka, removes levels color).
- Use primary style for login button.
- Small fixes in scorm players.
- Fix PDF menu display.
- Fix embedded widget display.
> fixes ui bugs

- plugin/agenda/Manager/AgendaManager.php
> [9.x] Button links in invitation event in calendar are absolute

- main/core/Resources/views/Workspace/list.html.twig
> [CoreBundle] Fixing workspace list search placeholder.

- plugin/exo/Resources/modules/items/graphic/components/answer-table.jsx
- plugin/exo/Resources/modules/items/graphic/paper.jsx
- plugin/exo/Resources/translations/ujm_exo.en.json
- plugin/exo/Resources/translations/ujm_exo.fr.json
> [ExoBundle] Fixing graphic type title.

- plugin/dropzone/Controller/CorrectionController.php
- plugin/dropzone/Controller/DropController.php
Fixes #1586
| Fixed tickets | fixes #1586
> [DropZone bundle] Fixes dropzone issue #1586

- main/core/Resources/views/Layout/javascripts.html.twig
> fixes tinyMCE js imports

- plugin/lti/Controller/LtiController.php
- plugin/lti/Resources/views/Lti/app.html.twig
- plugin/lti/Resources/views/Lti/appEdit.html.twig
> Admin : Edit LTI app

- plugin/exo/Resources/modules/quiz/editor/components/item-objects-editor.jsx
> Fixes title of object modal form

- plugin/claco-form/Resources/views/ClacoFormWidget/clacoFormWidgetOpen.html.twig
- plugin/path/Resources/views/Widget/slideshow.html.twig
…& clacoForm). closes #2337
| Fixed tickets | #2337
> Fixes redirection when clicking on slideshow buttons in widget

- main/core/Controller/LayoutController.php
- main/core/Resources/modules/organization/Partial/organizations_main.html
> [CoreBundle] Administration tools order.

- main/core/Resources/modules/widgets/Partial/admin_widgets.html
- main/core/Resources/modules/widgets/Partial/widgets.html
- main/core/Resources/modules/widgets/Partial/workspace_widgets.html
- main/core/Resources/views/Log/view_short_list.html.twig
- main/core/Resources/views/Widget/embed/widget.html.twig
> Fixes permanent horizontal scrollbar in widget

- plugin/exo/Resources/modules/components/score-gauge.jsx
> [ExoBundle] Fixing score gauge for null score.

- plugin/exo/Resources/modules/items/choice/index.js
> [ExoBundle] Choice question score total bugfix.

- main/core/Manager/MailManager.php
- plugin/agenda/Resources/views/Widget/agenda_widget.html.twig
> [AgendaBundle] Fixing widget layout.

- main/core/Manager/UserManager.php
> [CoreBundle] Fixing user managements for groups.

- main/core/Library/Transfert/RichTextFormatter.php
- plugin/exo/Transfer/ExerciseImporter.php
1st change but more will be required
| Fixed tickets | Fixes #2369
> [CoreBundle] Use guid for transfer

- main/core/Controller/API/Desktop/DesktopHomeController.php
- main/core/Controller/API/Workspace/WorkspaceHomeController.php
- main/core/Controller/Administration/HomeTabController.php
- main/core/Resources/views/API/Widget/widgetInstanceEditForm.html.twig
| New feature?  | yes/
| Fixed tickets | Fixes #2375
Show widget type when configuring it.
> [CoreBundle] Show widget type when configuring.

- main/core/Resources/modules/widgets/Partial/admin_widgets.html
- main/core/Resources/modules/widgets/Partial/widgets.html
- main/core/Resources/modules/widgets/Partial/workspace_widgets.html
> [CoreBundle] Fixing widget title color.

- main/core/Resources/less/themes/default/variables.less
- main/core/Resources/modules/widgets/Partial/admin_widgets.html
- main/core/Resources/modules/widgets/Partial/widgets.html
- main/core/Resources/modules/widgets/Partial/workspace_widgets.html
This reverts commit 16a9359efdf4e5355c2971024111a9031eb22a47.
> Revert "[CoreBundle] Fixing widget title color. (#2383)" and update less file

- main/core/Resources/views/Layout/topBar.html.twig
> [CoreBundle] No broken link on empty logo

- main/core/Resources/views/Administration/Parameters/appearanceForm.html.twig
> Hides themes management link

- main/core/Manager/RoleManager.php
- main/core/Resources/modules/desktopHome/Partial/main.html
> Fixes desktop lock

- plugin/exo/Resources/modules/items/match/player.jsx
- plugin/exo/Resources/styles/items/match.less
| Fixed tickets | #2258 
[Match question]
- Updates position of anchors after loading images
- Stretches choices vertically
> Fixes position of anchors in match question

- plugin/collecticiel/Controller/DocumentController.php
- plugin/collecticiel/Resources/translations/collecticiel.en.json
- plugin/collecticiel/Resources/translations/collecticiel.fr.json
- plugin/collecticiel/Resources/translations/collecticiel.nl.json
> Collecticiel directory name

- plugin/exo/Controller/Resource/ExerciseController.php
- plugin/exo/Resources/modules/quiz/components/quiz.jsx
- plugin/exo/Resources/modules/quiz/papers/components/papers.jsx
> Only displays manual correction button to papers admin

- plugin/exo/Manager/ExerciseManager.php
> Sets a string value for finished field in csv export of results

- plugin/remote-user-synchronization/Controller/RemoteUserSynchronizationController.php
> [RemoteUserSynchronizationBundle] Forces utf-8 encoding

- plugin/lti/Resources/translations/lti.fr.json
- plugin/lti/Resources/translations/lti.fr.yml
> Update and rename lti.fr.yml to lti.fr.json

- plugin/lti/Resources/translations/resource.en.json
- plugin/lti/Resources/translations/resource.en.yml
> Update and rename resource.en.yml to resource.en.json

- plugin/lti/Resources/translations/resource.fr.json
- plugin/lti/Resources/translations/resource.fr.yml
> Update and rename resource.fr.yml to resource.fr.json

- main/core/Library/Installation/AdditionalInstaller.php
- main/core/Library/Installation/Updater/Updater090300.php
> Fixing update

- plugin/claco-form/Manager/ClacoFormManager.php
> Also sends mail when sending message

- plugin/claco-form/Manager/ClacoFormManager.php
> Also sends mail when sending message to categories managers

- main/core/Library/Installation/Updater/Updater090300.php
- main/core/Manager/ResourceManager.php
- main/core/Manager/RoleManager.php
- main/core/Manager/WorkspaceManager.php
- main/core/Serializer/Workspace/WorskpaceSerializer.php
- plugin/exo/Serializer/Item/Type/GridQuestionSerializer.php
There are still some issues.
Fixes from 3l.
> [CoreBundle] Maj to v10 migrations fixes

- plugin/claco-form/Manager/ClacoFormManager.php
- plugin/claco-form/Resources/modules/Field/Controller/FieldEditionModalCtrl.js
> Fixes notifications at entry creation

- main/core/API/Finder/Workspace.php
- main/core/Resources/modules/administration/workspace/actions.js
- main/core/Resources/modules/layout/data/types/date/index.js
> [CoreBundle] Fixing workspace search

- main/core/API/Finder/Workspace.php
> [CoreBundle] Workspace search API

- main/core/Controller/API/Resource/ResourceNodeController.php
> Fixes resource node routes

- main/core/Resources/modules/layout/resource/components/resource-actions.jsx
> fixes rights management tooltips

- main/core/API/Finder/Workspace.php
- main/core/Manager/RightsManager.php
> Use timestamp

- plugin/claco-form/Resources/modules/ClacoForm/Service/ClacoFormService.js
> Adds entries export for claco form

- main/core/Listener/AdministrationToolListener.php
> [CoreBundle] AdministrationTool event

- plugin/exo/Resources/modules/quiz/player/components/attempt-end.jsx
> [ExoBundle] fixes typo

- plugin/exo/Entity/Exercise.php
- plugin/exo/Manager/ExerciseManager.php
> [ExoBundle] makes sure quiz is persisted on publish

- main/core/Resources/modules/layout/resource/components/resource-actions.jsx
> [CoreBundle] hides resource management if no rights

- plugin/exo/Resources/translations/question_types.fr.json
> [ExoBundle] Typo

- plugin/exo/Library/Item/Definition/ClozeDefinition.php
- plugin/exo/Resources/modules/items/graphic/index.js
- plugin/exo/Resources/modules/items/grid/index.js
still some issues:
50336 [2017-06-13 11:28:19] request.CRITICAL: Uncaught PHP Exception UJM\ExoBundle\Library\Item\Definition\Exception\UnregisteredDefinitionException: "No registered question handler for mime "text/html""       at /home/ceb/claroline/vendor/claroline/distribution/plugin/exo/Library/Item/ItemDefinitionsCollection.php line 88 {"exception":"[object] (UJM\\ExoBundle\\Library\\Item\\Definition\\Exception\\Unreg      isteredDefinitionException(code: 0): No registered question handler for mime \"text/html\" at /home/ceb/claroline/vendor/claroline/distribution/plugin/exo/Library/Item/ItemDefinitionsCollection.php:      88)"} []
Also it's very VERY slow. …
> [ExoBundle] Fixes for clozes for docimology

- main/core/Manager/IconSetManager.php
> [CoreBundle] Handle exception throw for corrupted thumbnails

- main/core/Library/Transfert/RichTextFormatter.php
- plugin/website/Transfert/WebsiteImporter.php
Adds missing richtext parsing in website importer for its header and footer.
> [WebsiteBundle]Adds richtext parsing in importer for website header and footer

- plugin/website/Resources/views/Website/view.html.twig
> [WebsiteBundle] Fixed website analytics issue

- main/core/Library/Utilities/ThumbnailCreator.php
> [CoreBundle] Fixed script for not supported extensions

- main/core/Library/Installation/Updater/Updater100000.php
Probably lost / forgot to merge them.
> [CoreBundle] Missing use and stuff for v10 upgrade

- update-version.sh
> Upgrade refactoring

- main/core/Library/Installation/Updater/Updater090300.php
- main/core/Manager/WorkspaceManager.php
> [CoreBundle] Fix Updater090300 error

- main/core/Manager/WorkspaceManager.php
> [CoreBundle] Fixing user registration.

- plugin/exo/Resources/modules/quiz/decorators.test.js
- plugin/exo/Resources/modules/quiz/defaults.js
- plugin/exo/Serializer/ExerciseSerializer.php
> [ExoBundle] fixes quiz endMessage

- main/core/Resources/modules/translation/module.js
Otherwise translations are not always loaded (ie pathbundle).
> Fixing translations module.

- plugin/announcement/Resources/views/announcementsList.html.twig
> [AnnoucenementBundle] Fixing edition/supppression button display.

- plugin/blog/Transfer/BlogImporter.php
Adds missing comments parsing in blog importer.
> [BlogBundle] Adds missing comments parsing in blog importer

- main/core/Doctrine/Query/Replace.php
- main/core/Resources/config/suggested/doctrine_prod.yml
- plugin/external-user-group-synchronization/Repository/ExternalResourceSynchronizationRepository.php
> [ExternalSyncBundle] Enhanced external group search

- plugin/external-user-group-synchronization/Manager/ExternalSynchronizationManager.php
> [ExternalSync] Fixed some minor issues in user sync

- plugin/external-user-group-synchronization/Resources/modules/synchronization/group/group-list.controller.js
> Fixed small interface sync issue

- main/core/Migrations/pdo_mysql/Version20170620161356.php
> [CoreBundle] Fixed minor issue in resource icons uuid migration

- plugin/external-user-group-synchronization/Manager/ExternalSynchronizationManager.php
> [ExternalSync] Disabled mail notification on external user sync

- plugin/exo/Installation/Updater/Updater090000.php
Migrations for v9 where no longer executed.
> [ExoBundle] fixes migrations

- plugin/path/Controller/Api/StepConditionController.php
- plugin/path/Controller/Resource/PathController.php
- plugin/path/Manager/StepManager.php
- plugin/path/Resources/views/manageResults.html.twig
- Fixed api for StepController
- Fixed publish withTutor
- Fixed results page
> [PathBundle] Fixed some issues in path bundle

- plugin/blog/Resources/modules/app.js
- plugin/blog/Resources/modules/panels/panel.infobar.partial.html
This filter is too restrictive and prevented infobar display with some embedded images.
> [BlogBundle] Remove angular filter

- main/core/Resources/views/Home/menuSettings.html.twig
- main/core/Resources/views/Layout/topBar.html.twig
> [CoreBundle] Fixed logo issue after folder move

- main/core/Resources/modules/tinymce/tinymce.js
> [CoreBundle] Tinymce - Fixing object%20object not found error in js

- main/core/Library/Installation/Plugin/DatabaseWriter.php
> [CoreBundle] Restoration system for masks

- plugin/badge/Migrations/pdo_mysql/Version20170620161602.php
- plugin/cursus/Migrations/pdo_mysql/Version20170620133509.php
> [Migrations] Fixing uuids initialization.

- main/core/Resources/modules/administration/workspace/components/workspaces.jsx
> [CoreBundle] Fixing workspace administration filter

- plugin/exo/Resources/modules/items/cloze/selectors.js
| Fixed tickets | #2492, #2469
> [ExoBundle] fixes #2492 / #2469

- main/core/Library/Installation/Plugin/CheckerInterface.php
- main/core/Library/Installation/Plugin/Configuration.php
- main/core/Library/Installation/Plugin/ConfigurationChecker.php
- main/core/Library/Installation/Plugin/DatabaseWriter.php
- main/core/Library/Installation/Plugin/Recorder.php
- main/core/Library/Installation/Plugin/RoutingChecker.php
- main/core/Library/Installation/Plugin/Validator.php
- plugin/cursus/Migrations/pdo_mysql/Version20170620133509.php
- Fixes external plugin updaters
- Fixes cursus migrations
> [CoreBundle] Fixes for external plugins and cursus migrations

- main/core/Resources/modules/utilities/app/bootstrap.js
- main/core/Resources/modules/utilities/app/router.js
- package.json
> [CoreBundle] adds react router and utilities

- plugin/exo/Resources/modules/bank/components/question-list.jsx
> [ExoBundle] Fixing question bank layout.

- main/core/Command/ChangeIconSetCommand.php
- main/core/Manager/IconSetManager.php
> [CoreBundle] Create command to change icon set

- main/core/Entity/Model/OrderTrait.php
- main/core/Entity/Model/UuidTrait.php
- main/core/Library/Utilities/ClaroUtilities.php
| Fixed tickets | Fixes #343 
Use Ramsey library for uuids.
> [CoreBundle] Uuid generation

- plugin/path/Resources/styles/components/summary.less
> [PathBundle] fixes #2639

- plugin/cursus/Entity/Course.php
- plugin/cursus/Entity/Cursus.php
- plugin/cursus/Library/Testing/CursusPersister.php
- plugin/cursus/Manager/CursusManager.php
> [CursusBundle] Uuid set in entity constructor.

- main/core/Manager/WorkspaceManager.php
> [CoreBundle] Workspace creation (previous fix merged slightly too fast)

- main/core/Command/DatabaseIntegrity/ResourceWorkspaceIntegrityCheckerCommand.php
- main/core/Manager/ResourceManager.php
> [CoreBundle] Integrity checker command for resources updated.

- main/core/Manager/WorkspaceManager.php
> [CoreBundle] Activities not copied when copying a workspace.

- plugin/path/Resources/styles/components/breadcrumbs.less
- plugin/path/Resources/styles/components/path.less
> [PathBundle] fixes tinymce styles

- main/core/Resources/config/suggested/doctrine_prod.yml
| Fixed tickets | #2677
Suite à ce rapport: https://github.com/claroline/Distribution/issues/2677
> Using database_port in Doctrine configuration

- plugin/exo/Serializer/Item/Type/GraphicQuestionSerializer.php
> [ExoBundle] fixes graphic question validation error

- main/core/Controller/API/Workspace/WorkspaceController.php
- main/core/Controller/WorkspaceAnalyticsController.php
- main/core/Entity/User.php
- main/core/Manager/UserManager.php
- main/core/Migrations/pdo_mysql/Version20170720120711.php
- main/core/Repository/UserRepository.php
- main/core/Resources/views/Tool/workspace/analytics/workspaceManagerActivityEvaluations.html.twig
- main/core/Serializer/Workspace/WorskpaceSerializer.php
There is an issue with the getUsersByRolesIncludingGroups() because it's used with a pager in WorkspaceAnalyticsController::workspaceManagerActivityEvaluationsShowAction()
> [CoreBundle] Solving the workspace administation perf issue.

- plugin/scorm/Resources/modules/Results/Partial/scormResults.html
- plugin/scorm/Resources/public/css/scormResults.css
- plugin/scorm/Resources/translations/scorm.en.json
- plugin/scorm/Resources/translations/scorm.fr.json
> [10.x] Adds column for suspend data in SCORM 1.2 results page

- main/core/Manager/RightsManager.php
| Fixed tickets | #2704 
Ça sera pas suffisant pour les gros arbres mais ça devrait aider dans un premier temps.
> [CoreBundle] Don't log changeset on recursive permission change.

- plugin/exo/Resources/modules/quiz/editor/components/item-form.jsx
- plugin/exo/Resources/modules/quiz/editor/components/step-editor.jsx
- plugin/exo/Serializer/Item/ItemSerializer.php
Make it consistent with json-quiz
> [ExoBundle] Renaming property for json-quiz

- composer.json
> [10.x] Adds BigBlueButtonBundle in composer.json

- plugin/exo/Resources/modules/quiz/editor/components/quiz-editor.jsx
> [ExoBundle] Restoring "success score".

- plugin/competency/Resources/modules/my-objectives/components/competency.jsx
> [CompetencyBundle] Rounds percentage of competency progress

- plugin/competency/Entity/Ability.php
> [CompetencyBundle] Filters active resources for abilities

- plugin/competency/Manager/ProgressManager.php
- plugin/competency/Repository/AbilityRepository.php
- plugin/competency/Tests/Repository/AbilityRepositoryTest.php
> Fixes issue of competency acquired when passing only 1 resource

- main/core/API/Finder/ResourceNodeFinder.php
- main/core/API/FinderProvider.php
- plugin/exo/Command/JsonQuizExportCommand.php
- plugin/exo/Command/JsonQuizImportCommand.php
- plugin/exo/Controller/Api/ExerciseController.php
- plugin/exo/Manager/JsonQuizManager.php
- plugin/exo/Serializer/Item/Type/MatchQuestionSerializer.php
Usage:
claroline:json-quiz:import [path] [owner username] [workspace code]
claroline:json-quiz:export [destination folder]
> [ExoBundle] Cli tool for import/export json quiz

- plugin/exo/Resources/modules/items/set/paper.jsx
- plugin/exo/Resources/modules/items/words/index.js
- plugin/exo/Resources/modules/items/words/paper.jsx
- plugin/exo/Resources/modules/items/words/utils/utils.js
- plugin/exo/Resources/styles/items/words.less
> [10.x] Adds stats for Words items

- plugin/exo/Resources/modules/items/ordering/index.js
- plugin/exo/Resources/modules/items/ordering/paper.jsx
- plugin/exo/Resources/modules/items/ordering/utils/utils.js
- plugin/exo/Resources/styles/items/ordering.less
> [10.x] Adds stats for Ordering items

- plugin/exo/Resources/modules/items/cloze/components/answers-stats-table.jsx
- plugin/exo/Resources/modules/items/cloze/index.js
- plugin/exo/Resources/modules/items/cloze/paper.jsx
- plugin/exo/Resources/modules/items/cloze/utils/utils.js
- plugin/exo/Resources/styles/items/cloze.less
> [10.x] Adds stats for Cloze items

- main/core/Library/Mailing/Client/SwiftMailer.php
> [Mailer] Fixing validation

- main/core/Library/Configuration/PlatformDefaults.php
set allow_self_registration to false by defaut for security
> adapt default options

- main/core/Resources/views/Form/organization_picker.html.twig
> [CoreBundle] Fixing organization picker in prod mode.

- main/core/API/FinderProvider.php
- main/core/Controller/API/Organization/OrganizationController.php
- main/core/Resources/views/Form/organization_picker.html.twig
> [CoreBundle] FinderProvider limit nullable.

- main/core/Manager/ThemeManager.php
- main/core/Twig/ThemeExtension.php
Instead of throwing an error.
(but if the default can not be found either, the error is still thrown).
> [CoreBundle] fallbacks to default if current theme not found

- main/core/Form/DataTransformer/OrganizationPickerTransformer.php
- main/core/Library/Security/Voter/ResourceVoter.php
- main/core/Resources/views/Form/organization_picker.html.twig
> [CoreBundle] Fix Voter, Group creation crash, orga field in dev mode.

- main/core/Menu/Builder.php
> [CoreBundle] Fixing logout error after account usurpation

- plugin/external-user-group-synchronization/Manager/ExternalSynchronizationManager.php
> [ExternalSyncBundle] Fix external sync group update

- main/core/Command/Removal/EmptyWorkspaceCommand.php
usage: php app/console claroline:workspace:empty M1GEONUM1D1 visitor -n -u -vvv
@clarophil
> [CoreBundle] Empty workspace command improvement.

- main/core/Manager/MaskManager.php
> [CoreBundle] Fix resource mask decoder duplication on update

- main/core/Command/DatabaseIntegrity/ResourceMaskDecoderIntegrityCheckerCommand.php
- main/core/Entity/Resource/MaskDecoder.php
- main/core/Library/Installation/AdditionalInstaller.php
- main/core/Library/Installation/Updater/Updater100030.php
- main/core/Manager/MaskManager.php
- main/core/Repository/ResourceMaskDecoderRepository.php
| Fixed tickets | #2854 
Complementary to #2860
> [CoreBundle] Fix already broken mask decoders with command and updater

- main/core/Command/Removal/RemoveWorkspaceCommand.php
> [CoreBundle] Fixed claroline:remove:workspaces command

- composer.json
> Fixing php svg version

- main/core/Resources/server/themes/build.js
> fixes themes directory creation fail

- main/core/Manager/WorkspaceManager.php
> [CoreBundle] Fixing the "isManager" method.

- main/core/Manager/WorkspaceManager.php
> [CoreBundle] Right handling for children in creation from model.

- main/core/Manager/WorkspaceManager.php
> [CoreBundle] fixing ws creation (all ids are null)

- plugin/blog/Resources/views/widget/blog.html.twig
> [10.x] Fixes redirection to first tab when clicking on a link in widget

- main/core/Command/DatabaseIntegrity/IconSetBuilderCommand.php
> [CoreBundle] Icon set builder cmd.

- plugin/exo/Resources/modules/quiz/editor/components/step-editor.jsx
> [ExoBundle] Fixing moving stuff

- plugin/exo/Installation/AdditionalInstaller.php
- plugin/exo/Installation/Updater/Updater100200.php
- plugin/exo/Manager/ExerciseManager.php
- plugin/exo/Resources/modules/items/open/paper.jsx
- plugin/exo/Resources/modules/quiz/papers/utils.js
| Fixed tickets | #2942 #2938 #2935 #2932
Fixes #2942 
Fixes #2938 
Fixes #2935 
Fixes #2932
> [ExoBundle] Fixing some bugs

- plugin/bibliography/Controller/BookReferenceController.php
> [BibliographyBundle] Fix bibliography issues (easy fix, no updaters)

- plugin/exo/Installation/Updater/Updater100200.php
old relations with papers throw foreign keys errors on delete.
> [ExoBundle] deletes obsolete & buggy table

- main/core/Controller/Widget/ResourcesWidgetController.php
> [CoreBundel] check if parent exists for widget resource.

- main/core/Controller/Widget/ResourcesWidgetController.php
- main/core/Library/Security/Voter/ResourceVoter.php
- plugin/path/Manager/WidgetManager.php
- plugin/path/Repository/PathRepository.php
> Minor fixes

- main/core/Library/Installation/OperationExecutor.php
> [CoreBundle] Fixing platform update.

- main/core/Resources/views/Tool/workspace/home/workspaceHome.html.twig
> [CoreBundle] adds some ui enhancements

- main/core/Resources/less/users/login.less
- main/core/Resources/views/Authentication/login.html.twig
> [CoreBundle] fixes login page width

- main/core/Library/Session/SessionHandlerFactory.php
Option to let php choose by itself the session handler.
> [CoreBundle] Added option for native php handler (bypass file session handler)

- main/core/Resources/less/users/login.less
> [CoreBundle] fixes login page on Firefox

- main/core/Repository/ResourceQueryBuilder.php
Removed redundant select in query which had a huge impact in the execution time.
> [CoreBundle] Improve picker performance

- plugin/exo/Library/Model/AttemptParametersTrait.php
- plugin/exo/Resources/modules/quiz/editor/components/quiz-editor.jsx
- plugin/exo/Resources/modules/quiz/papers/components/paper.jsx
> [ExoBundle] fixes #2966

- plugin/exo/Resources/modules/bank/components/questions.jsx
> [ExoBundle] displays question content in bank grid

- bower.json
- main/core/API/Serializer/UserSerializer.php
- main/core/Resources/less/layout/list/data-grids.less
- main/core/Resources/less/tools/home.less
- main/core/Resources/less/tools/index.less
- main/core/Resources/modules/administration/scheduled-task/actions.js
- main/core/Resources/modules/administration/workspace/actions.js
- main/core/Resources/modules/administration/workspace/components/workspaces.jsx
- main/core/Resources/modules/layout/components/dropdown.jsx
- main/core/Resources/modules/layout/list/components/data-actions.jsx
- main/core/Resources/modules/layout/list/components/data-list.jsx
- main/core/Resources/modules/layout/list/components/header.jsx
- main/core/Resources/modules/layout/list/components/view/data-grid.jsx
- main/core/Resources/modules/layout/list/containers/data-list.jsx
- main/core/Resources/modules/layout/list/prop-types.js
- main/core/Resources/styles/tools/home.less
- main/core/Resources/views/Administration/HomeTab/adminHomeTabsConfig.html.twig
- main/core/Resources/views/Tool/desktop/home/desktopHome.html.twig
- main/core/Resources/views/Tool/workspace/home/workspaceHome.html.twig
- main/core/assets.json
- plugin/exo/Library/Attempt/PaperGenerator.php
> multiple fixes

- plugin/path/Manager/UserProgressionManager.php
> [PathBundle] fixes progression and anonymous users

- plugin/claco-form/Library/Installation/AdditionalInstaller.php
> [10.x] Fixes ClacoForm updater name

- plugin/claco-form/API/Finder/EntryFinder.php
> [10.x] Fixes ClacoForm entries list

- main/core/API/Serializer/Task/ScheduledTaskSerializer.php
- plugin/announcement/Controller/AnnouncementController.php
- plugin/announcement/Entity/Announcement.php
- plugin/announcement/Event/Log/LogAnnouncementCreateEvent.php
- plugin/announcement/Event/Log/LogAnnouncementDeleteEvent.php
- plugin/announcement/Event/Log/LogAnnouncementEditEvent.php
- plugin/announcement/Listener/AnnouncementListener.php
- plugin/announcement/Manager/AnnouncementManager.php
- plugin/announcement/Migrations/pdo_mysql/Version20171004104559.php
- plugin/announcement/Resources/public/js/create_form.js
- plugin/announcement/Resources/translations/announcement.en.json
- plugin/announcement/Resources/translations/announcement.fr.json
- plugin/announcement/Resources/translations/announcement.nl.json
- plugin/announcement/Resources/views/createForm.html.twig
- plugin/announcement/Tests/Controller/AnnouncementControllerTest.php
- plugin/announcement/Tests/Manager/AnnouncementManagerTest.php
> [10.x] Announcement task

- main/core/Controller/WorkspaceController.php
> [CoreBundle] Fixing last ws list for anon.

- plugin/claco-form/API/Finder/EntryFinder.php
- plugin/claco-form/Controller/ClacoFormController.php
- plugin/claco-form/Resources/modules/resources/claco-form/player/entry/actions.js
- plugin/claco-form/Resources/modules/resources/claco-form/player/entry/components/entries.jsx
- plugin/claco-form/Resources/modules/resources/claco-form/player/entry/components/entry-create-form.jsx
- plugin/claco-form/Resources/modules/resources/claco-form/player/entry/components/entry-edit-form.jsx
- plugin/claco-form/Resources/modules/resources/claco-form/player/entry/components/entry-view.jsx
> [10.x] Updates entry creation/edition form to handle template

- main/core/API/Crud.php
- main/core/Security/PermissionCheckerTrait.php
There is an issue in the mapping for the collection patching wich i'm going to fix too here.
> [CoreBundle] Permission checker trait

- main/core/Controller/WorkspaceController.php
- main/core/Form/WorkspaceType.php
> [CoreBundle] Fixing workspace creation form.

- plugin/exo/Resources/modules/items/ordering/paper.jsx
- plugin/exo/Resources/modules/items/set/paper.jsx
> [ExoBundle] Fixing classifying stats.

- plugin/exo/Resources/modules/quiz/editor/validators.js
| Fixed tickets | #3009 
Fixes #3009
> [ExoBundle] Fixing max copy amount validation.

- plugin/exo/Resources/modules/items/ordering/editor.js
| Fixed tickets | #2982 
Fixes #2982
> [ExoBundle] Fixing ordering penalty var type.

- plugin/exo/Resources/modules/items/match/editor.jsx
- plugin/exo/Resources/modules/quiz/editor/components/step-editor.jsx
- plugin/exo/Resources/modules/quiz/editor/validators.js
| Fixed tickets |  #3017 
Fixes #3017
> [ExoBundle] Refresh jsplumb on item header click

- plugin/exo/Resources/modules/quiz/editor/components/step-editor.jsx
| Fixed tickets | #2996
Fixes #2996
> [ExoBundle] Fixing d&d for questions.

- plugin/exo/Resources/modules/items/match/editor.jsx
- plugin/exo/Resources/modules/quiz/editor/components/step-editor.jsx
Reverts claroline/Distribution#3076
> Revert "[ExoBundle] Refresh jsplumb on item header click"

- plugin/exo/Manager/DocimologyManager.php
- plugin/exo/Manager/Item/ItemManager.php
| Fixed tickets | #2957
Fixes #2957
> Fix docimology generation

- main/core/Entity/Model/CodeTrait.php
> [CoreBundle model typo

- main/core/Resources/views/Form/organization_picker.html.twig
| Fixed tickets | #3093 
Fixes #3093
> [CoreBundle] Fix orga field.

- main/core/Listener/AdministrationToolListener.php
Fixes problem with notification configuration (via admin interface) as well as badges configuration.
> [CoreBundle] Fixed admin notification configuration + badge configuration

- main/core/Resources/less/themes/default/variables.less
- main/core/Resources/less/users/message.less
- plugin/claco-form/Resources/modules/resources/claco-form/player/entry/components/entry-view.jsx
> [CoreBundle] adds vars to theme user messages

- main/core/Form/Administration/MailServerType.php
- main/core/Library/Mailing/Client/Postal.php
- main/core/Library/Mailing/Message.php
- main/core/Manager/MailManager.php
- plugin/message/Manager/MessageManager.php
> Fixes mail server config + adds replyTo for mail forwarded from message

- main/core/Library/Security/TokenUpdater.php
- main/core/Manager/UserManager.php
- main/core/Manager/WorkspaceManager.php
@ptsavdar 
It also should fix the first issue of #3099
> [CoreBundle] Fixing csv import

- plugin/announcement/Controller/API/AnnouncementController.php
> Fixes permissions check

- main/core/Library/Mailing/Mailer.php
- plugin/claco-form/Resources/modules/resources/claco-form/player/entry/components/entry-edit-form.jsx
> Fixes edition of an entry

- plugin/claco-form/Resources/modules/resources/claco-form/player/entry/components/entries.jsx
> Fixes clacoform status column in entries list

- plugin/announcement/Controller/API/AnnouncementController.php
> Fixes permissions for announcement creation

- plugin/announcement/Listener/Resource/AnnouncementListener.php
- plugin/announcement/Manager/AnnouncementManager.php
> Fixes resource copy & deletion by allowing to disable logs

- plugin/scorm/Controller/API/ScormController.php
- plugin/scorm/Entity/Scorm12ScoTracking.php
- plugin/scorm/Entity/Scorm2004ScoTracking.php
- plugin/scorm/Manager/ScormManager.php
- plugin/scorm/Resources/modules/Results/Partial/scormResults.html
- plugin/scorm/Resources/modules/Results/Service/ScormResultsService.js
- plugin/scorm/Resources/translations/scorm.en.json
- plugin/scorm/Resources/translations/scorm.fr.json
> Adds last session date

- plugin/scorm/Resources/modules/Results/Partial/scormResults.html
> Shows last session date for scorm 2004

- main/core/Resources/public/js/sidebar.js
> [CoreBundle] Fixed sidebar scroll on view-as dropdown click

- main/core/Manager/IconManager.php
| Fixed tickets | #3207
variable declaration was missing
> [CoreBundle]Custom icon creation fix

- plugin/exo/Controller/Api/PaperController.php
- plugin/exo/Library/Attempt/PaperGenerator.php
- plugin/exo/Manager/ExerciseManager.php
> [ExoBundle] Fixes some csv export issues.

- plugin/agenda/Resources/views/Widget/task_widget.html.twig
- plugin/favourite/Resources/config/config.yml
- plugin/favourite/Resources/views/widget/favourite.html.twig
> Fixes display of Favourite widget and Tasks widget

- plugin/cursus/Resources/views/Widget/myCoursesListForWidgetChronologic.html.twig
- plugin/cursus/Resources/views/Widget/myCoursesWidget.html.twig
> Fixes links to workspace in MyCourses widget

- main/core/Repository/Task/ScheduledTaskRepository.php
> Fixes repo function to retrieve tasks to execute

- plugin/website/Entity/WebsitePage.php
- plugin/website/Migrations/pdo_mysql/Version20171123130644.php
> [WebsiteBundle]  Fixed page constraint on resource removal

- .travis.yml
I feel really guilty about this PR :'(.
> [temp] disables karma in travis

- main/core/Listener/AuthenticationSuccessListener.php
> [CoreBundle] Fixed redirect after session expiration

- plugin/blog/Resources/modules/blog/blog.controller.js
Unnecessary line of code prevented search from being fullfilled.
> [BlogBundle] Fix blog search

- plugin/cursus/Controller/API/AdminManagementController.php
- plugin/cursus/Manager/CursusManager.php
- plugin/cursus/Resources/modules/Course/Controller/CourseCreationModalCtrl.js
- plugin/cursus/Resources/modules/Course/Controller/CourseEditionModalCtrl.js
> [CursusBundle] Fixes workspace model field in course form

- main/core/Manager/ResourceManager.php
> [CoreBundle] Fixes non existent function call in ResourceManager

- plugin/exo/Controller/Api/PaperController.php
> [ExoBundle] Fix papers csv export

- plugin/cursus/Controller/API/AdminManagementController.php
- plugin/cursus/Manager/CursusManager.php
> Fixes organization field in cursus & course form

- main/core/Security/Voter/WidgetVoter.php
> Fixes widget voter

- plugin/remote-user-synchronization/Controller/RemoteUserSynchronizationController.php
> Update RemoteUserSynchronizationController.php (#3191)

- main/core/Resources/modules/data/types/locale/components/form-group.jsx
- main/core/Resources/modules/user/data/types/organization/components/form-group.jsx
Fixes the `parent` field in Organization form.
> [CoreBundle] adds auth info in async form components

- main/core/Resources/modules/administration/user/group/reducer.js
- main/core/Resources/modules/administration/user/location/reducer.js
- main/core/Resources/modules/administration/user/organization/reducer.js
- main/core/Resources/modules/administration/user/role/reducer.js
- main/core/Resources/modules/administration/user/user/reducer.js
- main/core/Resources/modules/data/form/actions.js
- main/core/Resources/modules/data/list/containers/data-list.jsx
- main/core/Resources/modules/data/list/containers/data-tree.jsx
> [CoreBundle] fixes data-list auto reloading

- main/core/Resources/modules/data/list/reducer.js
> [CoreBundle] fixes data list reducer

- main/core/API/Serializer/User/RoleSerializer.php
- main/core/API/Transfer/Adapter/Explain/Csv/ExplanationBuilder.php
- main/core/Entity/Organization/Organization.php
- main/core/Form/WorkspaceEditType.php
- main/core/Resources/modules/administration/user/role/components/role-list.jsx
- main/core/Resources/samples/user/valid/create/full.json
- main/core/Resources/schema/group.json
- main/core/Resources/schema/user.json
- main/core/Security/Voter/OrganizationVoter.php
I removed the required field for the schema and started using $refs.
I might reuse it later but it would break the csv import with the current definitions.
> [CoreBundle] Multiple administration fixes

- main/core/Resources/modules/validation/index.js
- plugin/exo/Resources/modules/contents/text-content/editor.js
- plugin/exo/Resources/modules/items/boolean/editor.js
- plugin/exo/Resources/modules/items/choice/editor.js
- plugin/exo/Resources/modules/items/cloze/editor.js
- plugin/exo/Resources/modules/items/match/editor.js
- plugin/exo/Resources/modules/items/ordering/editor.js
- plugin/exo/Resources/modules/items/pair/editor.js
- plugin/exo/Resources/modules/items/selection/editor.js
- plugin/exo/Resources/modules/items/set/editor.js
- plugin/exo/Resources/modules/quiz/editor/validators.js
> Refactors notBlank validator

- main/core/API/Serializer/User/UserSerializer.php
- main/core/Resources/modules/administration/user/index.js
- main/core/Resources/modules/administration/user/user/actions.js
- main/core/Resources/modules/administration/user/user/components/users.jsx
- main/core/Resources/modules/user/actions.js
Include some bugfixes for enable/disable users aswell.
> [CoreBundle] Users change password

- main/core/Resources/modules/workspace/Services/WorkspaceService.js
- main/core/Resources/views/Layout/javascripts.html.twig
> [CoreBundle] js assets

- main/core/API/Finder/User/UserFinder.php
- main/core/Controller/APINew/User/OrganizationController.php
- main/core/Entity/User.php
- main/core/Resources/modules/administration/user/organization/actions.js
- main/core/Resources/modules/administration/user/organization/components/organization.jsx
- main/core/Resources/modules/administration/user/organization/reducer.js
- main/core/Resources/translations/platform.en.json
- main/core/Resources/translations/platform.fr.json
> [CoreBundle] Organization manager back in admin

- main/core/Controller/Tool/WorkspaceParametersController.php
- main/core/Manager/WorkspaceManager.php
Fixes security breach on WS user self-registration with validation enabled which gets overridden if user already had an account and logged in (or if user created an account first then went back to the registration form and clicked on the 'login here' link). In both cases, user gets automatically subscribed without await for approval from administrator.
> [CoreBundle] Fix ws user registration validation

- main/core/Listener/AuthenticationSuccessListener.php
Fixes login.log writing error. Depending on installation domain, the application would sometime not be able to write in the login.log properly:
> [CoreBundle]Fixes login.log writing error

- main/core/Resources/modules/validation/index.js
> [CoreBundle] Fixing resource property accesses validation.

- main/core/API/Serializer/User/UserSerializer.php
> [CoreBundle] Fix user creation with facets

- main/core/Entity/Role.php
- main/core/Manager/Exception/AddRoleException.php
- main/core/Manager/RoleManager.php
> [CoreBundle] Fixing workspace user add.

- main/core/Resources/views/Workspace/layout.html.twig
> [CoreBundle] fixes iframe resize whith images

- plugin/announcement/Resources/modules/resources/announcement/components/resource.jsx
> [AnnouncementBundle] fixes announcement edition

- plugin/blog/Controller/BlogController.php
- plugin/lesson/Controller/LessonController.php
- plugin/wiki/Controller/WikiController.php
> [Wiki, Lesson, Blog] Fix pdf export extension

- main/core/Entity/Role.php
> [CoreBundle] fixes #3416

- composer.json
> Licence GPL-3.0 without +

- composer.json
> Fix packagist licence handle

- plugin/exo/Entity/Exercise.php
- plugin/exo/Migrations/pdo_mysql/Version20180122061353.php
- plugin/exo/Resources/modules/items/components/feedback-btn.jsx
- plugin/exo/Resources/modules/quiz/editor/components/quiz-editor.jsx
- plugin/exo/Resources/modules/quiz/player/components/attempt-end.jsx
- plugin/exo/Resources/modules/quiz/player/selectors.js
- plugin/exo/Resources/translations/ujm_exo.en.json
- plugin/exo/Resources/translations/ujm_exo.fr.json
- plugin/exo/Serializer/ExerciseSerializer.php
> [ExoBundle] adds option to show/hide end navigation (migrations)

- main/core/Controller/APINew/User/UserController.php
- main/core/Resources/modules/administration/user/user/actions.js
> [CoreBundle] Fixing personal workspace create/delete.

- plugin/exo/Resources/modules/items/cloze/editor.js
Je n'ai pas pu reproduire #3318 mais ce truc bug de toute façon.
> [ExoBundle] Cloze error on creation.

- main/core/Manager/RoleManager.php
- main/core/Repository/ResourceNodeRepository.php
> [CoreBundle] Role restoration improved.

- main/core/Library/Home/GraphService.php
> [CoreBundle] Fix youtube video opengraph

- main/core/API/Serializer/Facet/FieldFacetSerializer.php
- plugin/claco-form/Controller/ClacoFormController.php
- plugin/claco-form/Resources/views/ClacoForm/clacoFormOpen.html.twig
> [ClacoForm] Fixes serialization of fields

- composer.json
> fixes twig version

- plugin/external-user-group-synchronization/Manager/ExternalSynchronizationManager.php
- plugin/external-user-group-synchronization/Manager/ExternalSynchronizationUserManager.php
> [External-User-Sync] Take into account user reference change

- main/core/Resources/modules/administration/workspace/workspace/components/workspace-tab.jsx
> [CoreBundle] fixes workspaces management access

- main/core/Resources/modules/administration/workspace/workspace/components/workspace-list.jsx
> [CoreBundle] Workspace redirect

- main/core/API/Crud/User/OrganizationCrud.php
| Fixed tickets | partial #3506
> [CoreBundle] Creating an orga will add default manager.

- main/core/DataFixtures/Required/Data/CreatePublicFilesData.php
- main/core/Library/Installation/AdditionalInstaller.php
- main/core/Library/Installation/Updater/Updater110000.php
- plugin/portfolio/Resources/modules/statistics/statisticsApp.js
> [CoreBundle] Solving symlink user pictures issues (+ fix portfolio)

- main/core/Resources/modules/administration/workspace/workspace/components/workspaces.jsx
> [CoreBundle] Workspace edit form redirection

- main/core/Entity/Facet/FieldFacetChoice.php
> [CoreBundle] Fixing FieldFacetChoice

- plugin/exo/Entity/Exercise.php
- plugin/exo/Migrations/pdo_mysql/Version20180212094439.php
- plugin/exo/Resources/modules/quiz/defaults.js
- plugin/exo/Resources/modules/quiz/editor/components/quiz-editor.jsx
- plugin/exo/Resources/modules/quiz/player/components/player.jsx
- plugin/exo/Resources/modules/quiz/player/selectors.js
- plugin/exo/Resources/translations/ujm_exo.en.json
- plugin/exo/Resources/translations/ujm_exo.fr.json
- plugin/exo/Serializer/ExerciseSerializer.php
> [ExoBundle] adds option to disable end quiz confirm

- main/core/Controller/APINew/Resource/TextController.php
>  [CoreBundle] initializes resource text api

- main/core/Resources/views/Layout/javascripts.html.twig
> [CoreBundle] fixes tooltips

- webpack/packages.js
> [CoreBundle] Webpack meta handling

- main/core/Resources/modules/resource/components/page-actions.jsx
> [CoreBundle] Fixing resource action bar.

- plugin/dropzone/Command/ConvertDropzoneCommand.php
> Fixes dropzone cmd

- plugin/exo/Listener/Resource/ExerciseListener.php
- plugin/exo/Resources/views/Exercise/open.html.twig
- plugin/exo/Resources/views/Scorm/export.html.twig
> [Javascript] Rename jsPlumb

- plugin/drop-zone/Controller/API/DropController.php
- plugin/drop-zone/Manager/DropzoneManager.php
- plugin/drop-zone/Resources/modules/resources/dropzone/correction/actions.js
- plugin/drop-zone/Resources/modules/resources/dropzone/correction/components/drops.jsx
> [Dropzone] Allows to download drops

- main/core/Library/Transfert/RichTextFormatter.php
- main/core/Manager/TransferManager.php
> [CoreBundle] Fixes rich text resource export for single resource.

- main/core/Library/Installation/Updater/Updater110200.php
So it doesn't crash if a user has no organization.
> [CoreBundle] Fixing main organization updater.

- main/core/Library/Installation/Updater/Updater110200.php
> [CoreBundle] Fixing updater 110200

- main/dev/Command/TranslationIntegrityCommand.php
> Fixing the translation debug tool

- plugin/cursus/Controller/CursusRegistrationController.php
- plugin/cursus/Listener/CursusRegistrationListener.php
- plugin/cursus/Resources/views/CursusRegistration/userSessionsRegistrationManagement.html.twig
> Fixes route parameter for sessions management function

- main/core/API/Crud/File/PublicFile.php
- main/core/Library/Transfert/RichTextFormatter.php
- main/core/Manager/TransferManager.php
- plugin/blog/Controller/API/ApiController.php
- plugin/blog/Manager/PostManager.php
- plugin/blog/Repository/PostRepository.php
> [CoreBundle] Fixes pick 10.x

- main/core/Resources/modules/resource/components/resource-actions.jsx
> [ImagePlayer] Fix image player 10.x

- main/core/API/Transfer/Adapter/CsvAdapter.php
> [CoreBundle] Extend csv mimetypes

- main/core/Validator/Constraints/DomainNameValidator.php
> [CoreBundle] domain name validator redirection fix

- main/core/Resources/views/Tool/workspace/parameters/workspaceEdit.html.twig
> [CoreBundle] Fixing url

- main/core/Resources/modules/user/current.js
> [CoreBundle] Exposes current user in JS as JSON object

- main/core/Resources/modules/data/list/components/view/data-grid.jsx
> Fixes sort for data grid

- main/core/API/Serializer/PlatformSerializer.php
- main/core/Resources/modules/tinymce/tinymce.js
- main/core/Resources/views/Layout/javascripts.html.twig
> [CoreBundle] fixes TinyMCE locale

- main/core/Resources/views/variables.html.twig
> [CoreBundle] fixes TinyMCE (again)

- main/app/API/Crud.php
> [CoreBundle] Fixes WS copy

- main/core/API/Crud.php
- main/core/API/Serializer/User/UserSerializer.php
> [CoreBundle] Fixes User creation with facets & WS copy

- main/core/Command/UpdateRichTextCommand.php
I need to test it but it looks ok.
> [CoreBundle] Update rich text command (more entities supported).

- main/core/API/Serializer/User/UserSerializer.php
> [CoreBundle] Renaming getMail that was left.

- main/core/Entity/Organization/Organization.php
- Fixes addUser method for organization
> [CoreBundle] Fix addUser method for organization.

- main/core/API/Finder/User/OrganizationFinder.php
> [CoreBundle] OrganizationFinder typo

- main/core/Resources/modules/layout/form/components/field/file.jsx
> [DropZoneBundle] Fixes files upload

- doc/react/exemples.md
- main/core/API/Serializer/User/GroupSerializer.php
- main/core/API/Serializer/User/RoleSerializer.php
- main/core/API/Serializer/User/UserSerializer.php
- main/core/Resources/modules/workspace/user/components/tool.jsx
- main/core/Resources/modules/workspace/user/group/components/group-list.jsx
- main/core/Resources/modules/workspace/user/role/components/role-list.jsx
- main/core/Resources/modules/workspace/user/user/components/user-list.jsx
> [CoreBundle] Workspace user management tool fixes

- main/app/API/Options.php
- main/core/API/Finder/User/UserFinder.php
- main/core/API/Serializer/WorkspaceSerializer.php
- main/core/Controller/WorkspaceController.php
- main/core/Resources/modules/workspace/user/user/components/user-list.jsx
- main/core/Resources/modules/workspace/user/user/components/users.jsx
- main/core/Resources/views/Workspace/usersManagement.html.twig
> [CoreBundle] Workspace user list

- main/core/API/Finder/User/GroupFinder.php
- main/core/API/Finder/User/UserFinder.php
- main/core/Command/DatabaseIntegrity/RoleIntegrityCheckerCommand.php
- main/core/Manager/RoleManager.php
- main/core/Repository/RoleRepository.php
- main/core/Resources/modules/workspace/user/restrictions.js
> [CoreBundle] Role restoration for workspace.

- main/core/Controller/Tool/WorkspaceParametersController.php
- main/core/Controller/User/RegistrationController.php
- main/core/Resources/views/Tool/workspace/parameters/generate_url_subscription_anonymous.html.twig
- main/core/Resources/views/User/registration.html.twig
> [CoreBundle] Fixing registration default page.

- main/core/API/Serializer/User/RoleSerializer.php
> [CoreBundle] Fixing workspace role edit.

- main/core/Entity/Facet/FieldFacet.php
- plugin/claco-form/Controller/ClacoFormController.php
- plugin/claco-form/Resources/modules/resources/claco-form/editor/field/actions.js
- plugin/claco-form/Resources/modules/resources/claco-form/player/entry/components/entries.jsx
- plugin/claco-form/Resources/modules/resources/claco-form/player/entry/components/entry-create-form.jsx
- plugin/claco-form/Resources/modules/resources/claco-form/player/entry/components/entry-edit-form.jsx
- plugin/claco-form/Resources/modules/resources/claco-form/player/entry/components/entry-view.jsx
> [ClacoForm] Bugs fixes

- main/core/API/Serializer/User/RoleSerializer.php
> [CoreBundle] Fixing RoleSerializer

- plugin/claco-form/API/Finder/EntryFinder.php
- plugin/claco-form/Controller/ClacoFormController.php
> [ClacoForm] Fixes filters for custom field

- main/core/API/Finder/User/UserFinder.php
- main/core/Library/Mailing/Mailer.php
> [CoreBundle] Fix user search by mail and mailer (v10)

- main/core/Resources/modules/layout/form/components/field/select.jsx
- main/core/Resources/modules/layout/form/components/form-field.jsx
- plugin/claco-form/Resources/modules/resources/claco-form/editor/field/components/field-form-modal.jsx
> [ClacoForm] Fixes select input

- main/core/Listener/Resource/FileListener.php
- plugin/text-player/Listener/TextPlayerListener.php
> [CoreBundle] Display html files instead of download v10

- plugin/text-player/Listener/TextPlayerListener.php
- plugin/text-player/Resources/modules/resources/text-file/components/resource.jsx
- plugin/text-player/Resources/modules/resources/text-file/index.js
- plugin/text-player/Resources/modules/resources/text-file/reducer.js
- plugin/text-player/Resources/views/text.html.twig
- plugin/text-player/assets.json
Passage en React + Ouverture des fichiers .html
> [TextPlayerBundle] TextPlayer bundle refactoring

- main/core/Resources/less/main.less
> [CoreBundle] fixes FontAwesome path when using url rewriting

- plugin/blog/Controller/BlogController.php
- plugin/blog/Resources/views/layout.angular.twig
- plugin/lesson/Controller/LessonController.php
- plugin/lesson/Resources/views/Lesson/viewChapter.html.ng.twig
- plugin/wiki/Controller/WikiController.php
- plugin/wiki/Resources/views/Wiki/view.html.twig
> [WikiBundle, BlogBundle, LessonBundle] Fix PDF export access on Wiki, Blog, Lesson (v10)

- plugin/video-player/Resources/views/player.html.twig
> [VideoPlayer] Reverts deletion of template player.html.twig

- plugin/path/Resources/modules/resources/path/player/components/step.jsx
> [PathBundle] fixes step description display

- main/core/Resources/modules/data/list/components/data-list.jsx
> [CoreBundle] fixes data list refresh

- main/core/Manager/WidgetManager.php
Otherwise workspace creation is broken.
> [CoreBundle] Restoring used WidgetManager method.

- main/core/Resources/modules/layout/form/components/form-field.jsx
> Fixes html field in ClacoForm

- main/core/Resources/less/layout/list/data-grids.less
> [CoreBundle] implements responsive list grids

- plugin/path/Resources/modules/resources/path/player/components/step.jsx
> [PathBundle] fixes step content display

- plugin/planned-notification/Listener/PlannedNotificationListener.php
> [PlannedNotificationBundle] Fixes bug with platform roles

- main/core/Resources/less/data/card.less
> [CoreBundle] fixes responsive in detailed lists

- main/core/Resources/config/suggested/framework_dev.yml
- main/core/Resources/config/suggested/framework_prod.yml
| Bug fix?      | Security breach
> [CoreBundle] Secure against XSS attacks (v10)

- main/core/Resources/modules/administration/appearance/theme/components/themes.jsx
- main/core/Resources/modules/workspace/parameters/parameters/display.jsx
> [CoreBundle] Adding missing cards

- main/core/Manager/ResourceManager.php
Don't fetch users if notification is disabled
> [CoreBundle] Impove perf on resource publish/unpublish (v10)

- main/core/Resources/modules/administration/scheduled-task/components/scheduled-task.jsx
- main/core/Resources/modules/administration/scheduled-task/components/scheduled-tasks.jsx
- main/core/Resources/modules/administration/user/group/components/group.jsx
- main/core/Resources/modules/administration/user/group/components/groups.jsx
- main/core/Resources/modules/administration/user/location/components/location.jsx
- main/core/Resources/modules/administration/user/location/components/locations.jsx
- main/core/Resources/modules/administration/user/organization/components/organization.jsx
- main/core/Resources/modules/administration/user/organization/components/organizations.jsx
- main/core/Resources/modules/administration/user/role/components/role.jsx
- main/core/Resources/modules/administration/user/role/components/roles.jsx
- main/core/Resources/modules/administration/user/user/components/user.jsx
- main/core/Resources/modules/administration/workspace/workspace/components/workspace.jsx
- main/core/Resources/modules/data/list/actions.js
- main/core/Resources/modules/data/list/components/data-tree.jsx
- main/core/Resources/modules/user/contact/components/contacts.jsx
- main/core/Resources/modules/workspace/user/role/components/role.jsx
- main/core/Resources/modules/workspace/user/role/components/roles.jsx
- plugin/reservation/Resources/modules/administration/resource/components/resource-form.jsx
> fixes DataLists delete link

- plugin/exo/Resources/modules/quiz/player/actions.js
> [ExoBundle] avoids alerts flood in player

- main/core/Entity/Resource/MaskDecoder.php
- main/core/Entity/Resource/ResourceType.php
- plugin/exo/Resources/modules/docimology/components/docimology.jsx
- plugin/exo/Resources/modules/docimology/index.js
- plugin/exo/Resources/modules/docimology/selectors.js
- plugin/exo/Resources/modules/quiz/papers/components/papers.jsx
- plugin/exo/Resources/modules/quiz/statistics/components/statistics.jsx
- plugin/exo/Resources/modules/resources/quiz/components/resource.jsx
- plugin/exo/Resources/views/Exercise/docimology.html.twig
> [ExoBundle] fixes multiple routing bugs

- main/app/Resources/modules/components/embedded-app.jsx
- main/core/Resources/modules/widget/types/list/components/widget.jsx
- main/core/Resources/modules/widget/types/resource-list/index.js
- plugin/path/Resources/modules/resources/path/components/resource.jsx
>  [CoreBundle] fixes primary action in resources widget

- plugin/path/Resources/modules/resources/path/components/resource.jsx
Otherwise overview is always shown and editor accessible to non admins.
> [PathBundle] fixes routing

- main/app/Resources/modules/button/components/callback.jsx
- main/app/Resources/modules/button/components/link.jsx
- main/app/Resources/modules/button/components/url.jsx
- main/core/Resources/less/layout/components/dropdowns.less
- main/core/Resources/less/layout/components/tables.less
- main/core/Resources/modules/data/list/components/actions.jsx
- main/core/Resources/modules/data/list/components/data-list.jsx
- main/core/Resources/modules/data/list/components/header.jsx
- Fixes some styles
- Fixes default displayed columns.
> [CoreBundle] fixes DataList issues

- main/app/Resources/modules/action/components/dropdown-button.jsx
> [CoreBundle] fixes action groups in dropdowns

- main/core/Resources/modules/administration/scheduled-task/reducer.js
- main/core/Resources/modules/administration/user/group/reducer.js
- main/core/Resources/modules/administration/user/location/reducer.js
- main/core/Resources/modules/administration/user/organization/reducer.js
- main/core/Resources/modules/administration/user/role/reducer.js
- main/core/Resources/modules/administration/user/user/reducer.js
- main/core/Resources/modules/administration/workspace/workspace/reducer.js
- main/core/Resources/modules/data/list/components/data-list.jsx
- main/core/Resources/modules/data/list/connect.js
- main/core/Resources/modules/data/list/containers/data-list.jsx
- main/core/Resources/modules/data/list/containers/data-tree.jsx
- main/core/Resources/modules/user/registration/reducer.js
- main/core/Resources/modules/workspace/user/group/reducer.js
- main/core/Resources/modules/workspace/user/role/reducer.js
- main/core/Resources/modules/workspace/user/user/reducer.js
fixe https://github.com/claroline/Distribution/issues/3849
> [CoreBundle] fixes DataList ajax reload

- main/core/API/Finder/User/RoleFinder.php
> [CoreBundle] Admin bypass add role security.

- main/core/Resources/modules/workspace/user/user/components/user-tab.jsx
> [CoreBundle] Renaming action into callback.

- main/core/Resources/modules/layout/calendar/components/calendar.jsx
- main/core/Resources/modules/scaffolding/date/index.js
> [CoreBundle] Fix timezone difference v10

- main/core/Resources/modules/layout/calendar/components/calendar.jsx
- main/core/Resources/modules/scaffolding/date/index.js
> [CoreBundle] Fixes timezone difference issue v11

- plugin/path/Installation/AdditionalInstaller.php
> [PathBundle] Fix migrations

- plugin/message/Controller/API/MessageController.php
- plugin/message/Controller/MessageController.php
> [MessageBundle] Restoring removed controller actions.

- main/core/Resources/public/js/activity/edit.js
- main/core/Resources/public/js/home/height.js
- main/core/Resources/public/js/home/readmore.js
- main/core/Resources/public/js/sidebar.js
> [Jquery] .load() (#3964)

- plugin/exo/Library/Options/Transfer.php
- plugin/exo/Manager/ExerciseManager.php
- plugin/exo/Serializer/ExerciseSerializer.php
- plugin/exo/Serializer/Item/HintSerializer.php
- plugin/exo/Serializer/Item/ItemObjectSerializer.php
- plugin/exo/Serializer/Item/ItemSerializer.php
- plugin/exo/Serializer/StepSerializer.php
- plugin/exo/Transfer/ExerciseImporter.php
> [ExoBundle] Fixes tag import/copy on quizz import/copy v11

- plugin/path/Resources/views/Widget/list.html.twig
- plugin/path/Resources/views/Widget/slideshow.html.twig
> [PathBundle] fixes list widget
