- main/core/Resources/modules/administration/scheduled-task/components/scheduled-task.jsx
- main/core/Resources/modules/administration/transfer/components/import/tab.jsx
- main/core/Resources/modules/administration/user/location/components/location.jsx
- main/core/Resources/modules/administration/user/organization/components/organization.jsx
- main/core/Resources/modules/administration/user/parameters/components/parameters-tab.jsx
- main/core/Resources/modules/administration/user/role/components/role.jsx
- main/core/Resources/modules/resource/components/modal/edit-properties.jsx
- main/core/Resources/modules/workspace/user/parameters/components/parameters-tab.jsx
- plugin/drop-zone/Resources/modules/resources/dropzone/correction/components/correction-form.jsx
- plugin/drop-zone/Resources/modules/resources/dropzone/correction/components/drops.jsx
- plugin/drop-zone/Resources/modules/resources/dropzone/editor/components/editor.jsx
- plugin/drop-zone/Resources/modules/resources/dropzone/player/components/modal/add-document.jsx
- plugin/path/Resources/modules/resources/path/editor/components/parameters-form.jsx
- plugin/planned-notification/Resources/modules/tools/planned-notification/notification/components/notification.jsx
- plugin/reservation/Resources/modules/administration/resource/components/resource-form.jsx
- Sets condensed display for all "choice" fields in form
- Fixes primary button in drops list in dropzone
> Sets all choice form fields to condensed display

- VERSION.txt
- changelogs/11.x-11.3.x.md
- plugin/claco-form/Controller/ClacoFormController.php
- plugin/claco-form/Entity/FieldChoiceCategory.php
- plugin/claco-form/Entity/FieldValue.php
- plugin/claco-form/Finder/EntryFinder.php
- plugin/claco-form/Manager/ClacoFormManager.php
- plugin/claco-form/Migrations/pdo_mysql/Version20180502092627.php
- plugin/claco-form/Repository/FieldValueRepository.php
- plugin/claco-form/Resources/modules/resources/claco-form/components/resource.jsx
- plugin/claco-form/Resources/modules/resources/claco-form/editor/components/category-fields-values.jsx
- plugin/claco-form/Resources/modules/resources/claco-form/editor/components/editor.jsx
- plugin/claco-form/Resources/modules/resources/claco-form/editor/components/modals/category-form-modal.jsx
- plugin/claco-form/Resources/modules/resources/claco-form/player/entry/actions.js
- plugin/claco-form/Resources/modules/resources/claco-form/player/entry/components/entries.jsx
- plugin/claco-form/Resources/modules/resources/claco-form/player/entry/reducer.js
- plugin/claco-form/Resources/modules/resources/claco-form/prop-types.js
- plugin/claco-form/Resources/modules/resources/claco-form/selectors.js
- plugin/claco-form/Resources/modules/resources/claco-form/utils.js
- plugin/claco-form/Resources/translations/clacoform.en.json
- plugin/claco-form/Resources/translations/clacoform.fr.json
- plugin/claco-form/Serializer/CategorySerializer.php
- plugin/claco-form/Serializer/EntrySerializer.php
- plugin/claco-form/Serializer/FieldChoiceCategorySerializer.php
- plugin/claco-form/Serializer/FieldSerializer.php
> Merge 11.x

- plugin/claco-form/Resources/modules/resources/claco-form/components/resource.jsx
- plugin/claco-form/Resources/modules/resources/claco-form/editor/components/editor.jsx
> [ClacoForm] Fixes loading of used countries when list page is set to default

- main/core/API/Transfer/Action/Workspace/AddUser.php
> Fixes unsupported function name

- main/core/Resources/modules/administration/user/parameters/components/parameters-tab.jsx
> Fixes config of profile roles in users administration tool

- main/core/Manager/Resource/ResourceNodeManager.php
- main/core/Resources/modules/api/actions.js
> Fixes removal of a resource poster

- plugin/claco-form/Security/Voter/EntryVoter.php
> [ClacoForm] Adds Voter for Entry

- .github/PULL_REQUEST_TEMPLATE.md
- .travis.yml
- composer.json
- main/core/API/Serializer/PlatformSerializer.php
- main/core/ClarolineCoreBundle.php
- main/core/Controller/LayoutController.php
- main/core/Controller/WorkspaceController.php
- main/core/Entity/Role.php
- main/core/Entity/Tool/OrderedTool.php
- main/core/Entity/User.php
- main/core/Manager/ResourceManager.php
- main/core/Manager/RoleManager.php
- main/core/Manager/ToolManager.php
- main/core/Repository/ResourceQueryBuilder.php
- main/core/Resources/config/suggested/zenstruck_form.yml
- main/core/Resources/config/suggested/zenstruck_form_routing.yml
- main/core/Resources/modules/intl/constants.js
- main/core/Resources/modules/layout/form/prop-types.js
- main/core/Resources/views/workspace/layout.html.twig
- main/core/Resources/views/workspace/render_tool_list.html.twig
- main/core/Tests/Unit/Manager/RoleManagerTest.php
- main/recorder/Detector/Detector.php
- plugin/notification/Listener/ConfigureMenuListener.php
- plugin/video-player/Resources/modules/resources/video/editor/components/modal/subtitles.jsx
> fixes some symfony 3 bugs

- main/core/Controller/Administration/ParametersController.php
- main/core/Resources/views/administration/layout.html.twig
- main/core/Resources/views/administration/parameters/send_data_confirmation_form.html.twig
- plugin/notification/Listener/ConfigureMenuListener.php
> Fixes template annotation for sf3

- main/core/Controller/ResourceController.php
- main/core/Resources/views/resource/unlock_code_form_with_layout.html.twig
- main/core/Resources/views/text/index.html.twig
- plugin/announcement/Resources/views/announcement/open.html.twig
- plugin/bibliography/Resources/views/book_reference/open.html.twig
- plugin/big-blue-button/Resources/views/bbb/bbb_open.html.twig
- plugin/claco-form/Resources/views/claco_form/claco_form_open.html.twig
- plugin/drop-zone/Resources/views/dropzone/open.html.twig
- plugin/exo/Listener/Resource/ExerciseListener.php
- plugin/exo/Resources/views/exercise/docimology.html.twig
- plugin/exo/Resources/views/exercise/open.html.twig
- plugin/image-player/Resources/views/image/open.html.twig
- plugin/path/Resources/views/path/open.html.twig
- plugin/text-player/Resources/views/text.html.twig
- plugin/video-player/Resources/views/video.html.twig
> Fixes resource layout

- main/core/Resources/modules/data/form/components/field.jsx
- plugin/claco-form/Resources/modules/resources/claco-form/player/entry/components/entry-form.jsx
> Fixes HTML field when using FormField with a name containing a dot

- plugin/claco-form/Manager/ClacoFormManager.php
> Fixes pdf generation of entry

- main/core/Resources/views/Modal/modal.html.twigjs
- main/core/Resources/views/Modal/validationFooter.html.twigjs
> Fixes transparent button in confirmation modal

- plugin/path/Resources/views/Widget/list.html.twig
- plugin/path/Resources/views/Widget/slideshow.html.twig
> Fixes links in path widget

- main/core/Resources/modules/administration/workspace/workspace/reducer.js
> Refreshes workspaces list after editing one

- plugin/team/Form/MultipleTeamsType.php
- plugin/team/Form/TeamEditType.php
- plugin/team/Form/TeamParamsType.php
- plugin/team/Form/TeamType.php
- plugin/team/Listener/TeamListener.php
- plugin/team/Manager/TeamManager.php
> Fixes team creation when resource manager is not found

- main/core/API/Finder/ResourceNodeFinder.php
- main/core/Controller/APINew/ResourceNodeController.php
| Fixed tickets | #4135 
Si tout se passe bien, ne permet de chosir que des resources des EA dont on est gestionnaire (avant c'était des EA auxquels on a accès, si on a accès a bcp de chose... pratiquement tout est dispo).
> [CoreBundle] Stricter resource picker.

- main/core/Controller/APINew/User/UserController.php
> [CoreBundle] Fixing user list by orga manager.

- plugin/claco-form/Controller/ClacoFormController.php
- plugin/claco-form/Manager/ClacoFormManager.php
- plugin/claco-form/Resources/modules/resources/claco-form/player/entry/components/entry.jsx
- plugin/claco-form/Serializer/EntrySerializer.php
| Fixed tickets | #4153
- Removes templating service from manager
- Reactivates notifications to categories managers when an entry is modified
- Fixes file download in entry view
> [ClacoForm] Multiple fixes

- main/core/API/Serializer/User/UserSerializer.php
- main/core/Resources/schemas/user.json
> [CoreBundle] Allows organizations in user csvs.

- plugin/claco-form/Resources/modules/resources/claco-form/components/resource.jsx
- plugin/drop-zone/Resources/modules/resources/dropzone/overview/components/timeline.jsx
- plugin/drop-zone/Serializer/DropzoneSerializer.php
> [DropZoneBundle] Fixes time in resource overview

- plugin/announcement/Resources/modules/resources/announcement/components/announce-form.jsx
> [AnnouncementBundle] Fix prop type.

- plugin/exo/Resources/styles/items/content.less
> Fixes video width in exo

- plugin/announcement/Resources/modules/resources/announcement/components/send-form.jsx
- plugin/announcement/Resources/modules/resources/announcement/components/user-list.jsx
> [CoreBundle] Fixing user filter.

- main/core/Library/Installation/AdditionalInstaller.php
- main/core/Library/Installation/Updater/Updater110200.php
> [CoreBundle] Role creation for updaters

- main/core/Resources/modules/api/actions.js
> [Api] File upload

- main/core/Library/Installation/Updater/Updater120000.php
- plugin/link/ClarolineLinkBundle.php
- plugin/link/Installation/AdditionalInstaller.php
> [LinkBundle] fixes installation

- plugin/link/Listener/Resource/Types/ShortcutListener.php
> [LinkBundle] Fixed link bundle listener namespace

- main/core/Resources/modules/administration/workspace/workspace/components/workspace.jsx
- main/core/Resources/modules/workspace/components/metrics.jsx
Fixes workspace creation.
Also fixes the display of metrics.
> [CoreBundle] fixes workspace creation

- main/core/Resources/modules/administration/workspace/workspace/actions.js
- main/core/Resources/modules/administration/workspace/workspace/components/workspace.jsx
- main/core/Resources/modules/administration/workspace/workspace/components/workspaces.jsx
> [CoreBundle] fixes workspace edition

- main/core/Security/PermissionCheckerTrait.php
- plugin/link/Installation/AdditionalInstaller.php
> Fixes PermissionCheckerTrait missing import and LinkBundle postInstall

- main/core/Resources/modules/layout/calendar/components/calendar.jsx
- main/core/Resources/modules/layout/calendar/components/view/days.jsx
- main/core/Resources/modules/layout/calendar/components/view/layout.jsx
- main/core/Resources/modules/layout/calendar/components/view/months.jsx
- main/core/Resources/modules/layout/calendar/components/view/years.jsx
> [CoreBundle] fixes calendar picker

- .travis.yml
- plugin/exo/Form/Type/ExerciseType.php
- plugin/exo/Tests/Form/Type/ExerciseTypeTest.php
- plugin/exo/Tests/Validator/JsonSchema/Item/ItemValidatorTest.php
> Ignore risky for travis (not locally)

- main/core/API/Finder/User/UserFinder.php
> User finder 11x

- main/app/Resources/modules/action/components/toolbar.jsx
- main/app/Resources/modules/action/utils.js
- main/core/Resources/modules/data/list/components/view/data-table.jsx
> Fixes display of DataTable

- main/core/API/Crud/WorkspaceCrud.php
- main/core/Manager/WorkspaceManager.php
Tools still need to be fixed.
edit: j'ai trouvé d'ou vient le problème.
Il faudra faire un updater qui regénère les ws defaults. Sinon le faire à la main ça fonctionne aussi.
> Fixing WorkspaceOptions at creation.

- main/core/Controller/ResourceOldController.php
- plugin/planned-notification/Controller/API/MessageController.php
- plugin/planned-notification/Entity/PlannedNotification.php
- plugin/planned-notification/Listener/PlannedNotificationListener.php
- plugin/planned-notification/Manager/PlannedNotificationManager.php
- plugin/planned-notification/Resources/modules/tools/planned-notification/constants.js
- plugin/planned-notification/Resources/modules/tools/planned-notification/message/actions.js
- plugin/planned-notification/Resources/modules/tools/planned-notification/message/components/messages.jsx
- plugin/planned-notification/Resources/modules/tools/planned-notification/message/reducer.js
- plugin/planned-notification/Resources/modules/tools/planned-notification/notification/components/notification-tab.jsx
- plugin/planned-notification/Resources/modules/tools/planned-notification/notification/components/notification.jsx
- plugin/planned-notification/Resources/translations/planned_notification.en.json
- plugin/planned-notification/Resources/translations/planned_notification.fr.json
> [PlannedNotificationBundle] Upgrade for planned notifications 

- plugin/planned-notification/Controller/API/MessageController.php
> [PlannedNotificationBundle] Removes useless services injection

- main/app/Resources/modules/api/store/actions.js
> fixes file upload (again)

- main/core/Manager/Resource/ResourceEvaluationManager.php
- main/core/Resources/modules/layout/evaluation/components/score-gauge.jsx
- plugin/exo/Controller/Api/AttemptController.php
- plugin/exo/Library/Item/Definition/ChoiceDefinition.php
- plugin/exo/Manager/Attempt/PaperManager.php
- plugin/exo/Resources/modules/bank/components/questions.jsx
- plugin/exo/Resources/modules/quiz/player/actions.js
> [ExoBundle] Questions bank + fixes

- main/app/Resources/modules/overlay/toolbar/components/toolbar.jsx
- main/core/Resources/config/config.yml
> [CoreBundle] restores resources tool name

- main/core/Resources/modules/resources/text/components/resource.jsx
- plugin/claco-form/Controller/ClacoFormController.php
- plugin/claco-form/Library/Installation/AdditionalInstaller.php
- plugin/claco-form/Library/Installation/Updater/Updater100000.php
- plugin/claco-form/Library/Installation/Updater/Updater100600.php
- plugin/claco-form/Library/Installation/Updater/Updater110300.php
- plugin/claco-form/Listener/ClacoFormListener.php
- plugin/claco-form/Manager/ClacoFormManager.php
- plugin/claco-form/Resources/modules/modals/category/components/category-form.jsx
- plugin/claco-form/Resources/modules/modals/category/index.js
- plugin/claco-form/Resources/modules/modals/keyword/components/keyword-form.jsx
- plugin/claco-form/Resources/modules/modals/keyword/index.js
- plugin/claco-form/Resources/modules/plugin.js
- plugin/claco-form/Resources/modules/resources/claco-form/bootstrap.js
- plugin/claco-form/Resources/modules/resources/claco-form/components/resource.jsx
- plugin/claco-form/Resources/modules/resources/claco-form/editor/components/editor.jsx
- plugin/claco-form/Resources/modules/resources/claco-form/index.js
- plugin/claco-form/Resources/modules/resources/claco-form/reducer.js
- plugin/claco-form/Resources/modules/resources/claco-form/selectors.js
- plugin/claco-form/Resources/views/claco_form/claco_form_open.html.twig
- plugin/claco-form/Resources/views/claco_form_widget/claco_form_widget_open.html.twig
- plugin/claco-form/assets.json
> Resources fixes

- main/core/Manager/IPWhiteListManager.php
> [CoreBundle] Fix IP white list manager

- plugin/announcement/Resources/modules/plugin.js
- plugin/forum/Resources/modules/plugin.js
> forum and announcement

- main/core/Command/UpdateRichTextCommand.php
> Rich Text updater

- main/app/API/Listener/ApiListener.php
- main/core/API/Validator/Resource/ResourceNodeValidator.php
- main/core/Listener/Resource/ResourceListener.php
- main/core/Resources/views/tool/resources.html.twig
> [CoreBundle] Resource API backend

- plugin/blog/Controller/Resource/BlogController.php
- plugin/blog/Repository/PostRepository.php
- plugin/blog/Resources/modules/resources/blog/post/components/post.jsx
- plugin/blog/Resources/views/blog/open.html.twig
- plugin/blog/Resources/views/blog/pdf/view.pdf.twig
fixes: twig imports & paths, archives query, post action bar
> [BlogBundle] Fixes twig imports & paths, archives query, post action bar

- main/app/Resources/modules/action/utils.js
- main/core/Resources/modules/tools/resources/components/tool.jsx
- main/core/Resources/modules/tools/resources/index.js
> [CoreBundle] use directory add as primary action in explorer

- main/app/Resources/modules/components/await.jsx
- main/app/Resources/modules/page/components/header.jsx
- main/core/Resources/modules/resource/utils.js
> [CoreBundle] fixes sub directories top bar in explorer

- plugin/scorm/Command/DeleteOldScormCommand.php
- plugin/scorm/Listener/Scorm12Listener.php
- plugin/scorm/Listener/Scorm2004Listener.php
- plugin/scorm/Listener/ScormListener.php
- plugin/scorm/Manager/ScormManager.php
> [Scorm] Fixes scorm deletion + updates conversion

- main/core/Entity/Resource/ResourceNode.php
- main/core/Library/Configuration/PlatformDefaults.php
- main/core/Library/Testing/RepositoryTestCase.php
- main/core/Listener/Resource/Types/DirectoryListener.php
- main/core/Manager/ResourceManager.php
- main/core/Migrations/pdo_mysql/Version20180709115458.php
- plugin/competency/Tests/Repository/AbilityRepositoryTest.php
- plugin/competency/Util/RepositoryTestCase.php
- plugin/dropzone/Command/ConvertDropzoneCommand.php
- plugin/exo/Library/Testing/Persister.php
- plugin/lesson/Testing/Persister.php
- plugin/result/Testing/Persister.php
- plugin/scorm/Manager/ScormManager.php
- plugin/website/Testing/Persister.php
> Removes "class"  from ResourceNode + adds some default platform options

- plugin/lesson/Controller/API/ChapterController.php
- plugin/lesson/Manager/ChapterManager.php
- plugin/lesson/Resources/modules/resources/lesson/components/chapter-form.jsx
- plugin/lesson/Resources/modules/resources/lesson/components/tree/utils.js
- plugin/lesson/Resources/modules/resources/lesson/player/components/player.jsx
- plugin/lesson/Resources/modules/resources/lesson/store/actions.js
- plugin/lesson/Resources/modules/resources/lesson/store/reducer.js
| BC breaks?    | 
- Move chapter form enhancement
- New position for delete button
- New deletion mechanism
- Copy chapter to new location option
- Last chapter removed resets the lesson
> [LessonBundle] Lesson react refactoring fixes

- main/core/API/Serializer/Resource/ResourceNodeSerializer.php
- main/core/Controller/APINew/Resource/ResourceNodeController.php
- main/core/Controller/APINew/ResourceNodeController.php
- main/core/Resources/modules/resource/explorer/components/explorer.jsx
- main/core/Resources/modules/resource/explorer/store/selectors.js
- main/core/Resources/modules/resource/modals/explorer/components/explorer.jsx
- main/core/Resources/modules/resource/store/selectors.js
- plugin/path/Resources/modules/resources/path/editor/components/editor.jsx
> Updates resources picker in path editor

- main/core/Resources/modules/resource/modals/explorer/components/explorer.jsx
> [CoreBundle] uses standard action as picker select

- plugin/dropzone/Library/Installation/Updater/Updater120000.php
- plugin/scorm/Library/Installation/Updater/Updater120000.php
> Checks existence of resource type before disabling it

- plugin/path/Resources/modules/resources/path/components/resource.jsx
- plugin/path/Resources/modules/resources/path/index.js
> [PathBundle] fixes editor navigation

- main/app/Resources/modules/components/embedded.jsx
> [CoreBundle] fixes embedded apps updates

- main/core/API/Finder/User/UserFinder.php
- main/core/Resources/modules/administration/user/user/components/user-list.jsx
- main/core/Resources/modules/administration/user/user/components/users.jsx
> [CoreBundle] Fixing user list search in administration.

- plugin/wiki/Resources/modules/resources/wiki/components/resource.jsx
- plugin/wiki/Resources/modules/resources/wiki/editor/components/editor.jsx
> [WikiBundle] Update wiki

- main/core/Resources/modules/resource/actions/copy.js
> [CoreBundle] fixes refresh on resources copy

- main/app/Controller/AbstractCrudController.php
- main/core/API/Crud/WorkspaceCrud.php
- main/core/API/Serializer/Workspace/WorkspaceSerializer.php
> Fixes model option in workspace form

- main/core/API/Finder/Workspace/WorkspaceFinder.php
> Lists also workspaces whose user is manager

- main/core/Security/Voter/WorkspaceVoter.php
> [CoreBundle] fixes WorkspaceVoter when using view as

- main/app/Resources/modules/action/constants.js
- main/app/Resources/modules/config/asset.js
- main/core/API/Serializer/Platform/ClientSerializer.php
- main/core/Resources/less/layout/pages.less
- main/core/Resources/less/main.less
- main/core/Resources/less/tinymce/default/Icons.less
- main/core/Resources/less/tinymce/default/plugins/FileUpload.less
- main/core/Resources/less/tinymce/default/plugins/ResourcePicker.less
- main/core/Resources/less/tinymce/index.less
- main/core/Resources/modules/administration/appearance/theme/components/theme.jsx
- main/core/Resources/modules/administration/user/user/components/users.jsx
- main/core/Resources/modules/data/form/components/actions.jsx
- main/core/Resources/modules/tinymce/config.js
- main/core/Resources/modules/user/data/components/user-card.jsx
- main/core/Resources/views/install/layout.html.twig
- main/core/Resources/views/widget/embed/widget.html.twig
- package.json
- plugin/bibliography/Resources/modules/configuration/components/form.jsx
- plugin/exo/Resources/modules/quiz/correction/components/answers.jsx
- plugin/forum/Resources/modules/resources/forum/player/components/subject.jsx
- plugin/forum/Resources/modules/resources/forum/player/components/subjects.jsx
- plugin/scorm/Manager/ExportManager.php
- plugin/scorm/Resources/views/export/layout.html.twig
- plugin/website/Resources/views/website/edit.html.twig
Upgrade to v5.2.0
I still need to double check icons for tinymce. Otherwise it's ok.
> Fontawesome

- plugin/bibliography/Listener/PluginListener.php
> No more getToken()->getUser() in constructor of Bibliography

- main/core/Library/Installation/Updater/Updater120000.php
> Check if container exists

- main/app/Resources/modules/content/list/store/actions.js
- main/app/Resources/modules/content/list/store/connect.js
> fixes list search

- main/core/Resources/modules/resource/components/restrictions.jsx
- main/core/Resources/modules/resource/store/reducer.js
> [CoreBundle] Resource opening restrictions

- main/core/Resources/modules/files/index.js
> fixes file resources

- main/core/Library/Installation/Updater/Updater120000.php
- main/core/Resources/config/config.yml
- plugin/audio-recorder/Installation/AdditionalInstaller.php
- plugin/audio-recorder/Installation/Updater/Updater120000.php
- plugin/audio-recorder/Resources/config/config.yml
- plugin/lti/Library/Installation/AdditionalInstaller.php
- plugin/lti/Library/Installation/Updater/Updater120000.php
- plugin/lti/Resources/config/config.yml
- plugin/lti/UJMLtiBundle.php
- plugin/result/ClarolineResultBundle.php
- plugin/result/Library/Installation/AdditionalInstaller.php
- plugin/result/Library/Installation/Updater/Updater120000.php
- plugin/result/Resources/config/config.yml
- plugin/result/Tests/Controller/ResultControllerTest.php
- plugin/result/Tests/Listener/ResultListenerTest.php
- plugin/result/Tests/Manager/ResultManagerTest.php
- plugin/result/Tests/Repository/MarkRepositoryTest.php
- plugin/result/Tests/Repository/ResultRepositoryTest.php
- plugin/video-recorder/Installation/Updater/Updater120000.php
- plugin/video-recorder/Resources/config/config.yml
Deactivates broken resource types :
- Activity
- Audio Recorder
- LTI
- Result
- Video Recorder
> Deactivates broken resource types

- main/app/Resources/modules/buttons/popover/components/button.jsx
- main/app/Resources/modules/overlay/popover/components/overlay.jsx
- main/core/API/Serializer/Resource/ResourceNodeSerializer.php
- main/core/Manager/Resource/RightsManager.php
- main/core/Resources/less/layout/resource/rights.less
- main/core/Resources/modules/resource/components/rights.jsx
> [CoreBundle] fixes resource creation rights

- main/core/Resources/modules/tools/home/components/tool.jsx
- main/core/Resources/modules/tools/home/editor/components/editor.jsx
- main/core/Resources/modules/tools/home/player/components/player.jsx
- main/core/Resources/modules/tools/home/selectors.js
> tabs admin fixes

- main/app/Resources/modules/content/list/components/actions.jsx
- main/app/Resources/modules/modals/alert/components/alert.jsx
- main/app/Resources/modules/modals/form/components/data.jsx
- main/app/Resources/modules/modals/iframe/components/iframe.jsx
- main/app/Resources/modules/modals/list/components/data.jsx
- main/app/Resources/modules/mount.js
- main/app/Resources/modules/overlay/modal/components/modal.jsx
- main/app/Resources/modules/overlay/modal/components/overlay.jsx
- main/app/Resources/modules/overlay/modal/containers/overlay.jsx
- main/app/Resources/modules/overlay/modal/prop-types.js
- main/app/Resources/modules/overlay/modal/store/actions.js
- main/app/Resources/modules/overlay/modal/store/reducer.js
- main/app/Resources/modules/overlay/modal/store/selectors.js
- main/app/Resources/modules/overlay/modal/withModal.js
- main/app/Resources/modules/store/index.js
- main/core/Resources/less/layout/list/index.less
- main/core/Resources/less/layout/pages.less
- main/core/Resources/less/layout/resource/explorer.less
- main/core/Resources/less/layout/toolbar.less
- main/core/Resources/modules/layout/form/components/field/storage.jsx
- main/core/Resources/modules/resource/modals/explorer/components/modal.jsx
- main/core/Resources/modules/widget/content/components/content.jsx
- main/core/Resources/modules/workspace/components/form.jsx
- main/core/Resources/modules/workspace/modals/parameters/components/modal.jsx
> [CoreBundle] allows multiple modals at once

- main/core/Library/Installation/Updater/Updater120000.php
> Restore widget plugins

- plugin/exo/Resources/modules/bank/components/modal/share.jsx
- plugin/exo/Resources/modules/contents/components/content-modal.jsx
- plugin/exo/Resources/modules/contents/components/content-thumbnail.jsx
- plugin/exo/Resources/modules/items/components/modal/duplicate-modal.jsx
- plugin/exo/Resources/modules/quiz/editor/components/editor.jsx
- plugin/exo/Resources/modules/quiz/editor/components/item-form.jsx
- plugin/exo/Resources/modules/quiz/editor/components/item-form.test.js
- plugin/exo/Resources/modules/quiz/editor/components/item-objects-editor.jsx
- plugin/exo/Resources/modules/quiz/editor/components/modal/add-content-modal.jsx
- plugin/exo/Resources/modules/quiz/editor/components/modal/add-item-modal.jsx
- plugin/exo/Resources/modules/quiz/editor/components/modal/import-items-modal.jsx
- plugin/exo/Resources/modules/quiz/editor/components/modal/move-item-modal.jsx
- plugin/exo/Resources/modules/quiz/editor/components/step-editor.jsx
> [ExoBundle] fixes modals

- plugin/inwicast/Resources/views/Media/videosListTinymce.html.twig
- plugin/support/Resources/views/Support/ticketFromIssueCreateForm.html.twig
> [v10x SupportBundle InwicastBundle] Few minor fixes for 10.x version

- main/core/Manager/Resource/ResourceRestrictionsManager.php
> Resource Restriction fix

- main/core/Resources/less/layout/form/fields/index.less
- main/core/Resources/less/layout/form/fields/resource.less
- main/core/Resources/modules/resource/data/types/resource/components/display.jsx
- main/core/Resources/modules/resource/data/types/resource/components/input.jsx
- main/core/Resources/modules/resource/data/types/resource/index.js
- main/core/Resources/translations/platform.en.json
- main/core/Resources/translations/platform.fr.json
- plugin/path/Resources/modules/resources/path/editor/components/editor.jsx
- plugin/path/Resources/modules/resources/path/editor/components/step-form.jsx
- plugin/path/Resources/modules/resources/path/editor/store/actions.js
- plugin/path/Resources/modules/resources/path/editor/store/reducer.js
Add an embedded option in the resource dataType and use it in the path stepForm
> Resource data type in path

- main/core/Listener/DataSource/ResourceSource.php
> Only displays published resources in resources widget

- main/core/Command/Dev/TestUpdateCommand.php
- main/core/Library/Installation/AdditionalInstaller.php
- main/core/Library/Installation/OperationExecutor.php
- main/core/Library/Installation/Updater/Updater120000.php
- main/installation/Additional/AdditionalInstaller.php
- main/installation/Additional/AdditionalInstallerInterface.php
- main/installation/Manager/InstallationManager.php
Faut encore que j'essaye, je restore l'ancienne db de mfr là.
> Fixed migrations for container/list

- main/core/Library/Installation/AdditionalInstaller.php
- main/core/Library/Installation/Plugin/Installer.php
- main/core/Library/Installation/Updater/Updater120000.php
> [CoreBundle] end version

- main/core/Resources/modules/workspace/data/components/workspace-card.jsx
> Workspace thumbnail now visible

- main/app/Resources/modules/page/components/page.jsx
> [CoreBundle] fixes page headers

- main/core/Resources/modules/resource/utils.js
- main/core/Resources/modules/tools/resources/components/tool.jsx
> [CoreBundle] fixes resource internal links in manager

- plugin/path/Resources/modules/resources/path/player/components/player.jsx
- plugin/path/Resources/translations/path.en.json
- plugin/path/Resources/translations/path.fr.json
> path placeholder

- main/core/Entity/Widget/Type/ResourceWidget.php
- main/core/Migrations/pdo_mysql/Version20180903171211.php
> fixing showHeader for widgets

- main/core/Library/Installation/Updater/Updater120000.php
> my workspaces as grid

- main/core/API/Serializer/Resource/ResourceNodeSerializer.php
- main/core/Manager/Resource/RightsManager.php
- main/core/Resources/less/layout/resource/embedded.less
- main/core/Resources/less/layout/resource/index.less
- main/core/Resources/modules/resources/directory/components/resource.jsx
- main/core/Resources/modules/resources/file/components/resource.jsx
- main/core/Resources/modules/resources/text/components/resource.jsx
- main/core/Tests/Unit/Manager/RightsManagerTest.php
- plugin/announcement/Resources/modules/resources/announcement/components/resource.jsx
- plugin/bibliography/Resources/modules/resources/book-reference/components/resource.jsx
- plugin/big-blue-button/Resources/modules/bbb/components/bbb-resource.jsx
- plugin/blog/Resources/modules/resources/blog/player/components/resource.jsx
- plugin/blog/Resources/styles/resources/blog/index.less
- plugin/claco-form/Resources/modules/resources/claco-form/components/resource.jsx
- plugin/drop-zone/Resources/modules/resources/dropzone/components/resource.jsx
- plugin/exo/Resources/modules/resources/quiz/components/resource.jsx
- plugin/forum/Resources/modules/resources/forum/components/resource.jsx
- plugin/path/Resources/modules/resources/path/components/resource.jsx
- plugin/scorm/Resources/modules/resources/scorm/components/resource.jsx
- plugin/url/Resources/modules/resources/url/components/resource.jsx
- plugin/web-resource/Resources/modules/resources/web-resource/components/resource.jsx
- plugin/wiki/Resources/modules/resources/wiki/components/resource.jsx
> Multiple fixes on resources

- main/core/Library/Installation/Updater/Updater120000.php
> Fixing widgets migrations

- plugin/claco-form/Entity/FieldValue.php
> [ClacoFormBundle] fixes entry save

- package.json
> upgrades FontAwesome and uses floating version

- plugin/forum/Installation/Updater/Updater120000.php
> Forum Updater

- main/core/API/Serializer/Widget/HomeTabSerializer.php
- main/core/Resources/modules/tools/home/editor/components/editor.jsx
> [CoreBundle] delete tab and section fix

- main/core/API/Crud/User/RoleCrud.php
> Create resource permissions on role creation.

- main/app/Resources/modules/data/url/index.js
> Remove url validation

- main/core/Resources/modules/tools/resources/components/tool.jsx
> [CoreBundle] fixes resource manager current directy actions

- main/core/Manager/MailManager.php
> Adds host url in mail validation link

- plugin/badge/Listener/BadgeListener.php
> Deactivates badge listener on every logs

- main/app/Resources/modules/overlay/header/components/header.jsx
- main/app/Resources/modules/overlay/header/components/workspaces.jsx
- main/app/Resources/modules/overlay/header/store/reducer.js
- main/core/Controller/LayoutController.php
> [CoreBundle] Top bar fixes

- main/core/Command/API/ImportCsvCommand.php
- main/core/Library/Installation/Updater/Updater090300.php
- main/core/Listener/ViewAsListener.php
- main/core/Manager/UserManager.php
- main/core/Manager/WorkspaceManager.php
Ça dépannera bien pour le moment.
Un utilisateur spécial claroline-user est utilisé lorsqu'on veut voir en tant que.
Y a rien qui empêche de créer des choses en tant que ce user (ce qui est peut être pas super) mais bon. C'est la solution la plus simple d'avoir l'affichage le plus correct dans les ws.
> [CoreBundle] Fixing ViewAs (Workspace Roles)

- main/core/Resources/views/workspace/layout.html.twig
- plugin/agenda/Resources/modules/data/sources/events.js
- plugin/agenda/Resources/modules/data/sources/tasks.js
- plugin/announcement/Finder/AnnouncementFinder.php
- plugin/announcement/Resources/modules/data/sources/announcements.js
- plugin/announcement/Serializer/AnnouncementSerializer.php
- plugin/forum/Resources/modules/data/sources/forum-messages.js
- plugin/forum/Serializer/MessageSerializer.php
> Adds primary action on several list widgets

- main/core/Manager/UserManager.php
> Default has accepted terms.

- main/core/API/Finder/Workspace/WorkspaceFinder.php
> Shows in "My workspaces" workspaces in which one of user's groups is registered

- main/core/Controller/APINew/Resource/ResourceNodeController.php
- main/core/Manager/UserManager.php
> Show as more fix

- main/core/Controller/HomeController.php
- main/core/Resources/views/home/home.html.twig
> Fixes home page edition

- main/app/Resources/modules/config/theme.js
- main/core/API/Serializer/Platform/ThemeSerializer.php
- main/core/Twig/ThemeExtension.php
> Fixes css assets loading for themes with white space in name

- main/app/API/Options.php
- main/authentication/Manager/ExternalSynchronization/ExternalSynchronizationManager.php
- main/core/API/Crud/User/UserCrud.php
- main/core/API/Finder/ResourceNodeFinder.php
- main/core/API/Serializer/User/RoleSerializer.php
- main/core/Command/User/CreateCommand.php
- main/core/Controller/APINew/User/UserController.php
- main/core/Controller/APINew/Workspace/WorkspaceController.php
- main/core/Controller/OauthController.php
- main/core/Library/Installation/AdditionalInstaller.php
- main/core/Library/Security/ExternalAuthenticator.php
- main/core/Manager/RegistrationManager.php
- main/core/Manager/UserManager.php
- main/core/Manager/WorkspaceManager.php
- main/core/Resources/modules/administration/user/role/components/role.jsx
> Workspace creations fixes

- main/core/API/Finder/Home/HomeTabFinder.php
- main/core/Controller/LocaleController.php
- main/core/Listener/PlatformListener.php
> Tab order & no crash on change locale

- main/core/Resources/modules/scaffolding/date/index.js
> Fixes 2 hours gap in date field of forms at change

- main/app/Resources/modules/overlay/header/components/notifications.jsx
- main/app/Resources/translations/actions.en.json
- main/app/Resources/translations/actions.fr.json
- main/core/Controller/LayoutController.php
- main/core/Resources/less/layout/header.less
fixing brand display and adding messages count
> [CoreBundle] Top bar notifications and brand

- main/core/Controller/ResourceOldController.php
- main/core/Listener/Notification/NotificationListener.php
- main/core/Manager/ResourceManager.php
- main/core/Tests/Unit/Manager/ResourceManagerTest.php
- plugin/badge/Listener/NotificationListener.php
- plugin/blog/Listener/NotificationListener.php
- plugin/collecticiel/Listener/DropzoneListener.php
- plugin/collecticiel/Listener/NotificationListener.php
- plugin/dropzone/Command/ConvertDropzoneCommand.php
- plugin/dropzone/Listener/DropzoneListener.php
- plugin/dropzone/Listener/NotificationListener.php
- plugin/lesson/Listener/NotificationListener.php
- plugin/portfolio/Listener/NotificationListener.php
- plugin/social-media/Listener/NotificationListener.php
- plugin/wiki/Listener/NotificationListener.php
> Fixes Shortcut resource path & notification templates

- main/core/API/Finder/Home/HomeTabFinder.php
- main/core/Library/Installation/Updater/Updater120000.php
- main/core/Resources/config/routing.yml
- main/core/Resources/modules/tools/home/components/tabs.jsx
- plugin/agenda/Finder/EventFinder.php
- plugin/agenda/Resources/modules/data/sources/events.js
> Agenda widget filter

- main/core/Listener/Tool/HomeListener.php
> [CoreBundle] Admin tabs always go first.

- main/app/API/Finder/AbstractFinder.php
- main/core/API/Finder/Home/HomeTabFinder.php
- main/core/Listener/Tool/HomeListener.php
> [CoreBundle] Query builder distinct

- main/core/Controller/APINew/User/UserController.php
- main/core/Resources/modules/administration/user/user/actions.js
- main/core/Resources/modules/administration/user/user/components/users.jsx
> Allows to reset password of a collection of users

- main/core/Controller/Administration/ParametersController.php
- main/core/Form/Administration/MailOptionType.php
- main/core/Form/Administration/MailServerType.php
- main/core/Resources/public/js/administration/email.js
- main/core/Resources/views/administration/parameters/mail_layout_form.html.twig
- main/core/Resources/views/administration/parameters/registration_mail_form.html.twig
> Fixes mail configuration

- main/core/Controller/FileController.php
> Fixes permissions for file streaming

- plugin/announcement/Security/Voter/AnnouncementVoter.php
> [AnnouncementBundle] Adds a voter for announcement

- main/core/Controller/ResourceController.php
- main/core/Controller/ResourceOldController.php
- main/core/Resources/modules/resource/modals/about/components/about.jsx
> Fixes old path for resources opening

- main/core/Security/Voter/Tool/Home/WidgetContainerVoter.php
- main/core/Security/Voter/Tool/Home/WidgetInstanceVoter.php
> Fixes home tabs & widgets deletion

- main/core/Listener/AuthenticationSuccessListener.php
> Fixes terms of services for FR locale

- main/core/Controller/AdministrationController.php
> Fixes access to admin tools

- main/app/API/Options.php
- main/app/API/Transfer/Action/AbstractCreateAction.php
- main/app/API/Transfer/Action/AbstractDeleteAction.php
- main/app/API/Transfer/Action/AbstractUpdateAction.php
- main/app/API/Transfer/Adapter/CsvAdapter.php
- main/app/API/TransferProvider.php
- main/app/Command/ApiImportCommand.php
- main/core/API/Crud/User/UserCrud.php
- main/core/API/Crud/WorkspaceCrud.php
- main/core/API/Serializer/User/UserSerializer.php
- main/core/API/Transfer/Action/User/Create.php
- main/core/API/Transfer/Action/Workspace/Delete.php
- main/core/Resources/schemas/workspace.json
> Csv import

- main/core/Controller/APINew/Workspace/WorkspaceController.php
- main/core/Manager/WorkspaceManager.php
> Uses copied resources for resource widgets at workspace creation/copy

- main/core/Controller/Tool/WorkspaceParametersController.php
> Fixes workspace registration for anonymous

- main/core/Resources/modules/user/components/page-actions.jsx
> Shows edition button in user's own profile

- main/core/Listener/PlatformListener.php
> Fixes locale change

- main/core/Resources/modules/resource/explorer/store/actions.js
> [CoreBundle] Resource explorer directory list limit

- main/core/Resources/modules/scaffolding/text/selection.js
- main/core/Resources/modules/tinymce/plugins/file-upload.js
- main/core/Resources/modules/tinymce/plugins/resource-picker.js
- plugin/exo/Resources/modules/items/selection/utils/selection.js
> Fix tinymce res picker.

- main/core/Manager/Task/ScheduledTaskManager.php
> Fixes creation of scheduled tasks

- plugin/collecticiel/Resources/modules/resources/collecticiel/store/selectors.js
> [CollecticielBundle] Fixes selectors name

- main/app/API/Finder/AbstractFinder.php
- main/core/API/Finder/ResourceNodeFinder.php
- main/core/API/Finder/User/UserFinder.php
- main/core/API/Serializer/Resource/ResourceNodeSerializer.php
> Resources perf load

- main/app/API/Finder/AbstractFinder.php
- main/core/API/Finder/ResourceNodeFinder.php
> Res search fix

- plugin/agenda/Controller/API/EventController.php
- plugin/agenda/Listener/AgendaListener.php
> [AgendaBundle] Allow to show events on 2 separated months.

- main/core/Controller/ResourceController.php
- plugin/agenda/Security/Voter/EventVoter.php
> [CoreBundle] Download docx/xlsx.

- main/core/Event/Resource/ResourceActionEvent.php
- main/core/Event/Resource/ResourceEvent.php
- main/core/Manager/Resource/ResourceActionManager.php
- main/core/Manager/ResourceManager.php
> Corrupted node deletion

- plugin/bibliography/Resources/modules/resources/book-reference/bootstrap.js
- plugin/bibliography/Resources/modules/resources/book-reference/editor/components/editor.jsx
- plugin/bibliography/Resources/modules/resources/book-reference/player/components/player.jsx
- plugin/bibliography/Resources/modules/resources/book-reference/store/reducer.js
- plugin/bibliography/Resources/modules/resources/book-reference/store/selectors.js
- plugin/bibliography/Serializer/BookReferenceSerializer.php
- plugin/bibliography/assets.json
>  Fixes bibliography resource

- plugin/path/Resources/modules/resources/path/editor/components/editor.jsx
> [PathBundle] Redirects to main parameters when deleting current step

- main/core/Listener/DataSource/ResourceSource.php
> [CoreBundle] Fixing ResourceSource.php.

- plugin/exo/Resources/modules/bank/components/questions.jsx
> [ExoBundle] Fixes search on question title/content in questions bank

- main/core/Manager/MailManager.php
- main/core/Manager/UserManager.php
- main/core/Security/PermissionCheckerTrait.php
> [CoreBundle] Fixing mailing urls.

- plugin/announcement/Resources/modules/resources/announcement/components/announce-form.jsx
> [AnnouncementBundle] Refactors saving of announcement

- plugin/cursus/Security/Voter/CourseVoter.php
- plugin/cursus/Security/Voter/CursusVoter.php
- plugin/cursus/Security/Voter/SessionEventCommentVoter.php
- plugin/cursus/Security/Voter/SessionEventVoter.php
- plugin/message/Security/Voter/MessageVoter.php
- plugin/team/Security/Voter/TeamVoter.php
- plugin/team/Security/Voter/WorkspaceTeamParametersVoter.php
> Adds voter for message & fixes several voters namespace

- main/core/Controller/APINew/Workspace/WorkspaceController.php
> [CoreBundle] Fixing bulk workspace registration.

- main/core/Library/Installation/AdditionalInstaller.php
- main/core/Library/Installation/Updater/Updater120015.php
> Resource types clean

- plugin/forum/Security/SubjectVoter.php
> [ForumBundle] Fixes subject voter

- main/core/Manager/MailManager.php
> Fixes link sent for password reset

- main/core/API/Transfer/Action/Workspace/RemoveUser.php
> [CoreBundle] Remove user from workspace by csv.

- plugin/exo/Resources/modules/quiz/papers/components/papers.jsx
- plugin/exo/Resources/modules/quiz/papers/reducer.js
> Fixes papers list

- plugin/exo/Controller/Api/ExerciseController.php
- plugin/exo/Resources/modules/docimology/components/docimology.jsx
- plugin/exo/Resources/modules/resources/quiz/components/resource.jsx
> [ExoBundle] Fixes docimology

- main/app/API/Listener/ApiListener.php
- main/core/API/Serializer/Resource/ResourceNodeSerializer.php
- main/core/Listener/Resource/ResourceListener.php
- main/core/Manager/Resource/OptimizedRightsManager.php
- main/core/Manager/Resource/RightsManager.php
- main/core/Resources/modules/resource/modals/rights/components/modal.jsx
- main/core/Resources/modules/resource/modals/rights/containers/modal.jsx
- main/core/Resources/modules/resource/modals/rights/store/actions.js
- main/core/Resources/modules/resource/modals/rights/store/index.js
- main/core/Resources/modules/resource/modals/rights/store/reducer.js
- main/core/Resources/modules/resource/modals/rights/store/selectors.js
> [CoreBundle] Resource right recursion

- plugin/exo/Controller/Api/CorrectionController.php
- plugin/exo/Resources/modules/quiz/correction/actions.js
- plugin/exo/Resources/modules/quiz/correction/components/questions.jsx
- plugin/exo/Resources/modules/quiz/correction/selectors.js
> [ExoBundle] Fixes manual correction

- main/core/Controller/APINew/Resource/ResourceNodeController.php
- main/core/Resources/modules/resources/directory/actions/add-files.js
- main/core/Resources/modules/resources/directory/actions/add.js
> [CoreBundle] Resource creation rights: frontend.

- plugin/url/Listener/ApiListener.php
> hevinci url fix

- plugin/claco-form/Resources/modules/resources/claco-form/editor/components/category-fields-values.jsx
> [ClacoFormBundle] Fixes category association

- main/core/Resources/modules/workspace/toolbar.js
> [CoreBundle] Fix workspace parameter form reload.

- main/core/Controller/LayoutController.php
- plugin/claco-form/Resources/modules/resources/claco-form/editor/components/category-fields-values.jsx
- plugin/message/Finder/MessageFinder.php
- plugin/message/Listener/MessageListener.php
- plugin/message/Resources/modules/components/sent-messages.jsx
> [MessageBundle] Fixing some message bundle errors

- main/core/Resources/config/routing.yml
> [CoreBundle] Fixing user tracking.

- main/app/API/Listener/ApiListener.php
- plugin/tag/Manager/TagManager.php
> Forum tagged obj

- plugin/announcement/Entity/Announcement.php
- plugin/announcement/Finder/AnnouncementFinder.php
- plugin/announcement/Migrations/pdo_mysql/Version20181001101504.php
- plugin/announcement/Serializer/AnnouncementSerializer.php
- plugin/forum/Serializer/MessageSerializer.php
> [AnnouncementBundle] Announcement sortBy

- main/core/API/Serializer/Resource/Types/FileSerializer.php
- plugin/pdf-player/Resources/modules/files/pdf/components/player.jsx
> [PdfPlayerBundle] Fixing issue with double pdf on single page.

- plugin/agenda/Finder/EventFinder.php
> [AgendaBundle] Includes today in "not done yet"

- plugin/team/Resources/modules/tools/team/components/teams.jsx
- plugin/team/Serializer/TeamSerializer.php
Fixes #4836 (mais pas la suggestion)
> [TeamBundle] Team user count.

- main/app/API/Finder/AbstractFinder.php
- plugin/agenda/Finder/EventFinder.php
Je n'ai pas testé sur une grosse DB. Faudrait le mettre sur mfrb avant de merger vérifier que c'est bon (mais ça devrait l'être).
> [AgendaBundle] Perf issues fix for widget.

- main/core/Listener/DataSource/ResourceSource.php
Fix #4890 
(ça montre tjrs le contenu des sous dossiers, mais plus les ressources cachées & co).
> [CoreBundle] DataSource same filters as resource manager.

- main/app/Resources/modules/overlay/header/components/title.jsx
- main/app/Resources/modules/overlay/header/components/user.jsx
- main/core/Resources/less/layout/header.less
- main/core/Resources/less/layout/list/data-lists.less
- main/core/Resources/less/users/index.less
- main/core/Resources/less/widget/index.less
- main/core/Resources/modules/data/components/data-card.jsx
- main/core/Resources/modules/resources/directory/player/components/directory.jsx
> Elorfin fixes

- plugin/agenda/Resources/modules/components/agenda.jsx
> [AgendaBundle] Fixing error on missing end.

- main/core/API/Finder/ResourceNodeFinder.php
> [CoreBundle] ResourceNode finder order by fix.

- main/app/Resources/modules/content/summary/components/content.jsx
- main/core/Resources/less/layout/components/summaries.less
- plugin/path/Resources/modules/resources/path/components/summary.jsx
- plugin/path/Resources/modules/resources/path/editor/components/editor.jsx
- plugin/path/Resources/modules/resources/path/editor/components/parameters-form.jsx
- plugin/path/Resources/modules/resources/path/editor/components/step-form.jsx
- plugin/path/Resources/modules/resources/path/editor/store/actions.js
- plugin/path/Resources/modules/resources/path/player/components/player.jsx
- plugin/path/Resources/modules/resources/path/store/reducer.js
> [PathBundle] fixes some ui issues

- main/core/Manager/MailManager.php
> Fixes duplicated [http://] in mail url

- plugin/wiki/Serializer/SectionSerializer.php
> [WikiBundle] Don't do weird thing on author serialization.

- main/app/API/SerializerProvider.php
> [AppBundle] Serializer returns null if object is null.

- main/core/Listener/Log/LogListener.php
- main/core/Manager/LogConnectManager.php
> Fixes ignored logs of workspace opening

- main/core/Resources/modules/tools/home/editor/components/editor.jsx
> [CoreBundle] Fixing HomeTab suppression redirect.

- plugin/message/Resources/modules/tools/messaging/components/new-message.jsx
> [MessagingBundle] Don't require the "to" field for everything.

- main/core/Security/Voter/ResourceVoter.php
> Fixes undefined var

- main/core/Resources/views/notification/notification_role_change_right.html.twig
- plugin/drop-zone/Resources/views/notification/notification_item.html.twig
- plugin/notification/README.md
> [NotificationBundle] Fixing wrong template path.

- main/core/API/Serializer/Widget/HomeTabSerializer.php
- main/core/API/Serializer/Widget/WidgetContainerSerializer.php
- main/core/Entity/Tab/HomeTabConfig.php
- main/core/Entity/Widget/WidgetContainerConfig.php
- main/core/Entity/Widget/WidgetInstanceConfig.php
- main/core/Library/Installation/AdditionalInstaller.php
- main/core/Migrations/pdo_mysql/Version20181010072637.php
- main/core/Migrations/pdo_mysql/Version20181010092915.php
- main/core/Resources/less/themes/default/variables.less
- main/core/Resources/less/widget/index.less
- main/core/Resources/modules/layout/components/heading.jsx
- main/core/Resources/modules/layout/form/components/field/color-picker.jsx
- main/core/Resources/modules/tools/home/components/tabs.jsx
- main/core/Resources/modules/tools/home/editor/components/tab.jsx
- main/core/Resources/modules/tools/home/store/selectors.js
- main/core/Resources/modules/widget/editor/components/form.jsx
- main/core/Resources/modules/widget/editor/components/widget.jsx
- main/core/Resources/modules/widget/player/components/widget.jsx
- main/core/Resources/modules/widget/prop-types.js
- main/core/Resources/modules/widget/utils.js
- main/core/Resources/styles/tools/home.less
- main/core/Resources/translations/platform.en.json
- main/core/Resources/translations/platform.fr.json
- main/core/Security/Voter/ResourceVoter.php
> [CoreBundle] enhances widget styles configuration

- plugin/blog/Resources/modules/resources/blog/editor/components/blog-options.jsx
> [BlogBundle] Fixes selectors call in editor

- main/core/Command/UpdateRichTextCommand.php
> [CoreBundle] Fixes RichTextUpdate Command.

- main/core/Library/Installation/Updater/Updater120000.php
> [CoreBundle] Migrations colors.

- main/app/Resources/modules/overlay/modal/components/overlay.jsx
> [AppBunble] fixes chained modals

- plugin/cursus/Controller/APINew/CourseController.php
- plugin/cursus/Controller/APINew/CursusController.php
- plugin/cursus/Controller/APINew/SessionController.php
- plugin/cursus/Controller/APINew/SessionEventController.php
- plugin/cursus/Finder/CourseFinder.php
- plugin/cursus/Finder/CursusFinder.php
- plugin/cursus/Finder/SessionEventFinder.php
- plugin/cursus/Finder/SessionFinder.php
> [CursusBundle] Doesn't filter by organizations for admin

- main/core/API/Finder/Workspace/WorkspaceFinder.php
> Fixes sort on creation date in workspace finder

- main/core/Listener/Tool/HomeListener.php
> [CoreBundle] fixes missing home tabs

- plugin/lesson/Listener/Resource/LessonListener.php
- plugin/lesson/Manager/ChapterManager.php
> Fixes root chapter copy of lesson

- plugin/agenda/Listener/AgendaListener.php
> Fixes agenda

- main/core/Command/RestoreTabsColorCommand.php
> Adds command to restore tabs color

- plugin/message/Resources/modules/tools/messaging/components/messages.jsx
> Fixes routing in messaging

- main/core/Library/Installation/Updater/Updater120000.php
> typo in updater

- plugin/survey/Controller/SurveyController.php
- plugin/survey/Resources/config/config.yml
- plugin/survey/Resources/modules/plugin.js
- plugin/survey/Resources/modules/resources/survey/actions/open.js
- plugin/survey/Resources/views/survey/question_create_form.html.twig
- plugin/survey/Resources/views/survey/question_edit_form.html.twig
- plugin/survey/Resources/views/survey/question_title_create_form.html.twig
- plugin/survey/Resources/views/survey/question_title_edit_form.html.twig
- plugin/survey/Resources/views/survey/survey_parameters_edit_form.html.twig
> Adds action to open a survey

- main/core/Manager/LogConnectManager.php
> Fixes connection logs when impersonating

- main/core/Manager/LogConnectManager.php
> Fixes connection logs for anonymous

- main/core/Library/Installation/Updater/Updater120100.php
> Empties log connection tables in updater to 12.1.0

- plugin/survey/Resources/modules/resources/survey/actions/open.js
> [SurveyBundle] fixes open action

- main/core/Manager/Resource/ResourceRestrictionsManager.php
- main/core/Resources/modules/resource/store/actions.js
- main/core/Resources/modules/resource/store/reducer.js
- main/core/Security/Voter/WorkspaceVoter.php
| Fixed issues | #5024, #4956 (don't fix all reported)
> Fix resources

- main/core/Manager/WorkspaceManager.php
Remplace le hack dégueu pour empécher la duplication des ressources d'une Activité lors de la copie par un hack dégueu pour les Parcours.
> [CoreBundle] temp fix path copy

- main/core/Resources/modules/resource/data/components/resource-card.jsx
- plugin/announcement/Resources/modules/data/components/announcement-card.jsx
- plugin/announcement/Resources/modules/resources/announcement/components/announce-form.jsx
- plugin/announcement/Resources/modules/resources/announcement/components/resource.jsx
- plugin/announcement/Resources/modules/resources/announcement/containers/resource.jsx
> [AnnouncementBundle] adds poster and author in list card

- main/app/API/Listener/ApiListener.php
- plugin/announcement/Serializer/AnnouncementSerializer.php
- plugin/forum/Event/LogPostMessageEvent.php
- plugin/forum/Resources/views/notification/notification_item.html.twig
> Fixes announcement

- main/core/Controller/RedirectController.php
- main/core/Controller/ResourceController.php
> [CoreBundle] fixes #5051

- main/core/API/Serializer/Platform/ClientSerializer.php
- main/core/Resources/modules/administration/logs/connection/store/reducer.js
- main/core/Resources/modules/administration/scheduled-task/reducer.js
- main/core/Resources/modules/administration/user/user/reducer.js
- main/core/Resources/modules/administration/workspace/reducer.js
- main/core/Resources/modules/resource/logs/connection/store/reducer.js
- main/core/Resources/modules/workspace/logs/connection/store/reducer.js
- main/core/Resources/modules/workspace/user/user/reducer.js
- plugin/planned-notification/Resources/modules/tools/planned-notification/message/reducer.js
- plugin/planned-notification/Resources/modules/tools/planned-notification/notification/reducer.js
- plugin/team/Resources/modules/tools/team/store/reducer.js
> Small fix + default list order

- main/app/Resources/modules/content/card/components/data.jsx
- main/app/Resources/modules/content/card/prop-types.js
- main/app/Resources/modules/content/list/components/view/data-grid.jsx
- main/app/Resources/modules/content/list/store/actions.js
- main/app/Resources/modules/content/list/store/connect.js
- main/core/Listener/Resource/ResourceListener.php
- main/core/Resources/modules/resource/explorer/store/actions.js
- main/core/Resources/modules/resource/explorer/store/reducer.js
- main/core/Resources/modules/resource/index.js
- main/core/Resources/modules/resource/store/actions.js
- main/core/Resources/modules/resources/directory/player/store/reducer.js
- main/core/Resources/modules/tool/constants.js
- main/core/Resources/modules/tool/store/actions.js
- main/core/Resources/modules/tool/store/index.js
- main/core/Resources/modules/tool/store/reducer.js
- main/core/Resources/modules/widget/content/components/form.jsx
fixes #5061, #5054.
@LaurentGruber : it also fixes empty resource widgets (it was not only for directories).
> [CoreBundle] multiple fixes on resources

- plugin/agenda/Finder/EventFinder.php
- plugin/announcement/Finder/AnnouncementFinder.php
- plugin/blog/Finder/PostFinder.php
- plugin/forum/Finder/MessageFinder.php
> Updates some mask checks

- main/app/Resources/modules/overlay/header/components/header.jsx
- main/app/Resources/modules/overlay/header/components/main.jsx
- main/app/Resources/modules/overlay/header/containers/header.jsx
- main/app/Resources/modules/overlay/header/store/reducer.js
- main/app/Resources/modules/overlay/header/store/selectors.js
- main/core/Controller/APINew/Resource/Types/TextController.php
- main/core/Controller/LayoutController.php
- main/core/Library/Configuration/PlatformDefaults.php
- main/core/Resources/modules/plugin.js
- main/core/Resources/modules/resource/components/page.jsx
- main/core/Resources/views/layout/top_bar.html.twig
- plugin/path/Resources/modules/resources/path/player/components/step.jsx
- plugin/path/Resources/modules/resources/path/prop-types.js
> makes main header menu configurable

- main/app/Routing/ApiLoader.php
> [AppBundle] Fixing routing loading order.

- main/core/Controller/LayoutController.php
- main/core/Resources/less/data/card.less
- main/core/Resources/views/layout.html.twig
> [CoreBundle] fixes layout overrides

- plugin/survey/Controller/SurveyController.php
> [SurveyBundle] Removes misplaced function

- main/app/Routing/ApiLoader.php
- plugin/team/Controller/API/TeamController.php
- plugin/team/Resources/modules/tools/team/components/teams.jsx
> [TeamBundle] Fixing team list.

- main/core/Controller/RedirectController.php
> [CoreBundle] Fixing show redirect.

- main/core/Library/Normalizer/DateRangeNormalizer.php
> [CoreBundle] DateRangeNormalizer condition

- main/app/API/Utils/ArrayUtils.php
> [CoreBundle] Fixing ArrayUtils condition

- main/core/API/Serializer/ParametersSerializer.php
- main/core/Resources/modules/administration/parameters/appearance/components/main.jsx
> [CoreBundle] Allow to set the logo.

- main/app/Routing/ApiLoader.php
> [AppBundle] ApiLoader ignore.

- main/core/Resources/modules/data/types/workspace/components/display.jsx
- main/core/Resources/modules/data/types/workspace/components/group.jsx
- main/core/Resources/modules/data/types/workspace/components/input.jsx
- main/core/Resources/modules/data/types/workspace/index.js
- main/core/Resources/modules/data/types/workspaces/components/input.jsx
- main/core/Resources/modules/plugin.js
> Adds a picker for a single workspace

- main/app/Resources/modules/content/list/parameters/components/form.jsx
> [CoreBundle] fixes list card config

- main/app/Resources/modules/content/list/containers/source.jsx
- main/app/Resources/modules/data/country/components/filter.jsx
- main/app/Resources/modules/data/country/index.js
- main/core/Resources/modules/layout/form/components/field/country.jsx
> [CoreBundle] fixes list source

- plugin/claco-form/Resources/modules/data/sources/entries.js
> [ClacoFormBundle] fixes choice search

- main/app/Resources/modules/content/list/containers/source.jsx
- main/app/Resources/modules/content/list/parameters/components/form.jsx
- main/app/Resources/modules/content/search/components/full.jsx
- main/app/Resources/modules/data/filter/components/input.jsx
- main/app/Resources/modules/data/filter/index.js
- main/core/Library/Installation/AdditionalInstaller.php
- main/core/Library/Installation/Updater/Updater120118.php
- main/core/Resources/translations/platform.en.json
- main/core/Resources/translations/platform.fr.json
J'ai du réinitialiser les champs suivants : 
- Filtres par défaut
- Filtres disponibles
- Tri par défaut
- Tris disponible
> [CoreBundle] fixes list default filters and sort

- main/core/Command/Import/CreateWorkspaceFromCsvCommand.php
- plugin/claco-form/Command/CreateEntriesFromCsvCommand.php
- plugin/claco-form/Manager/ClacoFormManager.php
> [ClacoForm] Adds a command to import entries from a CSV

- plugin/claco-form/Command/CreateEntriesFromCsvCommand.php
- plugin/claco-form/Manager/ClacoFormManager.php
> [ClacoForm] Updates import command

- main/app/Entity/Parameters/ListParameters.php
- main/core/Entity/Resource/Directory.php
- main/core/Event/CreateResourceEvent.php
- main/core/Listener/Resource/Types/DirectoryListener.php
- main/core/Manager/Resource/ResourceActionManager.php
- main/core/Manager/Resource/ResourceLifecycleManager.php
> [CoreBundle] sets directory defaults

- main/app/Resources/modules/content/form/components/data.jsx
- main/app/Resources/modules/content/form/components/form.jsx
- main/app/Resources/modules/content/list/components/footer.jsx
- main/app/Resources/modules/content/list/containers/data.jsx
- main/app/Resources/modules/content/list/containers/source.jsx
- main/app/Resources/modules/content/list/store/connect.js
- main/app/Resources/modules/content/pagination/components/pagination.jsx
- main/app/Resources/modules/data/choice/index.js
- main/core/Resources/less/progression/index.less
- main/core/Resources/modules/tools/progression/components/list.jsx
> [CoreBundle] fixes list pagination

- plugin/agenda/Serializer/EventSerializer.php
> [AgendaBundle] Fixing Serialization (no more full workspace).

- plugin/agenda/Resources/modules/components/agenda.jsx
- plugin/agenda/Serializer/EventSerializer.php
> [AgendaBundle] Add color in form.

- main/core/Resources/modules/user/message/components/user-message.jsx
> Changes label for messages from undefined user

- main/app/API/Serializer/SerializerTrait.php
- main/core/API/Serializer/Widget/WidgetInstanceSerializer.php
> [CoreBundle] Fixing WidgetInstance serializer.

- main/app/Resources/modules/action/components/toolbar.jsx
- main/app/Resources/modules/action/prop-types.js
- main/app/Resources/modules/content/list/containers/source.jsx
- main/app/Resources/modules/page/components/breadcrumb.jsx
- main/app/Resources/modules/page/components/full.jsx
- main/app/Resources/modules/page/components/header.jsx
- main/app/Resources/modules/page/prop-types.js
- main/core/API/Serializer/Resource/ResourceNodeSerializer.php
- main/core/Resources/less/layout/modal/index.less
- main/core/Resources/less/layout/resource/explorer.less
- main/core/Resources/modules/resource/explorer/components/explorer.jsx
- main/core/Resources/modules/resource/explorer/containers/explorer.jsx
- main/core/Resources/modules/resource/explorer/store/actions.js
- main/core/Resources/modules/resource/explorer/store/reducer.js
- main/core/Resources/modules/resource/explorer/store/selectors.js
- main/core/Resources/modules/resource/modals/explorer/components/modal.jsx
- main/core/Resources/modules/tools/resources/components/tool.jsx
> [CoreBundle] fixes resource explorer

- main/core/Resources/modules/modals/users/components/modal.jsx
> Adds group filter in users picker

- main/core/Controller/APINew/User/UserController.php
- main/core/Security/Voter/UserVoter.php
> [CoreBundle] Secure the api user list.

- main/core/API/Serializer/User/UserSerializer.php
> [CoreBundle] User metadata deserialization.

- main/core/Controller/ResourceController.php
- main/core/Repository/ResourceRightsRepository.php
> [CoreBundle] redirects anonymous on resource show if needed

- plugin/web-resource/Resources/modules/resources/web-resource/player/components/player.jsx
> [WebResourceBundle] Fixing iframe height.

- main/core/API/Finder/Home/HomeTabFinder.php
- main/core/API/Finder/Workspace/WorkspaceFinder.php
- plugin/agenda/Finder/EventFinder.php
- plugin/announcement/Finder/AnnouncementFinder.php
- plugin/blog/Finder/PostFinder.php
- plugin/forum/Finder/MessageFinder.php
- plugin/forum/Finder/SubjectFinder.php
- plugin/forum/Finder/UserFinder.php
> [Platform] Use like in finders instead of eq.

- plugin/tag/Migrations/pdo_mysql/Version20181212090304.php
> [TagBundle] fixes migrations

- plugin/claco-form/Entity/FieldChoiceCategory.php
> [ClacoFormBundle] Fixes FieldChoiceCategory

- main/core/Entity/Resource/ResourceNode.php
- main/core/Library/Installation/Updater/Updater120200.php
> [CoreBundle] Skipping path generation on broken paths.

- main/authentication/ClarolineAuthenticationBundle.php
- main/authentication/Library/LegacyParametersMapping.php
> restore oauth routing

- main/core/Entity/Workspace/Workspace.php
> [CoreBundle] fixes #5306

- main/core/Command/DatabaseIntegrity/DirectoryIntegrityCommand.php
`php app/console claroline:directory:check -w workspaceCode`
> [CoreBundle][ Directory restore cmd.

- main/core/API/Serializer/Workspace/WorkspaceSerializer.php
| Fixed issues | #5346
J'espère qu'il n'y aura pas d'effet de bords (je pense pas).
> [CoreBundle] Workspace default role serialization.

- plugin/path/Entity/Path/Path.php
> [PathBundle] fixes path creation

- plugin/lti/Library/Installation/AdditionalInstaller.php
- plugin/lti/Library/Installation/Updater/Updater120212.php
> [LtiBundle] Changes updater for 12.2.0 to 12.2.12

- main/core/Library/Installation/Updater/Updater120212.php
> Deletes all tables from SupportBundle in an updater

- main/app/API/ToolsOptions.php
- main/core/Library/Installation/Updater/Updater120212.php
> Removes completely SupportBundle from DB

- main/app/Routing/ApiLoader.php
- main/core/Resources/modules/workspace/actions/copy-model.js
- main/core/Resources/modules/workspace/actions/copy.js
> [CoreBundle] Fixing ws copy.

- main/core/Resources/modules/tools/home/editor/components/editor.jsx
- main/core/Resources/modules/tools/home/player/components/player.jsx
- main/core/Resources/modules/tools/home/store/selectors.js
> fixes tab title in homes

- plugin/exo/Resources/modules/items/match/paper.jsx
> [ExoBundle] Fixing match questions.

- main/core/Resources/modules/tools/home/editor/components/editor.jsx
- main/core/Resources/modules/tools/home/editor/store/selectors.js
- main/core/Resources/modules/widget/content/components/form.jsx
- main/core/Resources/modules/widget/content/modals/parameters/components/modal.jsx
> [CoreBundle] fixes #5402

- main/core/Resources/styles/tools/home.less
> [CoreBundle] adds some theme vars for home

- main/core/Manager/RoleManager.php
> [RoleIntegrityChecker] Also set ROLE_USER.

- plugin/announcement/Resources/modules/resources/announcement/components/announce-send.jsx
> [AnnouncementBundle] fixes sending form

- main/core/Controller/APINew/ParametersController.php
- main/core/Manager/LocaleManager.php
- main/core/Manager/MailManager.php
> [CoreBundle] default locale for template + platform details url.

- main/app/Resources/modules/content/form/components/data.jsx
> [CoreBundle] fixes form events

- main/core/Controller/ResourceController.php
> [CoreBundle] Replace /\ by _ in file names download.

- main/core/Listener/DataSource/ResourceSource.php
> [CoreBundle] Resource Data List: Remove ws limitation.

- plugin/agenda/Resources/modules/tools/agenda/containers/tool.jsx
- plugin/agenda/Resources/modules/tools/agenda/modals/event/components/modal.jsx
> [Agenda] A couple translations.

- composer.json
> [CoreBundle] Fixing bundle install order.

- main/app/API/Finder/AbstractFinder.php
- plugin/blog/Finder/PostFinder.php
> [AppBunde] Fixing setDefaults method.

- main/core/Manager/LogConnectManager.php
> Fixes command for connection duration

- main/app/Resources/modules/action/components/toolbar.jsx
- main/app/Resources/modules/action/prop-types.js
- main/app/Resources/modules/page/components/breadcrumb.jsx
- main/core/Resources/modules/tool/components/page.jsx
- main/core/Resources/modules/tools/resources/components/tool.jsx
> [CoreBundle] fixes resources manager breadcrumb

- main/app/Resources/modules/content/summary/components/summary.jsx
- main/core/Command/DatabaseIntegrity/UserIntegrityCheckerCommand.php
- plugin/lesson/Resources/config/config.yml
- plugin/lesson/Resources/modules/resources/lesson/utils.js
> [LessonBundle] GUI doesn't display unusuable buttons anymore.

- main/core/Manager/ResourceManager.php
> Dispatches an event when soft deleting a resource

- main/app/Resources/modules/content/form/store/actions.js
- main/core/Controller/APINew/LoggerController.php
- main/core/Resources/modules/workspace/creation/components/form.jsx
- main/core/Resources/modules/workspace/creation/store/actions.js
| Fixed issues | #4375 partial
> [CoreBundle] Form validation (part1)

- plugin/team/Resources/modules/tools/team/components/team-form.jsx
- plugin/team/Resources/translations/team.en.json
- plugin/team/Resources/translations/team.fr.json
- plugin/team/Serializer/TeamSerializer.php
| Fixed issues | #4829 
4829 part one
> [TeamBundle] Allow to not create the team directory.

- main/core/Event/Resource/SoftDeleteResourceEvent.php
- main/core/Manager/ResourceManager.php
> Creates specific event for resources soft delete

- main/app/Resources/modules/action/utils.js
- plugin/blog/Resources/modules/resources/blog/comment/components/comments.jsx
- plugin/blog/Resources/modules/resources/blog/components/resource.jsx
- plugin/blog/Resources/modules/resources/blog/containers/resource.jsx
- plugin/blog/Resources/modules/resources/blog/index.js
- plugin/blog/Resources/modules/resources/blog/moderation/components/unpublished-posts.jsx
- plugin/blog/Resources/modules/resources/blog/player/components/player.jsx
- plugin/blog/Resources/modules/resources/blog/post/components/card.jsx
- plugin/blog/Resources/modules/resources/blog/post/components/post.jsx
- plugin/blog/Resources/modules/resources/blog/post/components/posts.jsx
- plugin/blog/Resources/modules/resources/blog/store/selectors.js
- plugin/blog/Resources/modules/resources/blog/toolbar/components/archives.jsx
- plugin/blog/Resources/modules/resources/blog/toolbar/components/calendar.jsx
- plugin/blog/Resources/modules/resources/blog/toolbar/components/exporters.jsx
- plugin/blog/Resources/modules/resources/blog/toolbar/components/redactors.jsx
- plugin/blog/Resources/modules/resources/blog/toolbar/components/tags.jsx
- plugin/blog/Resources/modules/resources/blog/utils.js
- plugin/blog/Resources/styles/mixins.less
- plugin/blog/Resources/styles/resources/blog/index.less
- plugin/blog/Resources/styles/resources/blog/pdf.less
- plugin/blog/Resources/styles/resources/blog/post.less
- plugin/blog/Resources/styles/variables.less
> [BlogBundle] fixes links and ui styles

- main/core/API/Crud/User/OrganizationCrud.php
> [CoreBundle] Organization crypto keys crud.

- main/core/Controller/APINew/User/UserController.php
> [CoreBundle] Fixing managed users search criteria.

- plugin/claco-form/Entity/ClacoForm.php
> Fixes ClacoForm serialization

- main/core/Manager/CurlManager.php
> Updates CurlManager

- plugin/rss/Resources/modules/resources/rss-feed/player/components/player.jsx
> [RssFeedBundle] Html properly displayed.

- plugin/team/Serializer/TeamSerializer.php
- plugin/wiki/Listener/BadgeListener.php
- plugin/wiki/Resources/views/log/log_list_item_section.html.twig
- plugin/wiki/Resources/views/notification/notification_contribution_create.html.twig
- plugin/wiki/Resources/views/notification/notification_section_create.html.twig
- plugin/wiki/Resources/views/notification/notification_user_tagged.html.twig
> [WikiBundle] Wiki log urls fix

- composer.json
> Bump doctrine/orm version.

- composer.json
Also require https://github.com/claroline/Claroline/pull/1492
> Php7.3 compatibility

- plugin/forum/Serializer/MessageSerializer.php
- plugin/forum/Serializer/SubjectSerializer.php
Faut encore que je teste en local.
Ça plante pas en tout cas. Je me crée un fichier csv pour importer des users et je confirme plus tard.
> Forum msg fix

- plugin/agenda/Resources/modules/tools/agenda/components/tool.jsx
> [AgendaBundle] Fixes translations in day view

- plugin/scorm/Resources/modules/resources/scorm/player/actions.js
> [ScormBundle] Hides status message for API calls

- plugin/claco-form/Manager/ClacoFormManager.php
> [ClcaoForm] Fixes relative URL in notifications

- main/app/API/Listener/ApiListener.php
- plugin/message/Entity/UserMessage.php
> [MessageBundle] Fixing messaging soft delete.

- main/core/API/Serializer/User/LocationSerializer.php
- main/core/Resources/modules/administration/user/location/components/location.jsx
- main/core/Resources/modules/administration/user/role/components/role.jsx
- main/core/Resources/schemas/location.json
https://github.com/claroline/Distribution/issues/5463 
- locations
- role type
> [CoreBundle] Location validation.

- main/core/Controller/APINew/Workspace/WorkspaceController.php
- main/core/Resources/modules/workspace/actions/view-as.js
- main/core/Resources/modules/workspace/user/role/components/roles.jsx
> [CoreBundle] Workspace role user registration list.

- main/core/Resources/modules/workspace/components/form.jsx
> [CoreBundle] Workspace limit only by admins

- main/core/API/Finder/TransferFinder.php
- main/core/Resources/modules/administration/transfer/history/components/history-list.jsx
- main/core/Resources/modules/administration/transfer/history/components/tab.jsx
- main/core/Resources/modules/administration/transfer/reducer.js
> [CoreBundle] Sort csv imported files.

- plugin/path/Resources/modules/resources/path/player/components/step.jsx
| Fixed issues | fix https://github.com/claroline/Distribution/issues/5584
> [Path] fix inheritedResources doesnt exist

- main/core/API/Serializer/ParametersSerializer.php
- main/core/Manager/IconSetManager.php
- main/core/Repository/ContentTranslationRepository.php
| Fixed issues | fixe https://github.com/claroline/Distribution/issues/5586
> [CoreBundle] IconSet fix.

- main/core/Resources/modules/workspace/user/user/components/user-tab.jsx
> [CoreBundle] Fixing user create url

- plugin/forum/Crud/SubjectCrud.php
- plugin/forum/Entity/Message.php
- plugin/forum/Entity/Subject.php
- plugin/forum/Serializer/SubjectSerializer.php
> [ForumBundle] Set first moderated msg in Crud.

- plugin/scorm/Resources/modules/resources/scorm/player/api.js
> [ScormBundle] Fixes undefined value for LMSGetValue

- main/app/API/Crud.php
- main/app/API/Options.php
- main/app/API/ValidatorInterface.php
- main/app/API/ValidatorProvider.php
- main/core/API/Validator/GroupValidator.php
- main/core/API/Validator/Resource/ResourceNodeValidator.php
- main/core/API/Validator/UserValidator.php
- main/core/API/Validator/WorkspaceValidator.php
- main/core/Controller/APINew/User/UserController.php
- main/core/Resources/modules/user/registration/components/facet.jsx
- plugin/message/Validator/MessageValidator.php
- plugin/reservation/Validator/ResourceTypeValidator.php
- plugin/reservation/Validator/ResourceValidator.php
| Fixed issues | #5591
Faut pas encore merger. La validation est correcte mais ça casse lors de la création avec (mais c'est ptet juste ma platefome que j'ai dézingué).
Edit: c'est bon en fait, juste ma plateforme.
> [CoreBundle] Fixing facet validaiton.

- main/core/API/Serializer/Widget/HomeTabSerializer.php
- main/core/Controller/APINew/HomeController.php
- main/core/Entity/Resource/ResourceRights.php
> fixes lock

- plugin/lesson/Serializer/LessonSerializer.php
> [LessonBundle] Fixes Lesson creation

- plugin/exo/Serializer/ExerciseSerializer.php
> [ExoBundle] Fixes exo creation

- plugin/path/Resources/schemas/path.json
- plugin/path/Serializer/PathSerializer.php
> [PathBundle] Fixes path serializer and schema for resource creation

- main/core/API/Crud/Home/HomeTabCrud.php
- main/core/API/Crud/Home/WidgetContainerCrud.php
- main/core/API/Crud/Home/WidgetInstanceCrud.php
> [CoreBundle] Fixing home tabs delete

- main/core/API/Serializer/Resource/Types/TextSerializer.php
- plugin/blog/Resources/schemas/blog.json
- plugin/blog/Serializer/BlogOptionsSerializer.php
- plugin/blog/Serializer/BlogSerializer.php
> Fixes Text & Blog creation

- plugin/wiki/Repository/SectionRepository.php
- plugin/wiki/Serializer/WikiSerializer.php
> [WikiBundle] Fixes Wiki creation & opening

- plugin/drop-zone/Event/Log/LogCorrectionReportEvent.php
- plugin/drop-zone/Event/Log/LogDropReportEvent.php
> [DropZoneBundle] Fixes correction reporting

- main/core/API/Serializer/Template/TemplateSerializer.php
- main/core/Resources/modules/administration/template/components/template.jsx
> Adds an option in template form to define as default template

- main/core/Manager/Workspace/WorkspaceManager.php
> [CoreBundle] User registration condition fix.

- main/core/Manager/ResourceManager.php
- main/core/Manager/Workspace/WorkspaceManager.php
> This code should not have been removed.

- plugin/exo/Resources/modules/items/words/components/editor.jsx
- plugin/exo/Resources/modules/items/words/index.js
- plugin/exo/Resources/modules/items/words/prop-types.js
- plugin/exo/Resources/modules/resources/quiz/components/type.jsx
> Keyword question (draft)

- main/core/Resources/translations/platform.en.json
- main/core/Resources/translations/platform.fr.json
- plugin/exo/Resources/modules/items/pair/components/editor.jsx
- plugin/exo/Resources/modules/items/pair/components/pair-item-drag-preview.jsx
- plugin/exo/Resources/modules/items/pair/index.js
- plugin/exo/Resources/modules/items/pair/prop-types.jsx
> Refactors Pair Item editor

- plugin/exo/Resources/modules/items/set/components/editor.jsx
- plugin/exo/Resources/modules/items/set/components/set-item-drag-preview.jsx
- plugin/exo/Resources/modules/items/set/index.js
- plugin/exo/Resources/modules/items/set/prop-types.js
> Refactors editor of Set Item

- plugin/exo/Resources/modules/items/match/components/editor.jsx
- plugin/exo/Resources/modules/items/match/index.js
- plugin/exo/Resources/modules/items/match/prop-types.js
- plugin/exo/Resources/modules/resources/quiz/components/type.jsx
> Match question

- plugin/exo/Resources/modules/items/ordering/components/editor.jsx
- plugin/exo/Resources/modules/items/ordering/components/ordering-item-drag-preview.jsx
- plugin/exo/Resources/modules/items/ordering/constants.js
- plugin/exo/Resources/modules/items/ordering/index.js
- plugin/exo/Resources/modules/items/ordering/prop-types.jsx
- plugin/exo/Resources/translations/quiz.en.json
- plugin/exo/Resources/translations/quiz.fr.json
> Refactors editor for Ordering Item

- main/app/Resources/modules/polyfills/core-js.js
- main/core/Resources/modules/resource/components/page.jsx
- main/core/Resources/modules/tools/resources/components/tool.jsx
- main/core/Resources/modules/tools/resources/containers/tool.jsx
> [CoreBundle] opens resource manager in resource breadcrumbs

- main/core/Resources/modules/administration/user/parameters/components/parameters-tab.jsx
- main/core/Resources/modules/administration/workspace/parameters/components/parameters-tab.jsx
- plugin/tag/Repository/TaggedObjectRepository.php
> [TagBundle] Workspace tag redirect

- plugin/exo/Resources/modules/items/cloze/components/editor.jsx
- plugin/exo/Resources/modules/items/cloze/index.js
- plugin/exo/Resources/modules/items/cloze/prop-types.js
It triggers some errors at the beginning atm, but it works.
Changing the editor mode make things VERY slow.
> Cloze question

- main/core/Tests/NewAPI/SerializerProviderTest.php
- main/dev/Resources/travis/composer.lock
- main/migration/Manager/Manager.php
- plugin/open-badge/Serializer/AlignementObjectSerializer.php
- plugin/open-badge/Serializer/HostedBadgeSerializer.php
- plugin/open-badge/Serializer/RevocationListSerializer.php
- plugin/open-badge/Serializer/SignedBadgeSerializer.php
> [Travis] Composer.lock for tests.

- main/core/Entity/Organization/Organization.php
- main/core/Entity/User.php
| Fixed issues | #5666
J'ai quand meme mit un garde fou pour éviter de supprimer l'orga principale.
> [CoreBundle] Can remove organizations.

- main/core/Entity/Workspace/WorkspaceRegistrationQueue.php
| Fixed issues | #5678
Ça avait été rajouté par 
https://github.com/claroline/Distribution/commit/2d1e4a51ff6eef0208a223bceb401656a96735cd#diff-0b2c9c2c68746ad865d132caa4ac230c
Mais cette ligne n'est plus d'actualité. Je pense que c'est à cause de l'effet de bord sur les tags qu'on a eu à un moment et corrigé.
> [CoreBundle] Pending registration.

- plugin/exo/Controller/Api/AttemptController.php
- plugin/exo/Manager/AttemptManager.php
- plugin/exo/Resources/modules/quiz/overview/overview.jsx
- plugin/exo/Resources/modules/resources/quiz/components/resource.jsx
> Fixes anonymous access

- plugin/exo/Resources/modules/quiz/player/components/nav-bar.jsx
> Saves current answer when navigating to previous step

- plugin/exo/Event/Log/LogExerciseUpdateEvent.php
- plugin/exo/Manager/ExerciseManager.php
> [ExoBundle] Creates a log when updating exercise

- plugin/exo/Resources/modules/items/cloze/components/editor.jsx
- plugin/exo/Resources/modules/items/cloze/prop-types.js
- plugin/exo/Resources/modules/items/selection/components/editor.jsx
- plugin/exo/Resources/modules/items/selection/prop-types.js
- plugin/exo/Resources/modules/items/selection/utils/utils.js
> Fixes missing props in Cloze & Selection items

- main/app/Resources/modules/data/types/choice/components/input.jsx
> fixes #5650

- main/core/API/Serializer/User/UserSerializer.php
- main/core/Controller/RedirectController.php
- main/core/Controller/Tool/WorkspaceParametersController.php
- main/core/Entity/User.php
- main/core/Migrations/pdo_mysql/Version20190328135330.php
- main/core/Resources/modules/user/registration/index.js
- main/core/Resources/modules/user/registration/reducer.js
- main/core/Resources/views/tool/workspace/parameters/generate_url_subscription_anonymous.html.twig
> [CoreBundle] User code on registration.

- main/app/Resources/modules/data/types/file/components/input.jsx
- plugin/exo/Resources/modules/contents/audio/components/editor.jsx
- plugin/exo/Resources/modules/contents/audio/index.js
- plugin/exo/Resources/modules/contents/image/components/editor.jsx
- plugin/exo/Resources/modules/contents/image/components/player.jsx
- plugin/exo/Resources/modules/contents/image/index.js
- plugin/exo/Resources/modules/contents/video/components/editor.jsx
- plugin/exo/Resources/modules/contents/video/index.js
- plugin/exo/Resources/modules/items/index.js
- plugin/exo/Resources/modules/resources/quiz/editor/components/parameters.jsx
> [ExoBundle] restores content items

- main/app/Resources/modules/data/types/username/components/input.jsx
> fixes username input

- main/app/Logger/JsonLogger.php
- main/core/Resources/modules/administration/parameters/technical/components/mailing.jsx
- JsonLogger error on file null fixed.
- Administration mailing parameters form fixed.
> [CoreBundle] Fixing some bugs.

- main/app/Resources/modules/data/types/collection/components/input.jsx
- plugin/exo/Resources/modules/items/components/editor.jsx
- plugin/exo/Resources/modules/items/pair/components/editor.jsx
- plugin/exo/Serializer/Item/Type/PairQuestionSerializer.php
> [ExoBundle] Fixes several bugs

- main/core/Command/UpdateRichTextCommand.php
> [CoreBundle] Rich text.

- main/core/Controller/APINew/Log/LogConnectController.php
- main/core/Manager/LogConnectManager.php
> Fixes log connections csv download

- plugin/announcement/Controller/API/AnnouncementController.php
> [AnnouncementBundle] Email sent: fixing the query parameters.

- plugin/exo/Library/Item/Definition/AbstractDefinition.php
- plugin/exo/Library/Item/Definition/BooleanDefinition.php
- plugin/exo/Library/Item/Definition/ContentItemDefinition.php
- plugin/exo/Library/Item/Definition/ItemDefinitionInterface.php
- plugin/exo/Library/Validator/JsonSchemaValidator.php
- plugin/exo/Manager/Attempt/ScoreManager.php
- plugin/exo/Tests/Library/Attempt/PaperGeneratorTest.php
- plugin/exo/Validator/JsonSchema/Attempt/AnswerData/ClozeAnswerValidator.php
- plugin/exo/Validator/JsonSchema/Attempt/AnswerData/GraphicAnswerValidator.php
- plugin/exo/Validator/JsonSchema/Attempt/AnswerData/GridAnswerValidator.php
- plugin/exo/Validator/JsonSchema/Attempt/AnswerData/MatchAnswerValidator.php
- plugin/exo/Validator/JsonSchema/Attempt/AnswerData/OrderingAnswerValidator.php
- plugin/exo/Validator/JsonSchema/Attempt/AnswerData/SetAnswerValidator.php
- plugin/exo/Validator/JsonSchema/Attempt/AnswerValidator.php
- plugin/exo/Validator/JsonSchema/ExerciseValidator.php
- plugin/exo/Validator/JsonSchema/Item/HintValidator.php
- plugin/exo/Validator/JsonSchema/Item/ItemValidator.php
- plugin/exo/Validator/JsonSchema/Item/Type/ChoiceQuestionValidator.php
- plugin/exo/Validator/JsonSchema/Item/Type/ClozeQuestionValidator.php
- plugin/exo/Validator/JsonSchema/Item/Type/GraphicQuestionValidator.php
- plugin/exo/Validator/JsonSchema/Item/Type/GridQuestionValidator.php
- plugin/exo/Validator/JsonSchema/Item/Type/MatchQuestionValidator.php
- plugin/exo/Validator/JsonSchema/Item/Type/OrderingQuestionValidator.php
- plugin/exo/Validator/JsonSchema/Item/Type/PairQuestionValidator.php
- plugin/exo/Validator/JsonSchema/Item/Type/SelectionQuestionValidator.php
- plugin/exo/Validator/JsonSchema/Item/Type/SetQuestionValidator.php
- plugin/exo/Validator/JsonSchema/Item/Type/WordsQuestionValidator.php
- plugin/exo/Validator/JsonSchema/StepValidator.php
> [ExoBundle] fixes api

- main/app/Command/ApiDumperCommand.php
- main/app/Routing/Documentator.php
> [AppBundle] Fixing doc generation (albeit incomplete)

- plugin/drop-zone/Manager/DropzoneManager.php
> Fixes deserialization issue in DropZoneBundle

- plugin/exo/Library/Attempt/PaperGenerator.php
> [ExoBundle] Fixes type bug in Paper Generator

- main/app/API/Crud.php
> [AppBundle] Create object if not found on update.

- plugin/drop-zone/Serializer/CorrectionSerializer.php
> [DropZoneBundle] Fixes correction creation by manager

- main/core/Controller/APINew/FileController.php
> [CoreBundle] Fixing public file removal.

- plugin/exo/Installation/AdditionalInstaller.php
- plugin/exo/Installation/Updater/Updater120403.php
- plugin/exo/Installation/Updater/Updater120406.php
> [ExoBundle] fixes boolean items migration

- plugin/exo/Installation/AdditionalInstaller.php
> [ExoBundle] fixes installer

- main/core/API/Serializer/Resource/ResourceNodeSerializer.php
- main/core/API/Serializer/Resource/Types/FileSerializer.php
- main/core/Manager/ResourceManager.php
> [CoreBundle] Fixing copies.

- main/core/Manager/ResourceManager.php
- plugin/claco-form/Entity/ClacoForm.php
- plugin/claco-form/Listener/Resource/ClacoFormListener.php
- plugin/claco-form/Manager/ClacoFormManager.php
- plugin/exo/Serializer/ExerciseSerializer.php
- plugin/path/Entity/Path/Path.php
- plugin/path/Entity/Step.php
- plugin/path/Listener/Resource/PathListener.php
- plugin/path/Serializer/PathSerializer.php
> [PathBundle] fixes path copy

- main/app/Resources/modules/content/card/components/data.jsx
- main/app/Resources/modules/content/card/prop-types.js
- main/app/Resources/modules/content/list/components/actions.jsx
- main/app/Resources/modules/content/list/components/view/data-grid.jsx
- main/core/Resources/modules/workspace/actions/configure.js
- main/core/Resources/modules/workspace/actions/register-groups.js
- main/core/Resources/modules/workspace/actions/register-users.js
> [CoreBundle] fixes #5801

- plugin/announcement/Controller/AnnouncementController.php
- plugin/announcement/Entity/Announcement.php
- plugin/announcement/Entity/AnnouncementAggregate.php
- plugin/announcement/Listener/Resource/AnnouncementListener.php
- plugin/announcement/Serializer/AnnouncementAggregateSerializer.php
- plugin/announcement/Serializer/AnnouncementSerializer.php
> [AnnouncementBundle] fixes serializer and api

- main/core/Command/DatabaseIntegrity/CleanResourceTypeDatabaseCommand.php
> [CoreBundle] MediaResource cleaning tables.

- main/app/Manager/DatabaseManager.php
> [CoreBundle] DatabaseManager dump csv on not found.

- main/core/Command/User/CreateCommand.php
- main/core/Manager/UserManager.php
- main/core/Manager/Workspace/Transfer/Tools/ResourceManager.php
- main/core/Manager/Workspace/WorkspaceManager.php
> [CoreBundle] Fixing user creation.

- plugin/scorm/Listener/ScormListener.php
> [ScormBundle] Scorm copy.

- main/core/Manager/ProgressionManager.php
> Fixes children list in progression

- main/core/Controller/APINew/Workspace/WorkspaceController.php
> [CoreBundle] Workspace creation from api fix.

- main/core/API/Serializer/Workspace/WorkspaceSerializer.php
- main/core/Manager/Workspace/WorkspaceManager.php
- plugin/open-badge/Manager/OpenBadgeManager.php
> [CoreBundle] WorkspaceSerializer: finder for managers.

- plugin/wiki/Resources/modules/resources/wiki/player/components/wiki-section-form.jsx
- plugin/wiki/Resources/translations/icap_wiki.en.json
- plugin/wiki/Resources/translations/icap_wiki.fr.json
> [WikiBundle] Add translation.

- main/app/API/Crud.php
- main/app/Event/Crud/CreateEvent.php
- main/core/API/Crud/User/UserCrud.php
| Fixed issues | #5755 
Note: la philosophie des serializers a changée. Il faut également faire la meme manip pour les roles/orgas.
> [CoreBundle] Groups can be added w/ user import.

- main/core/Controller/APINew/User/LocationController.php
- main/core/Entity/Organization/Location.php
- main/core/Entity/Organization/Organization.php
- main/core/Resources/modules/administration/user/location/actions.js
> [CoreBundle] Fixing orga location link.

- main/app/API/Transfer/Action/AbstractDeleteAction.php
- main/core/API/Transfer/Action/User/Create.php
- main/core/API/Transfer/Action/User/CreateOrUpdate.php
- main/core/Resources/schemas/user.json
> [CoreBundle] It's now possible to do user csv import with workspaces.

- main/core/Listener/AuthenticationSuccessListener.php
- plugin/tag/Listener/TagListener.php
- plugin/tag/Manager/TagManager.php
- plugin/tag/Repository/TaggedObjectRepository.php
> [CoreBundle] Workspace tag redirection.

- main/core/Manager/Task/ScheduledTaskManager.php
> [CoreBundle] Fixing ScheduledTaskManager update.

- main/core/Command/DatabaseIntegrity/ResourceSlugBuilderCommand.php
- main/core/Entity/Resource/ResourceNode.php
- main/core/Migrations/pdo_mysql/Version20190514145921.php
> [CoreBundle] Sluggable resource node.

- plugin/claco-form/Installation/AdditionalInstaller.php
- plugin/claco-form/Installation/Updater/Updater120410.php
- plugin/claco-form/Resources/modules/data/sources/entries.js
- plugin/claco-form/Serializer/EntrySerializer.php
| Fixed issues | fixe https://github.com/claroline/Distribution/issues/5848
> [ClacoFormBundle] Restore proper displayed column name.

- plugin/wiki/Listener/Resource/WikiListener.php
- plugin/wiki/Manager/WikiManager.php
> [WikiBundle] Fixing wiki copy.

- main/core/Manager/Workspace/WorkspaceManager.php
> [CoreBundle] Fixing getWorkspaceOptions from ScheduledInserts.

- plugin/claco-form/Resources/modules/resources/claco-form/template.js
> Adds template help for title field in ClacoForm editor

- main/core/API/Serializer/Platform/ClientSerializer.php
- main/core/Event/GenericDataEvent.php
> [CoreBundle] Client config updatable from plugins.

- main/core/API/Crud/WorkspaceCrud.php
- main/core/Manager/Workspace/WorkspaceManager.php
- plugin/drop-zone/Crud/Dropzone.php
- plugin/drop-zone/Manager/DropzoneManager.php
- plugin/drop-zone/Serializer/DropzoneSerializer.php
| Fixed issues | #5868
Je n'ai jamais pu reproduire en local. L'édition fonctionne toujours bien. La copie je sais pas car j'ai jamais eu le problème ailleurs que sur le serveur.
C'est pour ça que j'ai refait une pr d'ailleurs. Ici j'ai pas testé en live la copie. Juste l'édition en local.
> [CoreBundle] Dropzone copy fix

- plugin/exo/Entity/Attempt/Paper.php
- plugin/exo/Installation/Updater/Updater120410.php
- plugin/exo/Library/Model/ScoreTrait.php
- plugin/exo/Manager/Attempt/PaperManager.php
- plugin/exo/Resources/modules/items/choice/components/editor.jsx
- plugin/exo/Resources/modules/items/components/editor.jsx
- plugin/exo/Resources/modules/quiz/player/actions.js
- plugin/exo/Resources/modules/resources/quiz/editor/components/item.jsx
- plugin/exo/Resources/modules/resources/quiz/editor/components/main.jsx
- plugin/exo/Resources/modules/resources/quiz/editor/components/parameters.jsx
- plugin/exo/Resources/modules/resources/quiz/editor/components/step.jsx
- plugin/exo/Resources/modules/resources/quiz/editor/containers/main.jsx
- plugin/exo/Resources/modules/resources/quiz/editor/store/selectors.js
- plugin/exo/Resources/modules/resources/quiz/papers/restrictions.js
- plugin/exo/Resources/modules/resources/quiz/papers/score.js
- plugin/exo/Resources/modules/resources/quiz/papers/store/actions.js
- plugin/exo/Resources/modules/scores/none/prop-types.js
- plugin/exo/Resources/modules/scores/sum/index.js
> [ExoBundle] fixes multiple bugs

- plugin/exo/Manager/Attempt/ScoreManager.php
> [ExoBundle] fixes rules score

- plugin/exo/Installation/Updater/Updater120410.php
> [ExoBundle] fixes updater

- plugin/exo/Library/Attempt/GenericScore.php
- plugin/exo/Manager/Attempt/PaperManager.php
- plugin/exo/Resources/modules/resources/quiz/papers/score.js
> [ExoBundle] fixes answers with negative score

- plugin/exo/Resources/modules/items/score.js
- plugin/exo/Resources/modules/items/set/index.js
- plugin/exo/Resources/modules/quiz/player/actions.js
- plugin/exo/Resources/modules/quiz/player/components/attempt-end.jsx
- plugin/exo/Resources/modules/quiz/player/selectors.js
- plugin/exo/Resources/modules/quiz/selectors.js
- plugin/exo/Resources/modules/resources/quiz/components/resource.jsx
- plugin/exo/Resources/modules/resources/quiz/player/attempt.js
- plugin/exo/Resources/modules/scores/index.js
> [ExoBundle] fixes test mode

- main/core/Resources/less/layout/components/contents.less
> [PathBundle] fixes display

- main/core/Manager/Workspace/Transfer/Tools/ResourceManager.php
> [CoreBundle] Workspace copy ignore soft-delete resources.

- main/app/API/TransferProvider.php
> [CoreBundle] Csv with duplicates.

- plugin/audio-player/Controller/API/SectionCommentController.php
- plugin/audio-player/Resources/modules/files/audio/components/player.jsx
- plugin/audio-player/Resources/modules/files/audio/components/sections-comments.jsx
> [AudioPlayerBundle ]Allows to also see comments of manager sections

- main/app/API/Listener/ApiListener.php
> [CoreBundle] Api returns error even if not through ajax properly.

- main/core/API/Transfer/Action/Directory/CreateOrUpdate.php
> [CoreBundle] Directory import. Better role management.

- main/core/Controller/APINew/Tool/HomeController.php
C'est pas la première fois qu'on me le demande (éditer les widgets via l'api).
Y a pas de route pour le get pour le moment. L'update est là mais la structure est compliquée.
Ici c'est "facile". On fetch les données avec le get. On modifie ce qu'il faut, et on soumet en post.
@clarophil
> [CoreBundle] HomeTool: fetch workspace home datas.

- composer.json
- main/core/Resources/config/suggested/assetic.yml
> fixes installation

- plugin/exo/Resources/modules/resources/quiz/editor/components/parameters.jsx
> fixes #5907

- main/core/Resources/schemas/resource/types/directory.json
> fixes #5916

- main/app/Resources/modules/data/types/collection/components/input.jsx
> fixes collection input

- main/core/API/Finder/User/UserFinder.php
- main/core/Resources/modules/administration/user/user/components/user-list.jsx
- main/core/Resources/modules/modals/users/components/modal.jsx
> [CoreBundle] Organization fileter for users.

- main/core/Manager/Workspace/TransferManager.php
> [CoreBundle] Copy default role properly.

- plugin/blog/Manager/PostManager.php
> [BlogBundle] Blog rss feed is now in correct order.

- plugin/drop-zone/Resources/modules/resources/dropzone/player/components/my-drop.jsx
- plugin/exo/Resources/modules/quiz/player/reducers.js
> Small fixes in ExoBundle & DropZoneBundle

- package.json
This fixes a compilation error in IE11.
> upgrades react-dnd

- plugin/exo/Manager/ExerciseManager.php
> Fixes export of anonymous papers

- plugin/forum/Resources/modules/resources/forum/overview/components/overview.jsx
- plugin/forum/Resources/modules/resources/forum/prop-types.js
- plugin/forum/Resources/modules/resources/forum/store/selectors.js
- plugin/forum/Serializer/ForumSerializer.php
- plugin/tag/Listener/TagListener.php
> Fixes tag buttons in Forum overview

- plugin/claco-form/Resources/modules/resources/claco-form/constants.js
- plugin/claco-form/Resources/modules/resources/claco-form/player/components/entry.jsx
> Fixes nav buttons & allows to hide menu

- main/core/API/Serializer/ConnectionMessage/ConnectionMessageSerializer.php
- main/core/API/Serializer/ConnectionMessage/SlideSerializer.php
- main/core/Entity/ConnectionMessage/ConnectionMessage.php
- main/core/Entity/ConnectionMessage/Slide.php
- main/core/Migrations/pdo_mysql/Version20190703113552.php
- main/core/Resources/modules/administration/parameters/main/components/message.jsx
- main/core/Resources/modules/administration/parameters/main/modals/slide/components/modal.jsx
- main/core/Resources/modules/administration/parameters/main/prop-types.js
> Uses trait in ConnectionMessage entities

- main/core/Library/Installation/AdditionalInstaller.php
- main/core/Library/Installation/Updater/Updater120500.php
> fixe 12.5.0 updater call

- plugin/drop-zone/Resources/modules/resources/dropzone/components/resource.jsx
- plugin/drop-zone/Resources/modules/resources/dropzone/containers/resource.jsx
- plugin/drop-zone/Resources/modules/resources/dropzone/correction/actions.js
- plugin/drop-zone/Resources/modules/resources/dropzone/correction/components/correction-row.jsx
- plugin/drop-zone/Resources/modules/resources/dropzone/correction/components/corrector.jsx
- plugin/drop-zone/Resources/modules/resources/dropzone/correction/components/correctors.jsx
- plugin/drop-zone/Resources/modules/resources/dropzone/correction/components/drop.jsx
- plugin/drop-zone/Resources/modules/resources/dropzone/correction/components/drops.jsx
- plugin/drop-zone/Resources/modules/resources/dropzone/correction/reducer.js
- plugin/drop-zone/Resources/modules/resources/dropzone/editor/components/editor.jsx
- plugin/drop-zone/Resources/modules/resources/dropzone/editor/reducer.js
- plugin/drop-zone/Resources/modules/resources/dropzone/index.js
- plugin/drop-zone/Resources/modules/resources/dropzone/overview/components/overview.jsx
- plugin/drop-zone/Resources/modules/resources/dropzone/player/actions.js
- plugin/drop-zone/Resources/modules/resources/dropzone/player/components/comments.jsx
- plugin/drop-zone/Resources/modules/resources/dropzone/player/components/my-drop.jsx
- plugin/drop-zone/Resources/modules/resources/dropzone/player/components/my-revisions.jsx
- plugin/drop-zone/Resources/modules/resources/dropzone/player/components/peer-drop.jsx
- plugin/drop-zone/Resources/modules/resources/dropzone/player/components/revision.jsx
- plugin/drop-zone/Resources/modules/resources/dropzone/player/components/revisions.jsx
- plugin/drop-zone/Resources/modules/resources/dropzone/player/reducer.js
- plugin/drop-zone/Resources/modules/resources/dropzone/store/index.js
- plugin/drop-zone/Resources/modules/resources/dropzone/store/reducer.js
- plugin/drop-zone/Resources/modules/resources/dropzone/store/selectors.js
> Refactors dropzone for SPA

- main/core/Entity/ConnectionMessage/ConnectionMessage.php
- main/core/Manager/ConnectionMessageManager.php
- main/core/Repository/ConnectionMessage/ConnectionMessageRepository.php
> Adds function to fetch connection messages for an user

- main/core/Manager/UserManager.php
- plugin/announcement/Resources/modules/data/sources/announcements.js
- plugin/announcement/Resources/modules/resources/announcement/actions/create-announce.js
- plugin/announcement/Resources/modules/resources/announcement/components/announce-form.jsx
- plugin/announcement/Resources/modules/resources/announcement/components/announce-post.jsx
- plugin/announcement/Resources/modules/resources/announcement/components/announce-send.jsx
- plugin/announcement/Resources/modules/resources/announcement/components/announce.jsx
- plugin/announcement/Resources/modules/resources/announcement/components/announces.jsx
- plugin/announcement/Resources/modules/resources/announcement/components/resource.jsx
- plugin/announcement/Resources/modules/resources/announcement/index.js
- plugin/announcement/Resources/modules/resources/announcement/store/reducer.js
- plugin/announcement/Resources/modules/resources/announcement/store/selectors.js
> Fixes user in token + refactors announcement for SPA

- plugin/exo/Finder/PaperFinder.php
- plugin/exo/Installation/Updater/Updater120410.php
> [ExoBundle] Paper score migration performance

- plugin/rss/Resources/translations/rss.en.json
- plugin/rss/Resources/translations/rss.fr.json
- plugin/rss/Serializer/RssSerializer.php
> Adds translations + fixes white page when url does not exist

- main/app/Resources/modules/security/login/containers/form.jsx
> fixes login page

- plugin/slideshow/Resources/modules/resources/slideshow/components/resource.jsx
- plugin/slideshow/Resources/modules/resources/slideshow/editor/components/editor.jsx
- plugin/slideshow/Resources/modules/resources/slideshow/editor/store/reducer.js
- plugin/slideshow/Resources/modules/resources/slideshow/index.js
- plugin/slideshow/Resources/modules/resources/slideshow/player/components/overview.jsx
- plugin/slideshow/Resources/modules/resources/slideshow/store/reducer.js
- plugin/slideshow/Resources/modules/resources/slideshow/store/selectors.js
> Refactors slideshow for SPA

- plugin/bibliography/Resources/modules/resources/book-reference/components/resource.jsx
- plugin/bibliography/Resources/modules/resources/book-reference/editor/components/editor.jsx
- plugin/bibliography/Resources/modules/resources/book-reference/index.js
- plugin/bibliography/Resources/modules/resources/book-reference/store/reducer.js
- plugin/bibliography/Resources/modules/resources/book-reference/store/selectors.js
> Refactors bibliography for SPA

- plugin/lti/Resources/modules/resources/lti/components/resource.jsx
- plugin/lti/Resources/modules/resources/lti/editor/components/editor.jsx
- plugin/lti/Resources/modules/resources/lti/index.js
- plugin/lti/Resources/modules/resources/lti/store/reducer.js
- plugin/lti/Resources/modules/resources/lti/store/selectors.js
> Refactors LTI resource for SPA

- plugin/wiki/Resources/modules/resources/wiki/components/resource.jsx
- plugin/wiki/Resources/modules/resources/wiki/editor/components/editor.jsx
- plugin/wiki/Resources/modules/resources/wiki/editor/store/reducer.js
- plugin/wiki/Resources/modules/resources/wiki/history/components/history.jsx
- plugin/wiki/Resources/modules/resources/wiki/index.js
- plugin/wiki/Resources/modules/resources/wiki/player/components/wiki-section.jsx
- plugin/wiki/Resources/modules/resources/wiki/player/store/reducer.js
- plugin/wiki/Resources/modules/resources/wiki/store/reducer.js
- plugin/wiki/Resources/modules/resources/wiki/store/selectors.js
> Refactors wiki for SPA

- main/core/Resources/modules/administration/dashboard/components/tool.jsx
- plugin/competency/Resources/modules/administration/competency/components/tool.jsx
>  Adds subtitles for some admin tools

- main/core/Command/DatabaseIntegrity/ResourceSlugBuilderCommand.php
> [CoreBundle] Slug generation command is now instantaneous.

- plugin/message/Resources/modules/tools/messaging/components/deleted-messages.jsx
- plugin/message/Resources/modules/tools/messaging/components/message.jsx
- plugin/message/Resources/modules/tools/messaging/components/new-message.jsx
- plugin/message/Resources/modules/tools/messaging/components/received-messages.jsx
- plugin/message/Resources/translations/message.en.json
- plugin/message/Resources/translations/message.fr.json
> Fixes translations + redirections

- main/core/Resources/modules/tools/dashboard/path/modals/step-details/components/modal.jsx
> Allows to send a message to users who have done a step

- plugin/path/Controller/API/PathTrackingController.php
> Only display last step done by users in paths tracking

- main/core/Resources/modules/resource/components/embedded.jsx
> fixes embedded resources

- main/core/Resources/less/layout/components/breadcrumb.less
- main/core/Resources/less/layout/menu.less
> Elorfin ui

- .travis.yml
- main/core/Library/Installation/Updater/Updater120200.php
- main/core/Resources/modules/data/sources/workspaces.js
- plugin/tag/Manager/TagManager.php
> Hotfix from server

- main/core/API/Finder/Workspace/WorkspaceFinder.php
- main/core/Command/Archive/ArchiveWorkspaceCommand.php
- main/core/Entity/Role.php
- main/core/Entity/Workspace/Workspace.php
- main/core/Library/Installation/AdditionalInstaller.php
- main/core/Library/Installation/Updater/Updater120414.php
- main/core/Manager/Workspace/WorkspaceManager.php
- main/core/Migrations/pdo_mysql/Version20190814143949.php
- main/core/Resources/modules/administration/workspace/workspace/components/workspace-list.jsx
- main/core/Resources/modules/data/sources/workspaces.js
> [CoreBundle] it's now possible to archive workspaces (new  flag & cmd)

- main/core/Command/Dev/ExportWorkspaceModelCommand.php
- main/core/Manager/Workspace/WorkspaceManager.php
- plugin/announcement/Finder/AnnouncementFinder.php
> [CoreBundle] finder search for archive + don't remove users from archive.

- main/core/Resources/modules/tools/home/player/components/tab.jsx
> Updates switch button of home tabs

- main/core/Resources/modules/workspace/store/actions.js
> Reloads workspace after self-registration from workspace restrictions page

- main/core/Listener/DataSource/ToolSource.php
- main/core/Resources/modules/data/sources/tools.js
> Implements primary action for tool data source

- main/app/Resources/modules/layout/header/components/main.jsx
- main/app/Resources/modules/layout/header/components/user.jsx
- main/app/Resources/modules/layout/header/containers/main.jsx
> Hides administration button in user menu for non-admin

- plugin/path/Migrations/pdo_mysql/Version20190821151113.php
> remove the where

- main/core/API/Finder/Workspace/WorkspaceFinder.php
- main/core/Migrations/pdo_mysql/Version20190814143949.php
> Workspace archives

- main/app/API/TransferProvider.php
- main/core/API/Transfer/Action/Group/AddUser.php
- main/core/Entity/Group.php
> Fix csv group

- main/core/Resources/modules/tools/community/user/store/actions.js
> [CoreBundle] Fix workspace user add.

- main/core/Controller/ResourceController.php
> Fixes resource evaluation creation when opening a resource for anonymous

- main/core/Manager/Workspace/WorkspaceManager.php
> Also copy shortcuts from model when creating a workspace

- main/core/API/Crud/User/UserCrud.php
> Creates default desktop tools at user creation

- plugin/claco-form/Manager/ClacoFormManager.php
- plugin/claco-form/Resources/modules/resources/claco-form/actions/add-entry.js
- plugin/claco-form/Resources/modules/resources/claco-form/player/components/entry.jsx
- plugin/claco-form/Serializer/EntrySerializer.php
> Fixes in ClacoForm

- plugin/claco-form/Resources/modules/resources/claco-form/player/components/entry.jsx
- plugin/claco-form/Serializer/EntrySerializer.php
> Fixes publication date

- plugin/open-badge/ClarolineOpenBadgeBundle.php
- plugin/open-badge/DataFixtures/PostInstall/LoadTemplateData.php
> Creates default badge templates at installation

- plugin/competency/Entity/Ability.php
- plugin/competency/Entity/Competency.php
- plugin/competency/Entity/Progress/AbilityProgress.php
- plugin/competency/Entity/Progress/AbstractCompetencyProgress.php
- plugin/competency/Migrations/pdo_mysql/Version20150824165947.php
- plugin/competency/Migrations/pdo_mysql/Version20190909144722.php
- plugin/competency/Resources/format/framework.json
> fixes competency migrations

- main/core/Resources/modules/administration/community/group/components/group-tab.jsx
- main/core/Resources/modules/administration/community/location/components/location-tab.jsx
- main/core/Resources/modules/administration/community/organization/components/organization-tab.jsx
- main/core/Resources/modules/administration/community/organization/components/organization.jsx
- main/core/Resources/modules/administration/community/organization/components/organizations.jsx
- main/core/Resources/modules/administration/community/organization/store/selectors.js
- main/core/Resources/modules/administration/community/role/components/role-tab.jsx
- main/core/Resources/modules/administration/community/user/components/user-tab.jsx
> fixes organization form loading

- main/core/Library/Configuration/PlatformConfigurationHandler.php
> [CoreBundle] ConfigurationHandler small fix

- main/app/API/Crud.php
- main/app/API/Options.php
- main/app/API/Transfer/Action/AbstractAction.php
- main/app/API/TransferProvider.php
- main/core/API/Transfer/Action/Workspace/Create.php
- main/core/Entity/Resource/ResourceNode.php
> [CoreBundle] Workspace csv copy part 1.

- main/core/Resources/modules/resource/utils.js
> fixes resource manager

- doc/sections/plugins/resources.md
- main/core/Listener/Resource/Types/FileListener.php
- main/core/Listener/Resource/Types/TextListener.php
- main/core/Manager/ResourceManager.php
- plugin/announcement/Listener/Resource/AnnouncementListener.php
- plugin/bibliography/Listener/Resource/BibliographyListener.php
- plugin/blog/Listener/BlogListener.php
- plugin/claco-form/Listener/Resource/ClacoFormListener.php
- plugin/drop-zone/Listener/Resource/DropzoneListener.php
- plugin/dropzone/Listener/DropzoneListener.php
- plugin/exo/Listener/Resource/ExerciseListener.php
- plugin/forum/Listener/Resource/ForumListener.php
- plugin/lesson/Listener/Resource/LessonListener.php
- plugin/path/Listener/Resource/PathListener.php
- plugin/result/Listener/ResultListener.php
- plugin/rss/Listener/RssListener.php
- plugin/scorm/Listener/Scorm12Listener.php
- plugin/scorm/Listener/Scorm2004Listener.php
- plugin/scorm/Listener/ScormListener.php
- plugin/slideshow/Listener/Resource/SlideshowListener.php
- plugin/url/Listener/UrlListener.php
- plugin/web-resource/Listener/WebResourceListener.php
- plugin/wiki/Listener/Resource/WikiListener.php
> Delete event from lifeCycleManager.

- main/app/API/Crud.php
- main/app/Resources/config/services.yml
> Quick crud fix

- plugin/claco-form/Resources/config/services/serializer.yml
> Fixes config of ClacoFormBundle

- main/core/API/Finder/Workspace/WorkspaceFinder.php
- main/core/Command/Archive/ArchiveWorkspaceCommand.php
> [CoreBundle] Quick fix for archive.

- plugin/forum/Finder/MessageFinder.php
> [ForumBundle] Finder fix.

- main/core/Library/Configuration/PlatformDefaults.php
- main/core/Library/Installation/Updater/Updater120503.php
- plugin/path/Installation/AdditionalInstaller.php
- plugin/path/Installation/Updater/Updater120503.php
> Adds updater for default score to success of path

- plugin/blog/Resources/config/services/services/finder.yml
> [BlogBundle] Wrong service namespace.

- plugin/agenda/Resources/config/services.yml
> agenda serializer

- main/core/API/Finder/Workspace/WorkspaceFinder.php
- main/core/Command/Removal/EmptyWorkspaceByDateCommand.php
- main/core/Resources/config/services/manager.yml
> Clean roles command.

- main/core/Library/Installation/Updater/Updater120504.php
> Fix updater request.

- main/app/API/SchemaProvider.php
- main/app/DependencyInjection/Compiler/ApiConfigPass.php
- main/app/Resources/config/services.yml
Par contre me demandez pas pourquoi.
> [CoreBundle] Fix slow cache generation.

- main/core/Listener/Tool/HomeListener.php
> [CoreBundle] Add a default tab in workspace if missing.

- main/core/Entity/Organization/Organization.php
> [CoreBundle] Organization group collection handling.

- main/app/API/Transfer/Action/AbstractCreateOrUpdateAction.php
> Should fix csv user create

- main/core/Resources/modules/resource/store/actions.js
> [CoreBundle] Fixing resource loading errors

- plugin/agenda/Controller/EventController.php
- plugin/analytics/Listener/Tool/DashboardListener.php
- plugin/announcement/Manager/AnnouncementManager.php
- plugin/rss/Listener/RssListener.php
- plugin/rss/Resources/config/services/services.yml
- plugin/rss/Resources/config/services/services/serializer.yml
> [RssBundle] Migrate + some cleaning.

- plugin/exo/Resources/modules/contents/resource/components/editor.jsx
> Adds filter for resource types when selecting resource content in quiz

- plugin/blog/Controller/Resource/BlogController.php
- plugin/blog/Listener/BlogListener.php
- plugin/blog/Resources/config/services/services/controller.yml
- plugin/blog/Resources/modules/resources/blog/components/resource.jsx
- plugin/blog/Resources/modules/resources/blog/containers/resource.jsx
- plugin/blog/Resources/modules/resources/blog/store/actions.js
- plugin/blog/Resources/modules/resources/blog/store/reducer.js
- plugin/blog/Resources/modules/resources/blog/store/selectors.js
- plugin/blog/Resources/modules/resources/blog/toolbar/components/exporters.jsx
> [BlogBundle] Pdf export

- plugin/lesson/Controller/API/ChapterController.php
- plugin/lesson/Controller/Resource/LessonController.php
- plugin/lesson/Listener/ChapterListener.php
- plugin/lesson/Listener/NotificationListener.php
- plugin/lesson/Listener/NotificationUserParametersListener.php
- plugin/lesson/Listener/Resource/LessonListener.php
- plugin/lesson/Resources/config/services.yml
- plugin/lesson/Resources/config/services/controller.yml
- plugin/lesson/Resources/config/services/listener.yml
- plugin/lesson/Resources/modules/resources/lesson/components/resource.jsx
- plugin/lesson/Resources/modules/resources/lesson/containers/resource.jsx
- plugin/lesson/Resources/modules/resources/lesson/store/actions.js
- plugin/lesson/Resources/modules/resources/lesson/store/reducer.js
- plugin/lesson/Resources/modules/resources/lesson/store/selectors.js
- plugin/wiki/Resources/modules/resources/wiki/store/reducer.js
> [LessonBundle] Lesson export pdf

- main/core/Resources/config/services/manager.yml
- plugin/drop-zone/Listener/Resource/DropzoneListener.php
- plugin/team/Command/TeamIntegrityCheckerCommand.php
- plugin/team/Controller/API/TeamController.php
- plugin/team/Listener/ApiListener.php
- plugin/team/Listener/TeamListener.php
- plugin/team/Manager/TeamManager.php
- plugin/team/Manager/Transfer/Team.php
- plugin/team/Resources/config/services.yml
- plugin/team/Resources/config/services/controller.yml
- plugin/team/Resources/config/services/listener.yml
- plugin/team/Resources/config/services/manager.yml
- plugin/team/Resources/config/services/serializer.yml
> [TeamBundle] Migrate configs.

- main/core/Entity/Log/Connection/LogConnectTool.php
> fixes tool logs

- main/core/Manager/Workspace/Transfer/OrderedToolTransfer.php
- main/core/Manager/Workspace/TransferManager.php
> [CoreBundle] fixes transfer manager

- main/core/Resources/modules/modals/roles/containers/modal.jsx
> [CoreBundle] fixes roles modal

- plugin/planned-notification/Resources/config/services/listener.yml
> [PlannedNotificationBundle] fixes DI

- main/authentication/Resources/config/services/manager.yml
> Restore cache event.

- plugin/exo/Resources/modules/items/cloze/components/editor.jsx
> Fixes cloze text edition

- main/core/Manager/IPWhiteListManager.php
> [CoreBundle] fixes ip white list

- plugin/planned-notification/Listener/LogListener.php
- plugin/planned-notification/Resources/config/services/listener.yml
- plugin/social-media/Controller/Controller.php
- plugin/social-media/Controller/LikeActionController.php
- plugin/social-media/Listener/ApiListener.php
- plugin/social-media/Listener/LogListener.php
- plugin/social-media/Listener/NotificationListener.php
- plugin/social-media/Listener/NotificationUserParametersListener.php
- plugin/social-media/Listener/ResourceActionsListener.php
- plugin/social-media/Manager/CommentActionManager.php
- plugin/social-media/Manager/LikeActionManager.php
- plugin/social-media/Manager/NoteActionManager.php
- plugin/social-media/Manager/ShareActionManager.php
- plugin/social-media/Manager/WallItemManager.php
- plugin/social-media/Resources/config/services.yml
- plugin/social-media/Resources/config/services/controller.yml
- plugin/social-media/Resources/config/services/listener.yml
- plugin/social-media/Resources/config/services/manager.yml
> [SocialMediaBundle] Migrate configs.

- main/app/Resources/modules/action/components/toolbar.jsx
> fixes toolbar styles

- plugin/audio-player/Serializer/Quiz/WaveformQuestionSerializer.php
> Fixes quiz copy with waveform items

- plugin/exo/Resources/modules/items/cloze/components/editor.jsx
- plugin/exo/Serializer/Item/Type/ClozeQuestionSerializer.php
> Many fixes for edition of cloze question

- plugin/planned-notification/Resources/config/services/manager.yml
> [PlannedNotificationBundle] Small config fix.

- main/core/Resources/config/services/manager.yml
> [CoreBundle] fixes ip manager

- plugin/exo/Resources/modules/resources/quiz/editor/components/item.jsx
> [ExoBundle] fixes items edition

- plugin/wiki/Resources/config/services.yml
- plugin/wiki/Resources/config/services/listener.yml
> Wiki creation fix

- plugin/exo/Resources/modules/resources/quiz/correction/store/reducer.js
> Fixes correction reducer in exo

- plugin/exo/Resources/modules/resources/quiz/correction/components/questions.jsx
- plugin/exo/Resources/modules/resources/quiz/correction/store/reducer.js
> Fixes manual correction of open questions

- main/core/Entity/Workspace/Workspace.php
- main/core/Library/Installation/AdditionalInstaller.php
- main/core/Library/Installation/Updater/Updater120421.php
- main/core/Migrations/pdo_mysql/Version20190814143949.php
> Renames Updater 12.4.14 to 12.4.21

- plugin/exo/Resources/modules/resources/quiz/player/attempt.js
> Fixes tag picking in test mode

- plugin/tag/Controller/TagController.php
- plugin/tag/Manager/TagManager.php
- plugin/tag/Repository/TagRepository.php
> Prevents creation of tag if name is already in use + fixes tag fetching

- composer.json
- main/app/Controller/SecurityController.php
- main/core/Controller/APINew/Platform/PluginController.php
- main/core/Controller/Administration/ArchiveController.php
- main/core/Resources/config/services/controller.yml
- plugin/analytics/Controller/Administration/AnalyticsController.php
- plugin/analytics/Controller/Administration/LogController.php
- plugin/analytics/Resources/config/services/controller.yml
- plugin/competency/Controller/MyObjectiveController.php
Ça va être requis pour passer à sf4.
> [Symfony] Removes JMSSecurityExtra.

- main/app/Entity/Meta/CreatedAt.php
- main/app/Entity/Meta/UpdatedAt.php
- plugin/history/Migrations/pdo_mysql/Version20191016124432.php
> [CoreBundle] fixes updatedAt and createdAt traits

- main/core/Command/Dev/HepnRemoveUserCommand.php
> [Hepn] Remove command.

- main/core/Repository/ResourceNodeRepository.php
> [CoreBundle] Find workspace root if many.

- plugin/exo/Manager/Attempt/ScoreManager.php
> [ExoBundle] fixes score calculation

- plugin/exo/Resources/modules/items/cloze/components/editor.jsx
- plugin/exo/Serializer/Item/Type/ClozeQuestionSerializer.php
* Fixes holes serialization after save
* Fixes hole deletion replacement word
* Fixes hole deletion when using button in popover
> Many fixes for edition of cloze question (#6315)

- plugin/exo/Resources/modules/items/cloze/components/editor.jsx
> [ExoBundle] Fix cloze (use the item instead of props.item)

- main/core/Resources/modules/resource/containers/page.jsx
- main/core/Resources/modules/resource/store/actions.js
- main/core/Resources/modules/resource/store/reducer.js
> Fixes resource restrictions page if there is a code

- composer.json
- main/core/ClarolineCoreBundle.php
- main/core/Entity/Role.php
- main/core/Resources/config/suggested/httplug.yml
> [Symfony] Prepare migration.

- main/core/API/Finder/Home/HomeTabFinder.php
This reverts commit 68cb40cf2c1e381c1c2fb94f730ed20fa4102ae6.
> Revert "[CoreBundle] HomeTab request fixes. (#5973)"

- plugin/message/Manager/MessageManager.php
J'ai corrigé en live.
Je comprends pas pourquoi ça fonctionne en local. J'ai peut être pas les même version de doctrine après mes tests d'upgrade vers sf4 mais ça me semble peu probable que ça soit ça.
fix #6368
> [MessageBundle] Persist $message ? no idea why required.

- main/core/Resources/modules/tools/community/user/components/users.jsx
Fix #6365 
Bon là on est plus dans le patch qu'autre chose. Ça corrige le pb sur psycheduc.
Impossible de reproduire l'erreur en local.
> [CoreBundle] Fix user removal condition.

- main/app/Resources/modules/page/components/simple.jsx
- main/core/Resources/modules/resource/components/form.jsx
- main/core/Resources/modules/workspace/components/form.jsx
> Removes unused references to keywords

- main/core/API/Serializer/Widget/HomeTabSerializer.php
> [CoreBundle] fixes home tab roles

- main/core/Repository/ResourceNodeRepository.php
> Fixes resourceNode repo

- plugin/blog/Resources/modules/resources/blog/toolbar/components/archives.jsx
Par contre faudra m'expliquer pourquoi j'ai eu besoin d'utiliser le router (il est sur les autres filtres aussi).
fix #6362
> [BlogBundle] Fixing redirection when filtering archives.

- plugin/open-badge/Resources/modules/tools/badges/badge/components/form.jsx
- plugin/open-badge/Resources/modules/tools/badges/store/actions.js
> Updates badge

- main/app/Entity/Restriction/Hidden.php
- main/app/Resources/modules/content/components/title.jsx
- main/core/API/Finder/ConnectionMessage/ConnectionMessageFinder.php
- main/core/API/Serializer/Platform/ClientSerializer.php
- main/core/API/Serializer/Platform/ConnectionMessageSerializer.php
- main/core/API/Serializer/Tool/AdminToolSerializer.php
- main/core/API/Serializer/User/RoleSerializer.php
- main/core/Entity/ConnectionMessage/ConnectionMessage.php
- main/core/Entity/Facet/FieldFacet.php
- main/core/Entity/Resource/ResourceNode.php
- main/core/Event/GenericDataEvent.php
- main/core/Manager/ConnectionMessageManager.php
- main/core/Manager/CurlManager.php
- main/core/Migrations/pdo_mysql/Version20191031084436.php
- main/core/Migrations/pdo_mysql/Version20191031084808.php
- main/core/Repository/ConnectionMessage/ConnectionMessageRepository.php
- main/core/Resources/config/services/manager.yml
- main/core/Resources/config/services/serializer.yml
- main/core/Resources/less/layout/components/tables.less
- main/core/Resources/modules/administration/parameters/main/components/message.jsx
- main/core/Resources/modules/administration/parameters/main/components/messages.jsx
- main/core/Resources/modules/modals/connection-messages/components/modal.jsx
- main/core/Resources/modules/modals/connection-messages/containers/modal.jsx
- main/core/Resources/modules/modals/connection-messages/index.js
- main/core/Resources/modules/modals/connection-messages/store/index.js
- main/core/Resources/modules/modals/connection-messages/store/reducer.js
- main/core/Resources/modules/modals/connection-messages/store/selectors.js
- plugin/exo/Serializer/Item/ItemSerializer.php
- plugin/notification/Listener/Platform/ClientListener.php
> [CoreBundle] enhances connection messages

- plugin/team/Manager/TeamManager.php
> Fixes team params creation

- main/core/Command/DatabaseIntegrity/RoleIntegrityCheckerCommand.php
- main/core/Command/Removal/RemoveFilesFromUnusedWorkspaceCommand.php
- main/core/Manager/ImportCsvManager.php
- main/core/Manager/UserManager.php
- main/core/Manager/Workspace/WorkspaceManager.php
> [CoreBundle] Clean some olds methods from WorkspaceManager.

- main/app/Resources/modules/content/components/title.jsx
- main/app/Resources/modules/content/form/components/stepper.jsx
- main/core/Resources/less/layout/form/form-stepper.less
- main/core/Resources/modules/modals/connection-messages/components/modal.jsx
- main/core/Resources/modules/widget/types/simple/containers/widget.jsx
> adds small enhancements on base ui components

- main/core/Resources/less/alert/index.less
- main/core/Resources/modules/widget/content/components/content.jsx
> [CoreBundle] allows custom styles in widgets

- main/core/API/Serializer/Facet/FacetSerializer.php
- main/core/API/Serializer/Facet/PanelFacetSerializer.php
- main/core/Resources/config/services/serializer.yml
> Fixes facets serializers

- main/app/API/Crud.php
- main/core/API/Serializer/User/UserSerializer.php
- main/core/Entity/Organization/UserOrganizationReference.php
- main/core/Library/Configuration/PlatformConfigurationHandler.php
- main/core/Resources/modules/administration/community/organization/components/organizations.jsx
>  [CoreBundle] fixes parameters set

- main/app/API/Options.php
- main/app/Resources/modules/content/form/components/stepper.jsx
- main/app/Resources/modules/data/types/email/index.js
- main/app/Resources/modules/data/types/string/index.js
- main/app/Resources/modules/data/types/username/index.js
- main/app/Resources/modules/data/types/validators.js
- main/app/Resources/modules/security/registration/components/main.jsx
- main/app/Resources/modules/security/registration/components/required.jsx
- main/core/API/Crud/User/UserCrud.php
- main/core/API/Transfer/Action/User/Create.php
- main/core/Manager/UserManager.php
> [CoreBundle] enhances forms (unicity check + stepper)

- main/core/Resources/modules/tools/home/editor/store/reducer.js
- main/core/Resources/modules/tools/home/editor/store/selectors.js
- main/core/Resources/modules/tools/home/player/components/tab.jsx
- main/core/Resources/modules/tools/home/player/containers/main.jsx
- main/core/Resources/modules/tools/home/store/actions.js
> [CoreBundle] fixes home edition when empty

- plugin/exo/Resources/modules/items/score.js
> [ExoBundle] Fix score calculate.

- plugin/claco-form/Finder/EntryFinder.php
- plugin/claco-form/Resources/modules/data/sources/entries.js
> Fixes type filter in clacoform

- plugin/claco-form/Finder/EntryFinder.php
- plugin/claco-form/Resources/modules/resources/claco-form/player/store/reducer.js
> Fixes configured filters in clacoform

- main/core/API/Crud/User/OrganizationCrud.php
- main/core/API/Crud/User/UserCrud.php
- main/core/Entity/AbstractRoleSubject.php
- main/core/Manager/Template/TemplateManager.php
> [CoreBundle] fixes user creation default locale

- main/core/Controller/APINew/ParametersController.php
- main/core/Manager/AnalyticsManager.php
- main/core/Resources/config/services/controller.yml
> Computes used storage when retrieving platform infos

- main/core/Manager/Resource/ResourceActionManager.php
- main/core/Resources/modules/resources/directory/components/resource.jsx
- main/core/Resources/modules/resources/directory/player/components/main.jsx
- plugin/claco-form/Manager/ClacoFormManager.php
> Disables resources copy if max storage has been reached + fixes clacoform copy

- main/app/Resources/modules/data/types/fields/components/input.jsx
- plugin/claco-form/Command/RefactorTemplatesCommand.php
- plugin/claco-form/Controller/ClacoFormController.php
- plugin/claco-form/Installation/AdditionalInstaller.php
- plugin/claco-form/Installation/Updater/Updater120506.php
- plugin/claco-form/Installation/Updater/Updater120513.php
- plugin/claco-form/Manager/ClacoFormManager.php
- plugin/claco-form/Resources/config/services/controller.yml
- plugin/claco-form/Resources/modules/resources/claco-form/permissions.js
- plugin/claco-form/Resources/modules/resources/claco-form/player/components/entry-form.jsx
- plugin/claco-form/Resources/modules/resources/claco-form/store/selectors.js
- plugin/claco-form/Resources/modules/resources/claco-form/template.js
- plugin/claco-form/Security/Voter/EntryVoter.php
> Many fixes for clacoform

- plugin/blog/Resources/modules/data/sources/blog-posts.js
- plugin/blog/Resources/modules/resources/blog/post/components/posts.jsx
- plugin/blog/Serializer/PostSerializer.php
> Blog fixes

- main/app/Resources/modules/intl/date/index.js
> Updates elapsed time calculation

- main/core/API/Serializer/Resource/ResourceNodeSerializer.php
> Fixes resource rights edition

- plugin/social-media/Listener/NotificationListener.php
> [SocialMediaBundle] Add missing event use for notifications.

- main/app/API/SerializerProvider.php
- main/app/Controller/AbstractCrudController.php
- main/app/Resources/modules/content/list/store/actions.js
- main/core/Resources/modules/tools/community/user/components/tab.jsx
- main/core/Resources/modules/tools/community/user/containers/tab.jsx
- main/core/Resources/modules/workspace/actions/export.js
> [CoreBundle] exports users csv

- plugin/web-resource/Listener/WebResourceListener.php
| Fixed issues | #6425
Déjà mergé en live sur l'estp pour résoudre #6425.
> [WebResourceBundle] Should fix download and copy.

- main/core/API/Serializer/User/RoleSerializer.php
You can't edit wich role can see what tool atm.
> [CoreBundle] Fix the permission edition for a role in workspace 

- main/core/Resources/modules/resource/components/page.jsx
- main/core/Resources/modules/resource/components/restrictions.jsx
- main/core/Resources/modules/resource/store/actions.js
> Only displays code input in resource restrictions page if it is the only restriction + displays resource if code is correct

- main/core/Manager/Resource/OptimizedRightsManager.php
- plugin/audio-player/Serializer/Resource/SectionSerializer.php
> Fixes workspace copy

- plugin/agenda/Finder/EventFinder.php
- plugin/agenda/Resources/modules/data/sources/events.js
- plugin/agenda/Resources/modules/data/sources/tasks.js
- plugin/agenda/Resources/translations/agenda.en.json
- plugin/agenda/Resources/translations/agenda.fr.json
>  [AgendaBundle] After today filter (required for estp).

- plugin/exo/Resources/modules/items/match/index.js
> Fixes validation of match question

- main/core/Controller/LegacyController.php
- main/core/Library/RoutingHelper.php
> Adds redirection for old home & desktop home urls

- main/core/Resources/modules/workspace/components/main.jsx
> [CoreBundle] fixes redirection on opening a ws tool with no rights

- main/core/Listener/Administration/CommunityListener.php
- main/core/Listener/Tool/CommunityListener.php
- main/core/Manager/UserManager.php
- main/core/Resources/config/services/listener.yml
- main/core/Resources/modules/tools/community/user/components/tab.jsx
- main/core/Resources/modules/tools/community/user/containers/tab.jsx
- main/core/Resources/modules/tools/community/user/store/reducer.js
- main/core/Resources/modules/tools/community/user/store/selectors.js
> [CoreBundle] fixes #6452

- plugin/blog/Controller/API/CommentController.php
- plugin/blog/Resources/modules/resources/blog/post/components/card.jsx
- plugin/blog/Resources/modules/resources/blog/post/components/prop-types.js
> Fixes blog post comments

- main/core/Security/Voter/UserVoter.php
> [CoreBundle] fixes #6468

- plugin/claco-form/Controller/ClacoFormController.php
> Fixes files export during clacoform entries export

- main/core/Manager/RoleManager.php
- main/core/Manager/Workspace/WorkspaceManager.php
> [CoreBundle] fixes workspace roles check

- plugin/path/Command/DatabaseIntegrity/PathSlugCheckerCommand.php
> [PathBundle] adds command to restore steps slug unicity

- main/app/Resources/modules/data/types/date-range/components/input.jsx
- main/app/Resources/modules/data/types/date/components/input.jsx
- main/core/Library/Normalizer/DateRangeNormalizer.php
- main/core/Listener/PlatformListener.php
> [CoreBundle] fixes platform restrictions check

- plugin/agenda/Controller/EventController.php
- plugin/agenda/Finder/EventFinder.php
- plugin/agenda/Listener/DataSource/AgendaSource.php
- plugin/agenda/Resources/modules/data/sources/tasks.js
- plugin/agenda/Resources/modules/event/modals/parameters/components/modal.jsx
- plugin/agenda/Resources/modules/tools/agenda/components/menu.jsx
- plugin/agenda/Resources/modules/tools/agenda/components/tool.jsx
- plugin/agenda/Resources/modules/tools/agenda/store/actions.js
- plugin/agenda/Resources/modules/tools/agenda/views/components/calendar.jsx
- plugin/agenda/Resources/modules/tools/agenda/views/day/index.js
- plugin/agenda/Resources/modules/tools/agenda/views/index.js
- plugin/agenda/Resources/modules/tools/agenda/views/list/components/view.jsx
- plugin/agenda/Resources/modules/tools/agenda/views/list/containers/view.jsx
- plugin/agenda/Resources/modules/tools/agenda/views/list/index.js
- plugin/agenda/Resources/modules/tools/agenda/views/list/store/index.js
- plugin/agenda/Resources/modules/tools/agenda/views/list/store/reducer.js
- plugin/agenda/Resources/modules/tools/agenda/views/list/store/selectors.js
- plugin/agenda/Resources/modules/tools/agenda/views/month/components/view.jsx
- plugin/agenda/Resources/modules/tools/agenda/views/month/index.js
- plugin/agenda/Resources/modules/tools/agenda/views/schedule/components/view.jsx
- plugin/agenda/Resources/modules/tools/agenda/views/schedule/index.js
- plugin/agenda/Resources/modules/tools/agenda/views/week/index.js
- plugin/agenda/Resources/modules/tools/agenda/views/year/index.js
- plugin/agenda/Resources/translations/agenda.en.json
- plugin/agenda/Resources/translations/agenda.fr.json
Je n'ai pas encore activé le mode de vue liste car il pose plus de problème qu'il n'en résoud.
Il y a également un demi fix pour le problème de chargement des évènements à l'ouverture de l'outils (demi fix car il y a encore 1 requête ajax qui part en trop).
> [AgendaBundle] fixes #6466

- main/core/Manager/RoleManager.php
> [CoreBundle] fixes integrity checker

- main/core/Repository/GroupRepository.php
> fixes messages sent to deleted groups

- main/core/Listener/Tool/HomeListener.php
- plugin/agenda/Resources/modules/data/sources/events.js
- plugin/agenda/Resources/modules/data/sources/tasks.js
- plugin/drop-zone/Controller/API/DropzoneController.php
- plugin/wiki/Resources/views/notification/notification_section_create.html.twig
> [CoreBundle] lot of fixe on 12.x

- plugin/claco-form/Controller/API/EntryController.php
- plugin/claco-form/Finder/EntryFinder.php
- plugin/claco-form/Resources/modules/resources/claco-form/player/store/reducer.js
> [ClacoFormBundle] fixes entries filters

- main/core/API/Serializer/Resource/ResourceEvaluationSerializer.php
> fixes #6011

- main/app/Resources/translations/actions.en.json
- main/app/Resources/translations/actions.fr.json
- main/core/Resources/modules/tools/community/pending/components/tab.jsx
- main/core/Security/Voter/UserVoter.php
| Fixed issues | https://github.com/claroline/Distribution/issues/6497
> [CoreBundle] fixes workspace role granting rights

- plugin/agenda/Resources/modules/data/components/event-card.jsx
> [AgendaBundle] fixes #6511

- main/core/Controller/APINew/Resource/ResourceNodeController.php
- main/core/Manager/ResourceManager.php
> [CoreBundle] fixes #6509

- main/app/Resources/modules/data/types/validators.js
- plugin/exo/Resources/modules/items/cloze/index.js
- plugin/exo/Resources/modules/items/index.js
- plugin/exo/Resources/modules/items/open/index.js
- plugin/exo/Resources/modules/items/pair/index.js
- plugin/exo/Resources/modules/items/set/index.js
- plugin/exo/Resources/modules/items/validation.js
- plugin/exo/Resources/modules/resources/quiz/editor/validation.js
- plugin/exo/Resources/modules/utils/keywords.js
> [ExoBundle] fixes editor validation

- main/core/Resources/modules/data/types/organization/components/cell.jsx
- main/core/Resources/modules/data/types/organization/index.js
- main/core/Resources/modules/data/types/user/index.js
> [CoreBundle] enhances data types components

- main/core/Manager/ToolManager.php
> [CoreBundle] displays desktop tool if not configured

- main/app/API/Crud.php
- main/app/Controller/AbstractCrudController.php
- main/core/API/Crud/Resource/ResourceNodeCrud.php
- main/core/API/Serializer/Resource/ResourceNodeSerializer.php
- main/core/Entity/Resource/ResourceNode.php
- main/core/Listener/Resource/ResourceListener.php
- main/core/Manager/Resource/ResourceActionManager.php
- main/core/Manager/ResourceManager.php
- plugin/path/Listener/Resource/PathListener.php
> fixes resources copy

- main/app/Resources/modules/content/form/containers/form.jsx
- main/app/Resources/modules/dom/scroll.js
- main/app/Resources/modules/input/components/slider.jsx
- main/app/Resources/modules/layout/sections/administration/components/menu.jsx
- main/app/Resources/modules/layout/sections/administration/containers/menu.jsx
- main/app/Resources/modules/layout/sections/desktop/components/menu.jsx
- main/app/Resources/modules/layout/sections/desktop/containers/menu.jsx
- main/app/Resources/translations/actions.en.json
- main/app/Resources/translations/actions.fr.json
- main/core/API/Transfer/Action/User/Create.php
- main/core/API/Transfer/Action/User/Delete.php
- main/core/API/Transfer/Action/User/Update.php
- main/core/Manager/LocaleManager.php
- main/core/Resources/less/layout/components/index.less
- main/core/Resources/less/layout/components/sliders.less
- main/core/Resources/less/layout/form/index.less
- main/core/Resources/modules/administration/index.js
- main/core/Resources/modules/desktop/actions/impersonation.js
- main/core/Resources/modules/desktop/index.js
- main/core/Resources/modules/plugin.js
- main/core/Resources/modules/widget/types/resource/components/widget.jsx
- main/core/Resources/translations/platform.en.json
- main/core/Resources/translations/platform.fr.json
- plugin/scorm/Resources/modules/resources/scorm/components/creation.jsx
> [CoreBundle] enhances and fixes

- main/app/Resources/modules/input/components/slider.jsx
- main/core/Controller/AdministrationController.php
- main/core/Controller/DesktopController.php
- main/core/Controller/WorkspaceController.php
- main/core/Resources/modules/data/types/groups/components/input.jsx
- main/core/Resources/modules/data/types/user/components/display.jsx
- main/core/Resources/modules/tool/store/actions.js
- main/core/Resources/modules/tool/store/reducer.js
- main/core/Resources/modules/tool/store/selectors.js
- main/core/Resources/translations/platform.en.json
- main/core/Resources/translations/platform.fr.json
- plugin/open-badge/Listener/ToolListener.php
- plugin/open-badge/Resources/modules/tools/badges/components/tool.jsx
- plugin/open-badge/Resources/modules/tools/badges/containers/tool.jsx
> [BadgeBundle] fixes rights check

- main/app/Resources/modules/data/types/validators.js
- main/app/Resources/modules/security/login/components/form.jsx
> fixes email input validation

- main/core/API/Serializer/Widget/WidgetInstanceSerializer.php
- main/core/Resources/modules/widget/player/components/widget.jsx
- main/core/Resources/translations/platform.en.json
- main/core/Resources/translations/platform.fr.json
> fixes widgets

- main/app/Controller/AbstractCrudController.php
- main/app/Resources/modules/input/components/slider.jsx
- main/app/Resources/modules/modals/form/components/data.jsx
- main/core/Resources/less/content/loader.less
- main/core/Resources/less/layout/components/sliders.less
- main/core/Resources/less/themes/default/variables.less
- main/core/Resources/modules/resources/file/store/actions.js
- main/core/Resources/modules/tool/containers/main.jsx
- main/core/Resources/modules/widget/player/components/widget.jsx
> multiple enhancements and fixes from dev

- main/app/Resources/modules/dom/mount.js
- main/app/Resources/modules/input/components/slider.jsx
- main/app/Resources/modules/layout/sections/desktop/store/actions.js
- main/app/Resources/modules/layout/sections/desktop/store/reducer.js
- main/app/Resources/modules/plugin.js
- main/core/Controller/DesktopController.php
- main/core/Resources/modules/plugin.js
- main/core/Resources/server/packages/index.js
> enhances from dev

- main/app/API/FinderProvider.php
- main/core/Resources/modules/administration/community/role/components/role-list.jsx
- main/core/Resources/modules/tools/community/role/components/role.jsx
- main/core/Resources/modules/tools/community/role/components/roles.jsx
- plugin/team/Resources/modules/tools/team/components/editor.jsx
> fixes from dev

- main/app/Resources/modules/modals/connection/components/modal.jsx
- main/core/Resources/less/layout/components/buttons.less
- main/core/Resources/less/layout/components/popovers.less
- main/core/Resources/less/mixins.less
> fixes some styles

- main/app/Resources/modules/intl/index.js
- main/app/Resources/modules/modals/connection/components/modal.jsx
- main/app/Resources/modules/modals/connection/containers/modal.jsx
- main/core/API/Serializer/Platform/ConnectionMessageSerializer.php
- main/core/Entity/ConnectionMessage/Slide.php
- main/core/Migrations/pdo_mysql/Version20200219085345.php
- main/core/Resources/config/services/serializer.yml
- main/core/Resources/modules/administration/parameters/message/components/message.jsx
- main/core/Resources/modules/administration/parameters/modals/slide/components/modal.jsx
- main/core/Resources/modules/administration/parameters/prop-types.js
- main/core/Resources/translations/platform.en.json
- main/core/Resources/translations/platform.fr.json
> [CoreBundle] adds shortcuts in connection messages

- main/core/Library/Installation/Updater/Updater120532.php
> [CoreBundle] fixes platform URL format

- main/app/Controller/AbstractCrudController.php
> fixes CRUD options

- main/core/Resources/less/layout/components/carousel.less
- plugin/slideshow/Entity/Resource/Slide.php
- plugin/slideshow/Migrations/pdo_mysql/Version20200224142150.php
- plugin/slideshow/Resources/config/services.yml
- plugin/slideshow/Resources/config/services/controller.yml
- plugin/slideshow/Resources/modules/resources/slideshow/editor/modals/slide/components/modal.jsx
- plugin/slideshow/Resources/modules/resources/slideshow/player/components/player.jsx
- plugin/slideshow/Resources/modules/resources/slideshow/prop-types.js
- plugin/slideshow/Resources/styles/resources/slideshow.less
- plugin/slideshow/Serializer/SlideshowSerializer.php
> [SlideshowBundle] adds slide color and fixes player ui

- package.json
- plugin/claco-form/Resources/modules/resources/claco-form/player/components/entry-form.jsx
> [ClacoFormBundle] fixes template use

- plugin/message/Installation/AdditionalInstaller.php
- plugin/message/Installation/Updater/Updater120534.php
> [MessageBundle] pushes new messages widget in header

- main/app/Resources/translations/actions.fr.json
- main/core/DataFixtures/PostInstall/Data/LoadDesktopHomeData.php
- main/core/Resources/modules/administration/parameters/modals/slide/components/modal.jsx
> connection messages & default home

- main/app/Resources/modules/data/types/fields/modals/parameters/components/parameters.jsx
- plugin/claco-form/Controller/ClacoFormController.php
- plugin/claco-form/Resources/modules/resources/claco-form/components/menu.jsx
- plugin/claco-form/Resources/modules/resources/claco-form/components/resource.jsx
- plugin/claco-form/Resources/modules/resources/claco-form/containers/resource.jsx
- plugin/claco-form/Resources/modules/resources/claco-form/index.js
> [ClacoFormBundle] more fixes on resource

- main/app/Resources/modules/content/form/components/form.jsx
- main/app/Resources/modules/content/list/components/data.jsx
- main/core/API/Crud/WorkspaceCrud.php
- main/core/API/Serializer/Resource/ResourceNodeSerializer.php
- main/core/Command/DatabaseIntegrity/RightsIntegrityCheckerCommand.php
- main/core/Command/DatabaseIntegrity/RoleIntegrityCheckerCommand.php
- main/core/Manager/Workspace/Transfer/Tools/ResourceManager.php
- main/core/Manager/Workspace/TransferManager.php
- main/core/Manager/Workspace/WorkspaceManager.php
> [CoreBundle] fixes resource rights on ws creation

- main/app/API/Options.php
- main/core/API/Crud/User/UserCrud.php
- main/core/API/Transfer/Action/User/Create.php
- main/core/Controller/APINew/User/UserController.php
- main/core/Library/Security/ExternalAuthenticator.php
- main/core/Manager/UserManager.php
- plugin/competency/DataFixtures/Batch/UserFixture.php
> [CoreBundle] allows to disable user send mail from api

- main/app/Resources/modules/content/form/components/fieldset.jsx
- main/app/Resources/modules/data/components/input.jsx
- main/app/Resources/modules/data/types/address/components/display.jsx
- main/app/Resources/modules/data/types/address/components/group.jsx
- main/app/Resources/modules/data/types/address/components/input.jsx
- main/app/Resources/modules/data/types/address/index.js
- main/app/Resources/modules/data/types/address/prop-types.js
- main/app/Resources/modules/data/types/choice/index.js
- main/app/Resources/modules/layout/header/components/user.jsx
- main/app/Resources/modules/plugin.js
- main/core/API/Crud/User/UserCrud.php
- main/core/API/Serializer/User/UserSerializer.php
- main/core/Entity/User.php
- main/core/Manager/UserManager.php
- main/core/Migrations/pdo_mysql/Version20200402090422.php
- main/core/Resources/less/data/address.less
- main/core/Resources/less/data/index.less
- main/core/Resources/translations/platform.en.json
- main/core/Resources/translations/platform.fr.json
> enhances core from dev

- main/app/Resources/modules/security/password/reset/components/reset.jsx
- main/core/Resources/translations/platform.en.json
- main/core/Resources/translations/platform.fr.json
> [CoreBundle] adds help message on reset password page

- main/app/API/Transfer/Action/AbstractCreateAction.php
- main/core/API/Transfer/Action/Directory/Create.php
- main/core/API/Transfer/Action/Directory/CreateOrUpdate.php
- main/core/API/Transfer/Action/Facet/Create.php
- main/core/API/Transfer/Action/Group/AddUser.php
- main/core/API/Transfer/Action/Group/RemoveUser.php
- main/core/Resources/config/services/transfer.yml
- main/core/Resources/translations/transfer.en.json
- main/core/Resources/translations/transfer.fr.json
> [CoreBundle] fixes transfer documentation

- main/core/API/Transfer/Action/Directory/Create.php
- main/core/API/Transfer/Action/Directory/CreateOrUpdate.php
> [CoreBundle] fixes import directory

- main/app/Resources/modules/intl/date/index.js
- main/core/Resources/modules/layout/calendar/components/calendar.jsx
- plugin/exo/Entity/ItemType/OpenQuestion.php
- plugin/exo/Library/Item/Definition/WordsDefinition.php
- plugin/exo/Migrations/pdo_mysql/Version20200422072816.php
- plugin/exo/Resources/modules/components/keywords.jsx
- plugin/exo/Resources/modules/items/words/components/editor.jsx
- plugin/exo/Resources/modules/items/words/components/feedback.jsx
- plugin/exo/Resources/modules/items/words/components/highlight.jsx
- plugin/exo/Resources/modules/items/words/components/paper.jsx
- plugin/exo/Resources/modules/items/words/components/player.jsx
- plugin/exo/Resources/modules/items/words/prop-types.js
- plugin/exo/Resources/modules/items/words/utils.js
- plugin/exo/Resources/styles/items/components/keywords.less
- plugin/exo/Serializer/Item/Type/OpenQuestionSerializer.php
- plugin/exo/Serializer/Item/Type/WordsQuestionSerializer.php
> [ExoBundle] adds date answer for words question

- main/app/Controller/RequestDecoderTrait.php
- main/app/Persistence/ObjectManager.php
- main/core/Controller/APINew/Workspace/RegistrationController.php
> [CoreBundle] fixes workspace api

- plugin/exo/Entity/Exercise.php
- plugin/exo/Migrations/pdo_mysql/Version20200422153656.php
- plugin/exo/Resources/modules/quiz/player/components/nav-bar.jsx
- plugin/exo/Resources/modules/quiz/player/components/player.jsx
- plugin/exo/Resources/modules/quiz/player/selectors.js
- plugin/exo/Resources/modules/resources/quiz/editor/components/parameters.jsx
- plugin/exo/Resources/translations/quiz.en.json
- plugin/exo/Resources/translations/quiz.fr.json
- plugin/exo/Serializer/ExerciseSerializer.php
> [CoreBundle] allows to hide back btn in player

- main/core/Command/Logs/LogsFetcherCommand.php
- main/core/Manager/LogManager.php
- main/core/Resources/config/services/manager.yml
> [CoreBundle] fixes export logs command

- main/app/API/Crud.php
> [CoreBundle] allows to disable perm checks in CRUD

- main/core/API/Serializer/User/UserSerializer.php
> [CoreBundle] allows to set user uuid through api

- plugin/exo/Controller/PaperController.php
> [ExoBundle] fixes results access

- plugin/exo/Resources/modules/quiz/player/actions.js
> [ExoBundle] fixes paper access after attempt

- plugin/exo/Command/ComputeScoresCommand.php
Usage :
```
$ php app/console claroline:quiz:scores RESOURCE_NODE_ID
```
> [ExoBundle] adds a command to recompute scores for a quiz papers

- main/core/Resources/modules/tools/community/user/containers/tab.jsx
> [CoreBundle] fixes user creation in community

- plugin/exo/Library/Item/Definition/AbstractDefinition.php
> [ExoBundle] fixes answers csv columns names

- plugin/exo/Resources/modules/quiz/player/actions.js
- plugin/exo/Resources/modules/quiz/player/components/attempt-end.jsx
- plugin/exo/Resources/modules/quiz/player/components/player.jsx
> fixes #6696

- composer.json
- main/core/API/Serializer/ParametersSerializer.php
- main/core/Library/Configuration/PlatformConfigurationHandler.php
- main/core/Library/Installation/Updater/Updater100000.php
- main/core/Library/Installation/Updater/Updater120118.php
- main/core/Manager/Workspace/WorkspaceManager.php
- main/core/Resources/config/parameters.yml
- main/core/Resources/config/services/manager.yml
- main/core/Resources/config/services/serializer.yml
- main/kernel/ClarolineKernelBundle.php
- main/kernel/Manager/BundleManager.php
- plugin/blog/Resources/config/services/services.yml
- plugin/claco-form/Controller/ClacoFormController.php
- plugin/claco-form/Resources/config/services/controller.yml
- plugin/claco-form/Resources/views/claco_form/entries_export.html.twig
- plugin/drop-zone/Entity/Dropzone.php
- plugin/drop-zone/Manager/DropzoneManager.php
- plugin/drop-zone/Resources/config/services/services/manager.yml
- plugin/open-badge/Manager/OpenBadgeManager.php
- plugin/open-badge/Resources/config/services/manager.yml
> fixes test environment

- plugin/announcement/Finder/AnnouncementFinder.php
- plugin/blog/Finder/PostFinder.php
- plugin/forum/Finder/MessageFinder.php
> fixes data sources

- main/app/Controller/Platform/ClientController.php
- main/app/Resources/config/services/controller.yml
- main/core/Listener/ViewAsListener.php
- main/core/Resources/config/suggested/sensio_framework_extra.yml
- plugin/bibliography/Controller/API/BookReferenceConfigurationController.php
> optimizes performances

- main/core/API/Finder/Tool/ToolFinder.php
- main/core/Listener/DataSource/ToolSource.php
> [CoreBundle] fixes tool data source

- main/core/API/Finder/Tool/ToolFinder.php
- main/core/Listener/DataSource/ToolSource.php
- main/core/Resources/modules/data/sources/tools.js
> [CoreBundle] fixes tool finder filters

- plugin/exo/Resources/modules/quiz/player/actions.js
> fixes #6722

- main/app/Resources/modules/content/form/store/actions.js
- main/app/Resources/modules/intl/date/index.js
- main/app/Resources/modules/layout/sections/home/components/disabled.jsx
- main/app/Resources/modules/layout/store/selectors.js
- main/core/Library/Installation/AdditionalInstaller.php
- main/core/Library/Installation/Updater/Updater120545.php
- main/core/Resources/modules/administration/scheduled-task/store/actions.js
- main/core/Resources/modules/layout/calendar/components/calendar.jsx
- main/core/Resources/modules/layout/chart/components/axis.jsx
- main/core/Resources/modules/layout/gauge/components/timer.jsx
- plugin/agenda/Installation/AdditionalInstaller.php
- plugin/agenda/Installation/Updater/Updater050002.php
- plugin/agenda/Installation/Updater/Updater120545.php
- plugin/announcement/ClarolineAnnouncementBundle.php
- plugin/announcement/Entity/Announcement.php
- plugin/announcement/Installation/AdditionalInstaller.php
- plugin/announcement/Installation/Updater/Updater120545.php
- plugin/blog/Installation/AdditionalInstaller.php
- plugin/blog/Installation/Updater/Updater120545.php
- plugin/drop-zone/Installation/Updater/Updater120545.php
- plugin/drop-zone/Resources/modules/resources/dropzone/store/selectors.js
- plugin/exo/Installation/AdditionalInstaller.php
- plugin/exo/Installation/Updater/Updater120545.php
- plugin/exo/Resources/modules/resources/quiz/papers/restrictions.js
- plugin/exo/Resources/modules/resources/quiz/player/attempt.js
- plugin/forum/Resources/modules/resources/forum/player/store/actions.js
- plugin/message/Resources/modules/tools/messaging/components/message.jsx
> fixes timezone management

- plugin/blog/Installation/AdditionalInstaller.php
- plugin/blog/Installation/Updater/Updater120545.php
> [BlogBundle] fixes Updater

- .travis.yml
- main/app/API/Options.php
- main/app/Resources/modules/data/types/password/components/input.jsx
- main/core/API/Crud/WorkspaceCrud.php
- main/core/API/Transfer/Action/Workspace/Create.php
- main/core/Controller/APINew/Workspace/WorkspaceController.php
- main/core/Controller/WorkspaceController.php
- main/core/Manager/Resource/ResourceRestrictionsManager.php
- main/core/Manager/Workspace/TransferManager.php
- main/core/Manager/Workspace/WorkspaceManager.php
- main/core/Resources/modules/resource/components/restrictions.jsx
- main/core/Resources/modules/workspace/actions/delete.js
- main/core/Resources/translations/actions.en.json
- main/core/Resources/translations/actions.fr.json
- main/core/Resources/translations/resource.en.json
- main/core/Resources/translations/resource.fr.json
- plugin/analytics/Resources/modules/charts/actions/components/chart.jsx
- plugin/drop-zone/Installation/Updater/Updater120545.php
- plugin/drop-zone/Resources/modules/resources/dropzone/components/documents.jsx
- plugin/drop-zone/Resources/modules/resources/dropzone/player/components/my-drop.jsx
> [DropzoneBundle] fixes dates

- main/app/Resources/modules/security/login/containers/form.jsx
- main/app/Resources/translations/security.en.json
- main/app/Resources/translations/security.fr.json
- plugin/lesson/Controller/Resource/LessonController.php
- plugin/lesson/Entity/Lesson.php
- plugin/lesson/Repository/ChapterRepository.php
- plugin/lesson/Resources/modules/resources/lesson/components/menu.jsx
- plugin/lesson/Resources/modules/resources/lesson/containers/menu.jsx
- plugin/lesson/Resources/modules/resources/lesson/store/actions.js
- plugin/lesson/Resources/styles/resources/pdf.less
- plugin/lesson/Resources/views/lesson/lessonChapters.pdf.twig
- plugin/lesson/Resources/views/lesson/lessonContents.pdf.twig
- plugin/lesson/Resources/views/lesson/open.pdf.twig
> enhancements

- main/core/API/Serializer/User/UserSerializer.php
- main/core/Resources/config/config.yml
- main/core/Resources/modules/user/components/page.jsx
- main/core/Resources/modules/user/profile/components/main.jsx
- main/core/Resources/modules/user/profile/containers/main.jsx
- plugin/analytics/Resources/modules/resource/actions/dashboard.js
- plugin/analytics/Resources/modules/user/actions/dashboard.js
- plugin/analytics/Resources/translations/actions.en.json
- plugin/analytics/Resources/translations/actions.fr.json
> [CoreBundle] adds community right for opening user tracking

- main/core/Repository/ResourceNodeRepository.php
- main/core/Tests/Database/Repository/Tool/ToolRepositoryTest.php
- main/migration/Generator/Writer.php
- main/migration/Tests/Generator/WriterTest.php
- Fixes issue on windows test env.
- Fixes issue when custom plugins are installed in test env.
> fixes tests

- main/core/API/Serializer/Platform/ClientSerializer.php
- main/core/Controller/APINew/SwaggerController.php
- main/core/Library/Configuration/PlatformDefaults.php
- main/core/Library/Installation/AdditionalInstaller.php
- main/core/Library/Installation/Updater/Updater120547.php
- main/core/Resources/config/services/controller.yml
- main/core/Resources/modules/data/sources/resources.js
- main/core/Resources/modules/data/types/resource/components/filter.jsx
- main/core/Resources/modules/user/profile/components/main.jsx
- main/core/Resources/modules/user/profile/player/components/main.jsx
- main/core/Resources/styles/swagger/index.less
- package.json
- plugin/claco-form/Controller/ClacoFormController.php
- plugin/drop-zone/Resources/translations/resource.fr.json
- plugin/favourite/Resources/modules/header/favourites/components/menu.jsx
- plugin/favourite/Resources/modules/header/favourites/store/actions.js
- plugin/lesson/Controller/Resource/LessonController.php
- plugin/lesson/Resources/config/services/controller.yml
- plugin/lesson/Resources/modules/resources/lesson/components/menu.jsx
- plugin/lesson/Resources/modules/resources/lesson/components/resource.jsx
> fixes from debug

- main/core/Resources/modules/modals/templates/components/modal.jsx
- main/core/Resources/modules/modals/templates/containers/modal.jsx
> [CoreBundle] allows default filters in template picker

- main/core/Library/Installation/Updater/Updater120547.php
> [CoreBundle] fixes resources widget updater

- plugin/lesson/Resources/views/lesson/open.pdf.twig
> [LessonBundle] fixes PDF export

- main/app/Resources/modules/layout/sections/administration/components/main.jsx
- main/app/Resources/modules/layout/sections/administration/containers/main.jsx
- main/app/Resources/modules/layout/sections/desktop/components/main.jsx
- main/app/Resources/modules/layout/sections/desktop/containers/main.jsx
- main/app/Resources/translations/administration.en.json
- main/app/Resources/translations/administration.fr.json
- main/app/Resources/translations/desktop.en.json
- main/app/Resources/translations/desktop.fr.json
> fixes double loading on desktop and admin open

- main/app/Resources/modules/action/components/toolbar.jsx
- main/core/API/Finder/Log/LogFinder.php
- main/core/Controller/APINew/User/RoleController.php
- main/core/Manager/LogManager.php
- main/core/Repository/UserRepository.php
- main/core/Resources/config/services/controller.yml
- main/core/Resources/modules/administration/community/role/components/role-tab.jsx
- main/core/Resources/modules/administration/community/role/components/role.jsx
- main/core/Resources/modules/administration/community/role/containers/role.jsx
- main/core/Resources/modules/administration/community/role/store/actions.js
- main/core/Resources/translations/platform.en.json
- main/core/Resources/translations/platform.fr.json
- main/core/Resources/translations/user.en.json
- main/core/Resources/translations/user.fr.json
- plugin/analytics/Resources/modules/tools/dashboard/components/activity.jsx
- plugin/analytics/Resources/modules/tools/dashboard/components/overview.jsx
> [CoreBundle] adds some analytics data on role details

- main/app/Resources/modules/content/components/help.jsx
- plugin/exo/Resources/modules/items/words/components/player.jsx
- plugin/exo/Resources/modules/quiz/player/components/attempt-end.jsx
- plugin/exo/Resources/translations/quiz.en.json
- plugin/exo/Resources/translations/quiz.fr.json
- plugin/team/Resources/modules/tools/team/containers/tool.jsx
> [ExoBundle] enhancements

- main/core/Resources/modules/tools/community/group/components/group.jsx
- main/core/Resources/modules/tools/community/group/components/groups.jsx
- main/core/Resources/modules/tools/community/group/components/tab.jsx
- main/core/Resources/modules/tools/community/group/containers/tab.jsx
- main/core/Resources/modules/tools/community/role/components/roles.jsx
- plugin/team/Entity/Team.php
> Community fixes
