claroline/Distribution

- main/recorder/Recorder.php
This should solve this error, which came with an upgrade of composer:
> Argument 4 passed to Composer\DependencyResolver\Solver::__construct() must implement interface Composer\IO\IOInterface, none given
> Fix composer api change issue

- main/core/Manager/WorkspaceManager.php
There no point doing a `$root->getName()` before checking if $root actually exists. Also it cause issues if we want do remove a workspace and something went wrong before because the $root doesn't exists anymore.
> Fixing ws suppression if no workspace root

- main/core/Resources/scripts/lib/collect-packages.js
- main/core/Resources/scripts/lib/webpack.js
Otherwise, in the distribution, nobody can share the same entry keys in the assets.json file.
There is no name collision in the files generated, so it only removes this limitation.
> Avoid name collision with webpack.

- main/core/Manager/UserManager.php
- main/core/Repository/UserRepository.php
It's better to count the number of users directly than incrementing a counter that count the number of users for each roles... because if a user is in 2 different roles, the counter will be wrong.
> Fixing stats user count.

- main/core/Resources/views/Resource/embed/audio.html.twig
- main/core/Resources/views/Resource/embed/video.html.twig
- plugin/video-player/Controller/VideoPlayerController.php
Remove flash fallback from resource embed templates to avoid heratic media autoplay.
Also removed the comment from ```plugin/video-player/Controller/VideoPlayerController.php
```
> [CoreBundle] - Remove flash fallback from embed templates

- main/core/Library/Testing/TransactionalTestCase.php
Following [this article](http://kriswallsmith.net/post/18029585104/faster-phpunit), I can see a huge performance gain when running the test suite locally (80% faster, 500% drop in memory).
> Optimize test suite memory usage

- main/dev/Resources/travis/php-cs.php
Prevents php-cs-fixer to apply fixers blindly on binary files.
> Exclude non-php files from cs finder

- .travis.yml
- main/core/Command/CreatePluginCommand.php
- main/core/Controller/FileController.php
- main/core/Controller/WorkspaceController.php
- main/core/Library/Installation/Updater/Updater030000.php
- main/core/Library/Installation/Updater/Updater030400.php
- main/core/Library/Transfert/ConfigurationBuilders/UsersImporter.php
- main/core/Manager/ToolManager.php
- main/core/Manager/TransfertManager.php
- phpmd.xml
- plugin/collecticiel/Controller/DropController.php
- plugin/competency/Tests/Installation/AdditionalInstallerTest.php
- plugin/oauth/Manager/OauthManager.php
- plugin/scorm/Listener/Scorm2004Listener.php
This PR adds a minimal phpmd check -- only unused private methods for now -- to the travis build. The goal is to progressively add rules to:
- eliminate dead code
- eliminate problematic functions like `exit`, `eval`, `var_dump`, etc.
- limit code complexity (class/method length, dependencies)
cc @claroline/commiters
> Add phpmd to travis

- .travis.yml
- main/dev/Resources/travis/pre-composer.php
When fetching the platform dependencies on travis, the distribution build is included as a local dependency using the `path` option. This PR changes the default behaviour of that option from symlink to mirror (hard copy). Advantages:
- simplify build config
- prevent issues like [this one](https://github.com/claroline/Distribution/pull/125#issuecomment-211324433)
- enable easier caching strategies
> Mirror build repo in vendor on travis

- main/core/Controller/Administration/HomeTabController.php
The home_tabs tool doesn't exist so the check will fail for everyone who don't have the ROLE_ADMIN.
desktop_and_home exists and is probably what was intended.
> [CoreBundle] Fixing wrong admin tool check

- main/recorder/Detector/Detector.php
Removes a false positive in bundle detection, which makes all the travis builds fail:
https://travis-ci.org/claroline/Distribution/builds/129190687#L2036
> [BundleRecorder] Exclude non symfony bundle classes

- plugin/exo/Entity/Exercise.php
Set an empty string as the default value for Exercise description (because the validation schema does not allow `null` value).
> Fix default value of Exercise description

- .travis.yml
- main/dev/Resources/travis/fetch-deps.bash
This should fix build errors like this one: https://travis-ci.org/claroline/Distribution/builds/131400211#L841 (secured environment variables aren't available in PRs coming from forks).
Not sure about the `after_success` step though.
> Fix external PR detection in travis

- .travis.yml
- main/dev/Resources/travis/fetch-deps.bash
- main/dev/Resources/travis/send-preview.sh
This should allow to bypass that step effectively for PRs coming from external repositories (see #342).
> Move preview build to a separate script

- .travis.yml
- main/dev/Resources/travis/fetch-deps.bash
- main/dev/Resources/travis/send-preview.sh
Replace zip with tar.gz compression for cache and previews:
- reduce storage and bandwidth use
- preserve symlinks by default
**EDIT**: also use new bin dir location (see #365)
> Switch to tar gzip archives

- plugin/exo/Installation/AdditionalInstaller.php
- plugin/exo/Installation/Updater600200.php
C'est juste pour attirer l'attention sur les bugs que j'ai pu constater, pas pour être mergé.
- La condition dans l'installer est pas logique. Si on regarde <= 6.1 ou <= 6.999999999, ça veut dire que tant qu'on est sur la v6 l'updater se déclenchera.
- Il manque le orderStep. La j'ai fait un patch à la con avec une variable qui s'incrémente mais elle n'est pas déclarée sinon, donc la valeur 'ordre' est null et ça casse derrière.
@UJM-dev
> [ExoBundle] Updater brokens

- plugin/ldap/Manager/LdapManager.php
Changes an "or" to "||" in the LDAP Manager as recomended by Sensio Insight
> [SensioInsight] Logical operators should be avoided

- plugin/exo/Controller/Api/ExerciseController.php
- plugin/exo/Manager/PaperManager.php
- plugin/exo/Resources/public/js/angular/Paper/Controllers/PaperListCtrl.js
- plugin/exo/Resources/public/js/angular/Paper/Controllers/PaperShowCtrl.js
- plugin/exo/Resources/public/js/angular/Paper/Services/PaperService.js
- plugin/exo/Tests/Controller/Api/ExerciseControllerCommonTest.php
I think it can be improved and it requires further tests if you want to continue an attempt with a deleted question.
But at least the corrections and scores are  OK. When loading the list of papers, I also load the set of questions for each paper. Can be improved to avoid performance impact...
I create a "fake" step at the end of the step list to get the questions which are no longer in the Exercise. So in that step, the questions are ordered. But the step is not at the correct place and the questions maybe not belong to the same step (this information has been lost when deleting).
> [ExoBundle] closes #140

- main/core/Resources/modules/modal/Controller/ConfirmModalController.js
- main/core/Resources/modules/modal/Directive/ConfirmModalDirective.js
- main/core/Resources/modules/modal/Partial/confirm-modal.html
- main/core/Resources/modules/modal/README.md
- main/core/Resources/modules/modal/module.js
- main/core/Resources/translations/platform.de.yml
- main/core/Resources/translations/platform.en.yml
- main/core/Resources/translations/platform.es.yml
- main/core/Resources/translations/platform.fr.yml
Original PR was #620 but it's not needed for the 7.x.
This PR contains a new directive to simplify the usage of AngularBootstrap modal.
For now only confirm modals are managed based on ngBootbox way to do it (directives that can be appended to DOM elements).
So once this PR is merged, there will be no more need of ngBootbox (which requires jquery and bootstrap js) which is only used in Exercises.
Implementation détails : 
- I have kept the controller inside the directive definition as the directive and the controller do practically nothing.
- The design and features are very limited for now (I only do what bootbox did) and will be updated when adding alert modal and other modal types.
See README for more information about usage.
> [CoreBundle] Add confirm modal management

- plugin/exo/Services/classes/Interactions/Matching.php
- plugin/exo/Tests/Controller/Api/ExerciseControllerMatchTest.php
This commit fixes the following issue: 
https://github.com/claroline/Distribution/issues/463
Now the score set for a label is counted for each right connection.
> Fix claroline/Distribution#463 Fix scoring on match questions

- main/core/Form/ActivityType.php
- main/core/Form/DirectoryType.php
- main/core/Form/ResourceNameType.php
- main/core/Form/TextType.php
- main/core/Resources/views/Tool/workspace/resource_manager/resources.html.twig
- plugin/blog/Form/BlogType.php
- plugin/collecticiel/Form/DropzoneType.php
- plugin/dropzone/Form/DropzoneType.php
- plugin/forum/Form/ForumType.php
- plugin/path/Form/AbstractPathType.php
- plugin/result/Form/ResultType.php
- plugin/scorm/Form/ScormType.php
- plugin/survey/Form/SurveyType.php
- plugin/website/Form/WebsiteType.php
- plugin/wiki/Form/WikiType.php
Added an autofocus HTML option on the first field of each resource creation form (displayed in a bootstrap modal on the resource page of each workspace).
Added some javascript to enable autofocus if a second (or more modal) is opened without a full page reload.
> Resource creation autofocus on first field

- plugin/exo/Resources/public/js/angular/Correction/Controllers/MatchCorrectionCtrl.js
- plugin/exo/Resources/public/js/angular/Correction/Directives/MatchCorrectionDirective.js
- plugin/exo/Resources/public/js/angular/Correction/Partials/match.html
- plugin/exo/Resources/public/js/angular/Question/Partials/Type/graphic.html
- plugin/exo/Resources/translations/ujm_exo.en.yml
- plugin/exo/Resources/translations/ujm_exo.fr.yml
This PR fixes two minor issues.
On graphic questions, since the pointers are no longer shown on page load, but appear on click, it seemed important to say it in a descriptive sentence.
On match question, the correction directive wasn't loading; the problem is fixed. The correction used to show a column "your answer", which is useless because we always show it with the question directive, containing these answers.
> Exo issues fixes

- main/core/Library/Installation/OperationExecutor.php
This didn't work well ($bundle not initialized; I don't get why it worked at some point). I guess we'll wait to work on the much tolerant upgrade to fix this properly. 
It would be nice to be able to find if the plugin is already in the database but that's not the correct way to do it.
> [CoreBundle] Removing update buggy code

- main/core/Manager/WorkspaceManager.php
Currently, when creating a user, the workspace manager tries to extract the personal.zip archive into a directory called personal.zip...
> [CoreBundle] Avoid creating a tmp directory with the template filename

- plugin/path/Resources/public/js/Path/Service/PathService.js
- plugin/path/Resources/public/js/PathSummary/Controller/PathSummaryBaseCtrl.js
- plugin/path/Resources/public/js/PathSummary/Controller/PathSummaryShowCtrl.js
- plugin/path/Resources/public/js/wizards.app.js
In order to fix the #593.
In the player if no step is specified in the URL (default behavior when you open a Path), the User is sent to the last Step he has seen or the last step he has set a manual progression (done / to do / to redo).
Implementation remark : the `wizard.app.js` starts to become quite ugly. I will need to split it to a player and editor entry points as the behavior of the router is no longer the same in the 2 apps. Will require some works and tests so it will be done later.
ping @eddymarques @ptsavdar
> [PathBundle] Restart path on the last seen step

- .eslintrc.json
- .travis.yml
- package.json
See #693. 
- the check will be applied to js files within *Resources/modules/** directories
- standard used is described in https://github.com/claroline/Distribution/issues/693#issuecomment-227124134 (I've added single quotes preference and unix-style line endings as per ESLint suggestion)
Note that this PR just adds the check, it doesn't fix any actual errors. Those will have to be fixed on each modified files prior to a PR submission. 
There're currently 8000+ infractions to the standard. Most of them are indent and semi-colons issues that can be fixed automatically by ESLint using the `--fix` option. The remaining ones are mainly:
- unknown globals (ESLint requires globals to be specified explicitely to prevent leakage)
- missing import statements
- unused variables
- variables defined …
> Add ESLint check on ES6 files

- main/dev/Resources/travis/php-cs.php
See #693. @claroline/commiters, you'll have to update your editor config and/or your git hooks accordingly.
> Require array shortands and ordered use statements

- plugin/exo/Resources/public/js/angular/Exercise/Services/ExerciseService.js
When adding a Step to an Exercise, the whole definition of the created step is not set in Angular. So if you try to edit the Step meta directly after angular crash.
Not a big bug because the data are correctly saved.
> [ExoBundle] Get the step definition when added to Exercise

- main/dev/Resources/hooks/pre-commit
- main/dev/Resources/hooks/pre-commit-eslint
- main/dev/Resources/hooks/pre-commit-md
- main/dev/Resources/hooks/pre-commit-phpcs
- main/dev/Resources/hooks/pre-commit-phpmd
Depend on #735.
Reuse files from http://github.com/claroline/git-hooks and add/modify hooks to cover current constraints:
- php-cs-fixer
- phpmd
- md
- eslint
Hooks can be enabled by a simple symlink:
```
cd .git/hooks
ln -s ../../main/dev/Resources/hooks/pre-commit
```
**NOTE**: currently hooks won't be triggered with the `--amend` option
cc @claroline/commiters
> [DevBundle] Add git pre-commit hooks

- .travis.yml
- phpmd.xml
Follows claroline/Claroline#892. Fixes #286 and #693.
- enable PHPMD rule disallowing unused local variables or private fields
- add new MD linter tool to reject problematic stuff often seen in PRs, like loose comparisons, commented code, etc. (complete list [here](http://github.com/stefk/md/issues/1))
cc @claroline/commiters
> Add linter pass + phpmd rule in .travis

- plugin/exo/Controller/InteractionGraphicController.php
- plugin/exo/Controller/InteractionHoleController.php
- plugin/exo/Controller/InteractionMatchingController.php
- plugin/exo/Controller/InteractionOpenController.php
- plugin/exo/Controller/InteractionQCMController.php
- plugin/exo/Entity/Question.php
- plugin/exo/Form/InteractionGraphicHandler.php
- plugin/exo/Form/InteractionHoleHandler.php
- plugin/exo/Form/InteractionMatchingHandler.php
- plugin/exo/Form/InteractionOpenHandler.php
- plugin/exo/Form/InteractionQCMHandler.php
- plugin/exo/Form/QuestionHandler.php
- plugin/exo/Resources/config/services.yml
- plugin/exo/Resources/views/Question/search.html.twig
- plugin/exo/Services/classes/CategoryService.php
This PR fixes the saring feature of the Bank which was buggy in the last version.
It also fixes the #737. 
I've just made the existing code work, but the feature seems a little weird to me : 
The categories are specific to a User. 
If you edit a question which have been shared with you it loads the list of your categories.
So the previous category doesn't exist (that's the origin of the original bug). 
In this case, the implementation replaces the original category by a default one linked to the current User.
The weird part is it overrides the original categorization made by the User who have shared the question.
As we will need to rewrite the Bank in Angular for the 16.09, I have kept it but IMHO we will need to rethink this part.
> [ExoBundle] Fix question sharing and categories management

- plugin/exo/Entity/ObjectQuestion.php
- plugin/exo/Entity/Question.php
- plugin/exo/Manager/QuestionManager.php
- plugin/exo/Resources/modules/question/Partials/show.html
- plugin/exo/Resources/translations/ujm_sequence.en.yml
- plugin/exo/Resources/translations/ujm_sequence.fr.yml
This adds some fields we used in V5 at innovalangues.
The fields are set as follow:
- Functional instruction is set on the "description" field.
- Object of the question uses the ObjectQuestion entity, refering to a question and a resourceNode.
- Pedagogic instruction is set on the "specification" field.
- Complementary information is set on the "supplementary" field.
This PR doesn't update the editor in order to fill these fields, it only allows to show existing data in the player.
> Exo question add fields

- main/core/Resources/modules/jquery/index.js
- main/core/Resources/scripts/lib/webpack.js
- package.json
Related to #734. Ideally when writing js modules, we should require everything needed through imports statements. However, we are currently stuck with a global instance of jquery injected via a script tag. Rather than allowing the use of this implicit global, this PR makes it available through the module system, so that:
- modules that consume jquery are correctly written even if jquery is not really managed by webpack
- when we're ready to remove the script tag or if we find a better config, nothing must be changed in the modules themselves
- eslint is happy
The PR also allows jquery ui modules to be loaded correctly.
**TLDR**:
```js
import $ from 'jquery'
import 'jquery-ui/ui/draggable'
import 'jquery-ui/ui/droppable'
$('#foo').draggable()
$('.bar').droppable()
```
> Allow jquery and jquery-ui to be required through imports

- plugin/exo/Resources/modules/correction/Controllers/ClozeCorrectionCtrl.js
- plugin/exo/Resources/modules/question/Controllers/Type/ClozeQuestionCtrl.js
- plugin/exo/Resources/modules/question/Services/Type/ClozeQuestionService.js
This PR fixes the following issues:
https://github.com/claroline/Distribution/issues/807
https://github.com/claroline/Distribution/issues/809
On the editor, we can set multiple right answers for one hole, that will both be valid on the correction. But this case was not treated in the immediate feedbacks on formative exercise, in player mode. This PR fixes this.
> [ExoBundle] Fix on formative cloze questions

- plugin/exo/Resources/less/question/type/match.less
- plugin/exo/Resources/modules/question/Partials/Type/match.html
- Add bootstrap classes in match questions for proper display on mobile screens.
- Increase size of img / video in match questions. it's 200px instead of 110px. (@Gatomlo I don't know if it will be sufficient for you, but I can't increase the size more without sacrifice rendering on small screens).
We will need to wait the new editor planned for the 16.09 for a better management of each resource type (for now, even the zoom feature of "to pair" questions doesn't work well with images).
> [ExoBundle] Improves player rendering

- main/core/Entity/User.php
- main/core/Resources/translations/platform.en.yml
- main/core/Resources/translations/platform.fr.yml
- main/core/Validator/Constraints/CsvUserValidator.php
- main/core/Validator/Constraints/UsernameValidator.php
Only the translation files and the UsernameValidator were changed. Others are checkstyles.
Fix #873
> [CoreBundle] Can't use already used email as a username.

- main/core/Library/Transfert/ConfigurationBuilders/Tools/ResourceManagerImporter.php
This should fix #877 
Method `getResourceElement`was changed.
> [CoreBundle] Fixing rich text parsing if node has no workspace.

- .travis.yml
This has been done on the master branch but not on the 7.x. 3Go aren't enough for composer... That explains #903, #904, #905, #906, #907, #908 and #909 build failures.
> Raise php memory limit on travis (7.x)

- main/core/Resources/views/layout.html.twig
Certaines configurations de serveur empêchent symfony2 de récupérer le nom de domaine facilement (si des proxy sont utilisés).
Ici on bypass symfony en allant récupérer le nom de domaine depuis la config s'il existe (et comme ça, plus de problème).
> [CoreBundle] AssetPath updated (uses the config domain name)

- plugin/path/Resources/less/summary.less
- plugin/path/Resources/public/js/PathSummary/Partial/show.html
If there is a lot of steps, the bottom of the summary is hidden.
> [PathBundle] Fixes bug in summary styles

- plugin/path/EventListener/Resource/PathListener.php
- plugin/path/Installation/AdditionalInstaller.php
- plugin/path/Installation/Updater/Updater070100.php
- plugin/path/Manager/PublishingManager.php
- plugin/path/Manager/StepManager.php
This PR attempts to fix 2 bugs in Path : 
- The last version of the Angular UI get the ID of the path from the JSON structure, but for old path this property was not set.
- The copy didn't check if the resources (primary & secondary) exist, so if one is deleted there is an error. Now, the deleted resource is deleted in the structure of the copy.
> [PathBundle] manages deleted resources + add id in structure

- main/core/Manager/ResourceManager.php
$event isn't always defined so this is the monkey patch.
Maybe the $node->setActive() block should be in the `if ($node->getClass() !== 'Claroline\CoreBundle\Entity\Resource\ResourceShortcut') {`condition. I don't know.
> [CoreBundle] event soft delete

- main/core/Resources/views/Workspace/layout.html.twig
- In some cases, the iframe content height can't be determined at the right time (with SCORM, for example). The loop will now ignore this situation.
- In some cases, an empty iframe (with no resource attached) occupies space on screen anyway. It is now hidden if empty.
> [PathBundle] Fixes for resource iframe in PathBundle

- main/core/Manager/ResourceManager.php
In production, copying a broken resource will just do nothing and return null with this fix.
I had an issue where a document from a dropzone/collecticiel wasn't removed properly and broke the workspace creation through a model (but copying the directory containing the resource would have the same issue).
> [CoreBundle] resource copy less string

- main/core/Resources/less/layout.less
The property `filter` is not supported in many browser.
It has been replaced by `opacity: 0.4`.
The value can be discussed.
> [ResourceManager] fixes non standard style for unpublished resource 

- plugin/path/Resources/modules/path/Controller/PathEditCtrl.js
If you modify a path after publishing it, the save button was never enabled.
> [PathBundle] fixes save button always disabled after publish

- main/core/Resources/scripts/lib/webpack.js
- package.json
The image loader only copies the original into the `dist` directory and return an URL to this file.
The url loader includes the image directly into the JS file (base64 encoded based on what I've seen). This is more convenient.
> [CoreBundle] replaces webpack img loader by url loader

- plugin/exo/Resources/modules/question/Services/Type/GraphicQuestionService.js
- plugin/exo/Resources/modules/question/Services/Type/MatchQuestionService.js
- plugin/exo/Resources/modules/question/Services/Type/OpenQuestionService.js
Some parts of the code currently assume that a `solution` property is always present on `question` objects, leading to "xyz is not defined" errors and eventually breaking whole exercises.
> [ExoBundle] Fix score computation when no solutions are given

- plugin/formula/Resources/views/Formula/plugin.js.html.twig
It seems that the `NodeChange` event triggered at initialization time is also applied to comment nodes, leading to an "undefined" error on `className` access when the original html value contains comments.
> [FormulaBundle] Exclude non element nodes from inspection

- main/core/Manager/UserManager.php
Changed control for 'ROLE_ADMIN' from 
``` $this->roleManager->getRoleByUserAndRoleName($user, 'ROLE_ADMIN');``` 
to just ``` $user->hasRole('ROLE_ADMIN') ```
This way even if someone acquires the ROLE_ADMIN through a group he's enrolled in, he gets the same rights as the rest of the admin users.
> Fixed check for ROLE_ADMIN

- plugin/exo/Tests/Transfer/Json/ValidatorTest.php
The recent changes in `json-quiz/json-quiz` have broken the ExoBundle tests.
This is needed in order to fix the travis build.
> [ExoBundle] fixes path to tests data

- plugin/website/Resources/views/Website/Edit/banner_footer_options.html.twig
Editor wouldn't show in banner and footer even after "show editor" button was clicked. This fixes the issue.
> Fixed website banner/footer editor not showing problem

- main/core/Repository/ResourceNodeRepository.php
Individual resource nodes can be retrieved either by id or guid. The problem is the current query uses a disjunction with the same bound parameter in both cases, although the corresponding column types are different (integer vs string). This causes an implicit cast by MySQL, which can lead to surprising results and eventually hard-to-track bugs:
```sql
SELECT name, id, guid FROM claro_resource_node
WHERE id = '6FCB9336-7338-442C-B400-9E6A103422F2' OR guid = '6FCB9336-7338-442C-B400-9E6A103422F2'
```
|name	|id	|guid
|-------------|-----|-----------------
|Ex 1	|6	|4107AC6F-9082-4257-A0CD-89734558BD26
|Ex 2	|19	|6FCB9336-7338-442C-B400-9E6A103422F2
...
This PR simply splits the …
> [CoreBundle] Avoid mysql implicit cast

- composer.json
It prevents twig/twig from updating to version 1.25.0 which generates compatibility issues
> Locks twig version to v1.24.2

- plugin/video-player/Resources/views/player.html.twig
| Fixed tickets | #1181 
This fixes the n°1181 issue. There was no buttons on the video player, which was confusing, in particular when playing an audio file.
> Add controls on audio/video player

- composer.json
`mbstring` is already used in many places in the current codebase. This PR just makes the dependency explicit.
> Add mbstring to required extensions

- main/core/Resources/translations/platform.en.yml
- main/core/Resources/translations/platform.fr.yml
- main/core/Resources/views/Widget/desktopWidgetMyWorkspaces.html.twig
- main/core/Resources/views/Widget/displayMyWorkspacesWidget.html.twig
| Fixed tickets | #1287 
When an user had a role in a workspace but had access to no tool, the workspace appeared in the "my workspaces" widget but it was impossible to click on the link.
> [CoreBundle] Fixes inacessible links in my workspaces widget. Closes #1287

- plugin/cursus/Command/RemoveCoursesCommand.php
- plugin/cursus/Manager/CursusManager.php
- plugin/cursus/Repository/CourseRepository.php
The command delete all courses that are not linked to a cursus. The related sessions and associated workspaces are also deleted.
> [CursusBundle] Adds a command to delete all courses that are not associated to a cursus

- main/core/Command/Import/CreateUserFromCsvCommand.php
When run from a php script triggered by a bash one, the output isn't visible otherwise.
ie:
myscript.php
```
...
php app/console mycommand
....
```
mybash.sh
```
...
php myscript.php
...
```
This PR fixes it (better logging support then).
> [CoreBundle] Updating user logger from csv.

- main/core/Manager/WorkspaceManager.php
- main/core/Manager/WorkspaceModelManager.php
| Fixed tickets | #1278 
When creating a workspace from a model the following options are now copied too :
- The workspace options (background color, hide tool menu option, hide breadcrumbs option)
- The color of the home tabs
- The text color of a widget
> [CoreBundle] Copies several options when creating workspace from a model

- plugin/rss-reader/Resources/views/rss.html.twig
| Fixed tickets | #1322 
When clicking on the title of a thread, instead of collapsing the panel we were redirected to the first home tab
> [RssReaderBundle] Rss collapse fix

- plugin/collecticiel/Resources/views/Dropzone/editCommon.html.twig
| Fixed tickets | https://github.com/claroline/Distribution/issues/1356
Fix broken html markup having it seems for side effect to open unwanted popup when submiting form
> Fix html markup and unwanted alert popup

- main/core/Command/DatabaseIntegrity/MigrationsCheckerCommand.php
- main/core/Command/Traits/BaseCommandTrait.php
- main/core/Manager/MigrationManager.php
| Fixed tickets | #1028
This simple CLI tool allows us to add entries in doctrine table when they're missing easily without having to go into mysql/phpmyadmin and try to find what we need (because these tables are hard to read).
There is also a manager because we used to do that manually in updaters and we could get it wrong.
`php app/console claroline:migration:check clarolinecorebundle 20150428152724`
The previous line will add the entry in the databse if it doesn't exists.
> [CoreBundle] CLI doctrine migration handling.

- main/core/Manager/TransferManager.php
| Fixed tickets | #1433
There are no activity importer so we have to check the condition.
We might add it later (at least we check it exists now because there isn't an importer for each resource type).
> [CoreBundle] Check if importer exists (Fixes #1433)

- main/core/Resources/scripts/build-old-themes.js
It adds the script to compile old themes, found on themes/less folder.
It uses theme.less and variables.less files in combination with claroline.less file to generate the updated theme.
> [CoreBundle] Script to build old themes found inside themes/less folder

- composer.json
- main/core/Command/Import/CreateUserFromCsvCommand.php
- main/core/Entity/User.php
- main/core/Manager/UserManager.php
Better email validation for users (with 3rd party suggested library by symfony2).
Also allows the csv user imports to continue by CLI and show wich users weren't imported due t validations errors.
> [CoreBundle] User csv validation

- main/core/Resources/scripts/build-old-themes.js
Added 'use strict' inside build-old-themes.js script and removed it from npm command in package.json
> [CoreBundle] Added 'use strict' inside script for old-themes, removed from npm command

- plugin/flashcard/Migrations/pdo_mysql/Version20161103101521.php
- plugin/flashcard/Resources/modules/flashcard/listNote.partial.html
This PR comes to fix errors found by @CPASimUSante on the 8.x.
- Error 500 on page `create_note` and `list_notes`
- JS error on page `list_notes`
This PR is the same as #1515 but for the 8.x branch. This is a correction of the #1521.
> [FlashCardBundle] Fix err 500 caused by bad migration (8.x)

- .sensiolabs.yml
- Excludes `.travis.yml` from checks
- Removes deleted files from configuration file
- Reduces the constraints on PRs to only validate on `critical` errors. We have too many `major` in the current code base, so the check will always fail. We will increase the severity when the code will be cleaner.
> updates sensio configuration

- main/core/Resources/views/Tool/desktop/parameters/toolProperties.html.twig
- plugin/notification/Resources/views/Parameters/config.html.twig
Cleans up the DOM and bootstrap classes in desktop tools and notification configuration.
This also adds a missing translation in Notification and slightly enhance responsivity on mobile screen.
Note : in the screenshots, the buttons have been moved to the right. But they are more commonly at the left in the config section so I've placed them back to their original position (I've just not updated the screenshots).
**Tools** [before]
**Tools** [after]
**Notification** [before]
**Notification** [after]
> Small ui fixes in desktop tools and notification configuration

- plugin/notification/Resources/views/Notification/rss.xml.twig
| Fixed tickets | https://github.com/claroline/Distribution/issues/1640
Fix dangling <strong> tag in rss notification
> [Notification] Fix extra strong tag in rss

- plugin/web-resource/Listener/WebResourceListener.php
| Fixed tickets | https://github.com/claroline/Distribution/issues/1619
allows index.html, index.htm, default.html, default.htm, Index.html, Index.htm, Default.html, Default.htm as rootfile in a webresource.
I added those files in the whitelist array. I could also have lowerized the check : if (strtolower(....)), but since there was some mixed case in the list, i didn't because i wasn't sure what it could imply in the corresponding file
**BEFORE :**
```php
private $defaultIndexFiles = [
'web/SCO_0001/default.html',          <=
'web/SCO_0001/default.htm',           <=
'web/index.html',
'web/index.htm',
'index.html',
'index.htm',
];
```
> allows capitalized rootfile for webresource

- main/core/Library/Transfert/ConfigurationBuilders/Tools/HomeImporter.php
- main/core/Library/Transfert/ConfigurationBuilders/Tools/ResourceManagerImporter.php
- main/core/Library/Transfert/ConfigurationBuilders/ToolsImporter.php
- main/core/Manager/TransferManager.php
- main/core/Resources/translations/platform.de.yml
The current import mechanism didn't use the default value set in the configuration because we never returned the data after the processor fired the processConfiguration method.
It fixes my use case where I needed the default values for the home widgets. I didn't change the rest.
I also slightly simplified the import method in the TransferManager (removes some useless/duplicated code).
> [CoreBundle] Fixing workspace import 

- plugin/path/Transfer/PathImporter.php
'manualProgressionAllowed' was missing from PathImporter. As a result any attempt to import a path was resulting to an error "option not found in data.path".
> [PathBundle] Fixed path import issue due to manualProgressionAllowed option missing from PathImporter

- plugin/exo/Resources/modules/api/middleware.js
It seems `response.body` does not exist in FF. In fact the whole condition was uneeded as empty body is handled by `.json() / .text()`.
> [exo-v2] fixes start quiz in Firefox

- plugin/website/Resources/views/Website/Macros/edit_macros.html.twig
- plugin/website/Resources/views/Website/Macros/view_macros.html.twig
Styles managed by assetic for website are dumped in the same folder used by `asset:installs`.
This produces strange results on my dev install (dumped files also appears in the vendor source directory, website/Resources/public/css, and so in git changes). 
I think it's due to the symlinks (possibly a problem with how windows manages it).
I've just moved the dest folder to another one in the `web` dir.
ping @ptsavdar.
> [WebSite] changes assetic destination folder

- plugin/cursus/Repository/CourseSessionRepository.php
Fixes repository methods that retrieve open sessions. It was returning closed sessions.
> Fix session repository methods

- plugin/exo/Resources/modules/utils/utils.js
When any html element without text (img / video ...) is set as item data the validation is in error
> [exo-v2] items html data validation

- plugin/exo/Resources/less/items/choice.less
- plugin/exo/Resources/less/items/common.less
- plugin/exo/Resources/less/main.less
- plugin/exo/Resources/less/quiz/index.less
- plugin/exo/Resources/less/quiz/papers.less
- plugin/exo/Resources/less/quiz/player.less
- plugin/exo/Resources/less/quiz/step.less
- plugin/exo/Resources/modules/items/choice/paper.jsx
- plugin/exo/Resources/modules/items/components/metadata.jsx
- plugin/exo/Resources/modules/items/components/paper-tabs.jsx
- plugin/exo/Resources/modules/items/match/paper.jsx
- plugin/exo/Resources/modules/items/words/paper.jsx
- plugin/exo/Resources/modules/quiz/papers/components/paper.jsx
- plugin/exo/Resources/modules/quiz/player/components/item-player.jsx
- plugin/exo/Resources/modules/quiz/player/components/player.jsx
- plugin/exo/Resources/translations/ujm_exo.en.yml
- plugin/exo/Resources/translations/ujm_exo.fr.yml
- Removes extra HTML elements.
- Fixes H* elements order.
- Fixes small bug in choices border radius.
- Displays step title in papers if available.
- Uses same styles for item meta in player and paper.
- Fixes item meta (title, content, description) order in papers.
- Fixes display of HTML contents in papers.
- Adds a generic "No answer" message in words paper.
- Removes unused props from `PaperTabs` component.
> [exo-v2] UI fixes

- plugin/exo/Serializer/Question/Type/PairQuestionSerializer.php
The player must only display rows for expected answers in the player (not all combinations defined by the creator).
> [exo-v2] fixes exported rows in pair questions

- plugin/audio-recorder/Form/Type/AudioRecorderConfigurationType.php
- plugin/audio-recorder/Resources/translations/innova_audio_recorder.en.yml
- plugin/audio-recorder/Resources/translations/innova_audio_recorder.fr.yml
- plugin/video-recorder/Form/Type/VideoRecorderConfigurationType.php
- plugin/video-recorder/Resources/translations/innova_video_recorder.en.yml
- plugin/video-recorder/Resources/translations/innova_video_recorder.fr.yml
The configuration form for innova recorders throws a 500 error because the button name is required.
> [InnovaRecorder] Administration configuration doesn't work

- plugin/wiki/Repository/SectionRepository.php
- plugin/wiki/Resources/modules/wiki/wiki.controller.js
- plugin/wiki/Resources/public/css/style.css
- plugin/wiki/Resources/views/Wiki/view.html.twig
Anonymous user can access wiki again.
Section title and section number are separated by hyphen.
Display scrolls to top of newly created or modified section after save.
> [WikiBundle] Fix for anonymous wiki access and display

- main/core/Twig/WorkspaceAccessExtension.php
If a resource has no workspace (it's currently allowed because users don't always have one), this function crashes.
> [CoreBundle] Fixing WorkspaceAccessExtension

- plugin/badge/Controller/BadgeController.php
If the workspace is null, the query needs to be different or a 500 error is triggered.
> [BadgeBundle] Fixing error in badge query.

- plugin/exo/Entity/Exercise.php
- plugin/exo/Migrations/pdo_mysql/Version20170213070637.php
- plugin/exo/Resources/modules/quiz/actions.js
- plugin/exo/Resources/modules/quiz/editor/components/quiz-editor.jsx
- plugin/exo/Resources/modules/quiz/overview/overview.jsx
- plugin/exo/Resources/modules/quiz/selectors.js
- plugin/exo/Resources/translations/ujm_exo.en.json
- plugin/exo/Resources/translations/ujm_exo.fr.json
- plugin/exo/Serializer/ExerciseSerializer.php
This option only affects users who can not edit the quiz.
**Known issue**
For now, the overview is still displayed during the initialization (aka AJAX call) of the player.
> [ExoBundle] adds option to disable overview for users

- plugin/agenda/Resources/views/Widget/event_widget.html.twig
… #1986
| Fixed tickets | #1986
> [9.x] Fixes links in agenda event widget that redirect to first tab

- plugin/exo/Installation/AdditionalInstaller.php
- plugin/exo/Installation/Updater/Updater090000.php
- plugin/exo/Installation/Updater/Updater090002.php
| Fixed tickets | #1994 
- Adds a new updater to fix migration of quiz types.
- Fixes answer data migration.
**Note about answer migration :**
I've directly fixes the original updater file because the fix is only here to filter incomplete answer data. 
In the old version when a user didn't answered a question, sometimes incomplete data were stored in the DB.
So if someone has already updated to 9.x and do not hit a bug, he doesn't need this fix.
ping @ptsavdar : this should solve your problems.
> [ExoBundle] fixes quiz migration

- plugin/url/Validator/Constraints/ReachableUrlValidator.php
URLs are currently validated using curl requests but some websites reject them with a 406-like error code if they see the default curl user-agent header. This PR simply adds a real browser u-a header to prevent that behaviour.
> [UrlBundle] Spoof user-agent header when validating URLs

- main/core/Resources/views/Layout/javascripts.html.twig
This PR ensures that polyfills are always available in the base layout.
This fixes quizzes on Safari and IE11.
> [CoreBundle] fixes polyfills import

- main/core/Controller/ResourceController.php
> Fixes call to getDetails() function when workspace options is null

- main/core/Resources/views/Layout/javascripts.html.twig
Polyfills require to be loaded after webpack `commons` in prod environment. 
They are broken without it.
> [CoreBundle] fixes javascripts load order

- plugin/exo/Resources/modules/items/cloze/editor.jsx
| Fixed tickets | https://github.com/claroline/Distribution/issues/2120
resolve #2120
> [ExoBundle] allow decimal score in cloze keyword

- main/core/Library/Configuration/PlatformDefaults.php
When Claroline is installed only french and english are activate by defaut, ES translation is not completed
> Update i18n parameter in PlatformDefaults.php

- plugin/exo/Resources/modules/items/components/icon.jsx
- plugin/exo/Resources/public/images/item-icons.svg
Use the direct output of https://github.com/claroline/icons and prefix icon names with domain name. Also add all the missing icons for existing (boolean) and ongoing question types.
From now on:
- Every icon must be stored in its original inkscape format in that repository. Other tools or storage solutions like owncloud and http://travis.claroline.net/icons-test/ should not be used anymore.
- No manual transformation of svg files must be performed. The contents of *dist/\*/\*.svg* files can be copy/pasted directly in their corresponding distribution files.
- Icons can -- and actually *must* -- be styled using css rules on `fill`/`stroke` attributes.
> [ExoBundle] Update icon file and refs

- plugin/cursus/ClarolineCursusBundle.php
- plugin/message/Resources/views/Message/listReceived.html.twig
- Prevents received messages lis page to crash if there is a message with no sender associated
- Adds dependency declaration to MessageBundle in CursusBundle
> [9.x] Small fixes

- main/core/Library/Transfert/ConfigurationBuilders/Tools/ResourceManagerImporter.php
Wrong property was read for imported items index, seems like a copy/paste error
wrong index property was read during item import.
> fix imported items index

- main/core/Manager/AuthenticationManager.php
If ldap bundle was once enabled and user had already created some ldap servers, if bundle was the disabled, it generated an error in some user forms (typically on add new user).
> [CoreBundle] Fixed minor issue if ldap is disabled after having enabled at least once

- main/core/Command/Logs/LogsFetcherCommand.php
- main/core/Form/Log/AdminLogFilterType.php
- main/core/Form/Log/ResourceLogFilterType.php
- main/core/Form/Log/WorkspaceLogFilterType.php
- main/core/Manager/LogManager.php
- main/core/Repository/Log/LogRepository.php
- main/core/Resources/translations/log.en.json
- main/core/Resources/translations/log.fr.json
- main/core/Resources/views/Log/tool_view_list.html.twig
We should be able to filter logs by groups and export the result as an excel/csv file.
This is a draft for a CLI tool doing it but it would be better to do it at the GUI level.
edit: I guess I can remove the CLI tool now.
@ptsavdar Where is the resource log form used ? It's the only only one I didn't touch. Did I miss something else ?
> Log exporter by group

- plugin/blog/Controller/API/ApiController.php
This commit fixes a bug where a post or tag can not be found by the API if its slug starts with a number.
> [BlogBundle] Fix searching post or tag by slug

- plugin/path/Resources/modules/summary/Partial/edit.html
- plugin/path/Resources/modules/summary/Partial/show.html
- plugin/path/Resources/styles/components/summary.less
- plugin/path/Resources/styles/variables.less
- plugin/path/Resources/views/Path/edit.html.twig
- plugin/path/Resources/views/Path/open.html.twig
New sizing rules are :
XS screens :
- summary can not be pinned
- closed summary is a bar at the top of the step content
- summary is full width (12 bs cols)
SM screens :
- summary can not be pinned
- closed summary is a bar at the left of the step content
- summary is 50% width (6 bs cols)
MD & LG screens :
- summary can be pinned
- closed summary is a bar at the left of the step content
- summary is ~40% width (5 bs cols) by default
- summary is ~33% width (4 bs cols) in fullscreen mode
> [PathBundle] fixes text overflow and enhances responsive

- plugin/dropzone/Controller/DropController.php
| New feature?  | /no
| Fixed tickets | #1929 
An evaluation only tries to rename its hidden directory if this directory exists.
> [DropZoneBundle] Fix issue #1929

- plugin/blog/Resources/modules/post/post.controller.js
- plugin/blog/Resources/modules/post/postcreate.partial.html
- plugin/blog/Resources/translations/icap_blog.de.json
- plugin/blog/Resources/translations/icap_blog.en.json
- plugin/blog/Resources/translations/icap_blog.es.json
- plugin/blog/Resources/translations/icap_blog.fr.json
- plugin/blog/Resources/translations/icap_blog.it.json
- plugin/blog/Resources/translations/icap_blog.nl.json
| Fixed tickets | #2335 
Angular template now limits post title size to 255 chars (limit fixed in Symfony annotation on Post entity). 
Fixes #2335
> [BlogBundle] Limit post title length in Angular template

- plugin/dropzone/Resources/views/Dropzone/editCommon.html.twig
- plugin/dropzone/Resources/views/Dropzone/editCriteria.html.twig
Fixes admin pages overflow : content (and its padding) is now contained into page boundaries.
> [DropZoneBundle] Fix admin pages layout

- main/core/Command/Dev/ImportWorkspaceModelCommand.php
- main/core/Controller/WorkspaceController.php
- main/core/Library/Transfert/ConfigurationBuilders/Tools/Resources/FileImporter.php
- main/core/Manager/TransferManager.php
- main/core/Manager/WorkspaceManager.php
- main/core/Resources/views/Workspace/importForm.html.twig
- plugin/bibliography/Transfert/BibliographyImporter.php
- plugin/blog/Manager/BlogManager.php
- plugin/forum/Transfert/ForumImporter.php
- plugin/url/Manager/UrlManager.php
- adds a method to create workspace from uncompressed template
- adds options to ImportWorkspaceModelCommand command line (--skip to skip existing workspaces and not deleting them, --uncompressed to import provided directory_path as an uncompressed template)
- removes unecessary file copy in memory during file import, it was doing twice the job, and mounting big files in memory provoked memory limit exceptions.
- fixes missing 'sticked', 'creation_date', ''modification_date' properties in forum importer
- adds http context check in url importer, otherwise crashed if called from command line
- fixes blog import banner detection
- fixes bibliography importer
- fixes …
> Importers patch

- main/core/Controller/API/User/UserController.php
- main/core/Tests/API/User/UserControllerTest.php
| Fixed tickets 
@Get("/user/{user}") expects a login or email as parameter, but fails if they contain dots (e.g. firstname.lastname, and most emails), which defeats the purpose of the method. Problem comes from the use of the dot as separator for 'format' parameter in routing (FOSRestBundle ?).
Adding a new part to the route splits up the 'user' and 'format' parameters thus fixing the problem.
> API getUserAction() route fix

- main/core/DataFixtures/PostInstall/LoadPostInstallFixturesData.php
The trait is already loaded in the parent class `LoadRequiredFixturesData`.
This should fix travis on claroline/Claroline.
> [CoreBundle] removes duplicated trait use

- main/core/Library/Transfert/RichTextFormatter.php
typo on object tag, source attribute is data, not src
> typo on object tag

- plugin/external-user-group-synchronization/Manager/ExternalSynchronizationManager.php
Liberating doctrine allocated memory to avoid exhaustion.
> [ExternalSyncBundle] Fixed memory issue

- main/core/Library/Installation/Refresher.php
Class `Composer\Script\CommandEvent` is marked as deprecated and should be replaced by `Composer\Script\Event`.
> [CoreBundle] removes deprecated composer type hint

- main/dev/Resources/hooks/pre-commit-phpcs
php-cs-fixer was pointing to machine's global php-cs-fixer. As a result if machine's php-cs-fixer was updated to a version >= 2 the hook didn't work.
> [DevBundle] Fixed to point to local php-cs-fixer inside vendor/bin

- plugin/website/Entity/WebsitePage.php
| Fixed tickets 
Fixes default target for external links in website importer. 
Forces default target value to new tab instead of iframe, to prevent crossdomain issues.
> [WebsiteBundle]Changed import 'target' default value

- main/core/Controller/Administration/AnalyticsController.php
- main/core/Repository/ResourceTypeRepository.php
Personal workspaces and soft deleted resources should not be counted in platform or workspace analytics.
> Platform analytics update

- main/core/Resources/modules/administration/workspace/components/workspaces.jsx
- main/core/Resources/modules/administration/workspace/index.js
- main/core/Resources/modules/administration/workspace/reducer.js
- main/core/Resources/modules/layout/page/components/page-actions.jsx
- main/core/Resources/modules/layout/page/components/page.jsx
- main/core/Resources/modules/layout/page/containers/page.jsx
- main/core/Resources/modules/layout/page/index.js
- main/core/Resources/modules/utilities/app/bootstrap.js
- main/core/Resources/modules/utilities/app/router.js
- main/core/Resources/modules/utilities/redux.js
- package.json
Adds react-router-dom as dependency (https://www.npmjs.com/package/react-router-dom)
ping @ngodfraind @kitan1982 
Adds a new `Page` redux container (used in WS management) so this is now longer needed to manually bind modales in implementations. Simplifications can be seen here : https://github.com/claroline/Distribution/pull/2732/files#diff-1cdf53377728baa51a013530940ea96b.
**Sugar synthax to bootstrap a react app.**
Implementation is here : https://github.com/claroline/Distribution/blob/react-router/main/core/Resources/modules/utilities/app/bootstrap.js#L15.
It can be seen in action in the workspace management : https://github.com/claroline/Distribution/blob/react-router/main/core/Res …
> [CoreBundle] adds react-router-dom and core UI components

- main/core/Controller/ResourceController.php
Until now, only platform admins and creators could re-order the resources inside a Workspace (or a folder in a workspace). This fix allows anyone that has the right to administrate a container resource to drag-n-drop its children resources.
> [CoreBundle] Fix drag-n-drop of resources for ws admins

- plugin/wiki/Resources/public/css/style.css
When a wiki is embedded in a website, some of the section headers were hidden by a rule defined by the Bootstrap stylesheet. This CSS fix prevents headers from disappearing.
> Fix wiki display when embedded in a website

- main/core/API/Serializer/UserSerializer.php
- main/core/Controller/APINew/AbstractController.php
- main/core/Routing/ApiLoader.php
- user serializer also return email and admin code
- no more '/' at the end of the auto generated endpoints
- new getAction method and route allowing to perform a doctrine findByOne on a given entity. This is relevant when we want to find a single entity (ie, find the user whose email is xxx@email.com, the list one use a LIKE operator so missmatch can occur).
> [CoreBundle] Some API improvements

- main/core/API/Finder/ResourceNodeFinder.php
This PR provides support for multiple values in resource type filter for API search.
> Enable API search by multiple resource types

- main/core/API/Serializer/Resource/ResourceNodeSerializer.php
- main/core/Controller/ResourcePropertiesController.php
- main/core/Entity/Resource/ResourceNode.php
- main/core/Entity/Resource/ResourceThumbnail.php
- main/core/Form/ResourcePropertiesType.php
- main/core/Manager/ResourceManager.php
- main/core/Manager/ThumbnailManager.php
- main/core/Migrations/pdo_mysql/Version20171119140324.php
- main/core/Resources/translations/platform.de.json
- main/core/Resources/translations/platform.en.json
- main/core/Resources/translations/platform.es.json
- main/core/Resources/translations/platform.fr.json
- main/core/Resources/translations/platform.it.json
- main/core/Resources/translations/platform.nl.json
Resource node edit form enables the user to add a description and a thumbnail poster to a node. This data is intended to be displayed in the resource portal.
> [CoreBundle] New fields for resource node edit form

- main/core/API/Serializer/Resource/ResourceNodeSerializer.php
- plugin/url/Listener/ApiListener.php
If a url points to a Youtube video, its thumbnail url is automatically added as poster during node serialization.
> [UrlBundle] Get automatic poster image for a Youtube url

- plugin/exo/Resources/modules/quiz/overview/overview.jsx
- plugin/exo/Resources/styles/quiz/overview.less
- plugin/exo/Resources/translations/ujm_exo.en.json
- plugin/exo/Resources/translations/ujm_exo.fr.json
| New feature?  | yes 
| Fixed tickets | Fixes partially #3213 
Exercise overview updated with clear messages of what's happening if you can't start it.
> Error message clearer if exercice not available.

- main/core/Controller/ResourceController.php
Disabled "lastOpenDate" behavior for now in resource manager for all resources as it was a performance issue for big log tables, until a better logging system is in place.
> [CoreBundle] Disable last open date for resources in resource manager (for performance sake)

- .gitignore
- plugin/exo/Controller/Api/PaperController.php
- plugin/exo/Entity/Item/Item.php
- plugin/exo/Library/Item/Definition/BooleanDefinition.php
- plugin/exo/Library/Item/Definition/ChoiceDefinition.php
- plugin/exo/Library/Item/Definition/ClozeDefinition.php
- plugin/exo/Library/Item/Definition/GraphicDefinition.php
- plugin/exo/Library/Item/Definition/MatchDefinition.php
- plugin/exo/Library/Item/Definition/OpenDefinition.php
- plugin/exo/Library/Item/Definition/OrderingDefinition.php
- plugin/exo/Library/Item/Definition/PairDefinition.php
- plugin/exo/Library/Item/Definition/SelectionDefinition.php
- plugin/exo/Library/Item/Definition/SetDefinition.php
- plugin/exo/Library/Item/Definition/WordsDefinition.php
- plugin/exo/Manager/ExerciseManager.php
- plugin/tag/Manager/TagManager.php
Je n'ai probablement pas tout testé, mais ça solutionne beaucoup de problème lors de l'export des résulats des exercices en csv. En tout cas mon export en local à base d'exercice par tag que j'ai que j'ai modifié plusieurs fois avec certaines questions dont la réponse est vide est correct de cette manière.
J'ai pas testé tous les types de questions lors qu'on ne répond pas. Pour le reste je pense que c'est bon.
En bonus le libellé n'est plus le Uuid là ou c'était possible.
Voir #3233
> [ExoBundle] Csv result export

- plugin/exo/Library/Item/Definition/BooleanDefinition.php
| Fixed tickets | #3374 
Fixes Boolean question CSV export for papers when no answer is provided.
> [ExoBundle] Fix boolean question paper csv export

- plugin/lti/Controller/LtiWsController.php
Use rawurlencode instead of urlencode to not encode ~
> To not encode the character ~

- main/core/Controller/APINew/User/OrganizationController.php
| Fixed tickets | #3420 
ATTENTION : il s'agit d'une erreur au niveau de l'api. Les utilisateurs qui ont été ajoutés à une Organisation depuis la version 10.9.0 ont été ajouté comme gestionnaire de l'organisation ! Il faut vérifier les données manuellement et corriger en conséquence.
> [CoreBundle] fixes #3420

- main/core/Resources/config/suggested/framework_prod.yml
| Bug fix?      | Security breach
This security param is normally set to true by default in SF. 
It just does so starting from version 2.8
> [CoreBundle] Secure XSS attacks (v11)

- package.json
I fixed the issue by running `npm install video.js@5.20.5`
| Fixed tickets | #3947
> Video.js version

- main/core/API/Serializer/Resource/ResourceNodeSerializer.php
- plugin/drop-zone/Resources/modules/resources/dropzone/components/documents.jsx
The old serialized version was not usable by the front.
ResourcePages, DataCards and DataLists can now use it (it's not done here).
> [CoreBundle] fixes ResourceNode serializer minimal mode

- main/core/Controller/FileController.php
Assez urgent. Répare les liens cassés lors de la migration (vu que les routes ont changées). Les plateformes en prodution ayant déjà rajouté des fichiers via tinymce devront les remettre (à moins de doubler l'url de stream. On le fera s'il le faut mais c'est peu probable vu que le picker dans tiny est cassé).
> Fixing file upload route (for retrocompatibility)

- package.json
- plugin/video-player/Resources/views/scripts.html.twig
In Safari we never catch the end of the video download (I don't know why) so the player never appears.
> [VideoPlayerBundle] fixes video loading

- plugin/path/Entity/Step.php
Cleaning request : 
```
DELETE t1 
FROM innova_step_secondary_resource t1
INNER JOIN innova_step_secondary_resource t2 
WHERE t1.id < t2.id AND t1.step_id = t2.step_id AND t1.resource_id = t2.resource_id;
```
> [PathBundle] fixes duplicated secondary resources

- plugin/exo/Resources/modules/items/match/prop-types.js
- plugin/exo/Resources/modules/quiz/correction/components/answers.jsx
- plugin/exo/Resources/modules/quiz/correction/selectors.js
In progress:
```
Sauvegarde de réponse de question ouverte échoue sous certaines conditions
Lorsqu'un exercice est en mode de correction 'après le dernier essai de l'étape' ou 'depuis date', si on revient sur une copie (via l'option de reprise de copie), et qu'on essaie de modifier la réponse d'une question ouverte préalablement sauvegardée, la sauvegarde/changement de page échoue. Erreur 422 Unprocessable Entity:
[{'path':'|/score','message':'instance must be of type number'},{'path':'','message':'instance must match all the schemas listed in allOf'}]
Le problème n'est pas présent si la correction est …
```
> Fixing white page for open question correction.

- main/core/Controller/APINew/User/GroupController.php
- main/core/Resources/modules/workspace/actions/register-groups.js
- main/core/Resources/modules/workspace/user/role/components/role.jsx
| Fixed issues | #5713 
J'avoue ne pas avoir pris le temps de reproduire mais je suis quasi sur que ça vient d'une de ces urls et que l'autre pose problème mais que personne ne s'en est jamais plaint.
apiv2_group_list_registerable montre la liste des groupes avec lesquels on a une organisation commune.
apiv2_group_list_managed montre la liste des groupes dont on est gestionnaire de l'organisation.
=> apiv2_group_list_managed est utilisée dans les requête des l'outils d'administration des utilsateurs
=> apiv2_group_list_registerable est (ou devrait s'il elle ne l'est pas) être utilisée dans les autres cas (sinon la liste peut être vide).
> [CoreBundle] Use the registerable group list instead of managed.

- main/core/Manager/Workspace/Transfer/OrderedToolTransfer.php
| Fixed issues | #5794 
C'est plus une vérif anti plantage qu'un véritable fix. Normalement le role devrait exister mais je connais pas du tout le système de synchronisation.
> [CoreBundle] Check if role exists before creating right.

- main/app/Controller/AbstractCrudController.php
I noticed it when toying around with mercure.
It's because a new entity is created in the Serializer. There might be other instances of such a case.
> [CoreBundle] Text properly refreshed in the ui on update.

- main/core/API/Serializer/User/RoleSerializer.php
| Fixed issues | #5847 
Role should not be renamed as it's used like an identifier. The translation key can be modified and and be used to generate the name the first time but that's all.
> [CoreBundle] Don't rename the role on update.

- .travis.yml
Travis a changé l'env de build par défaut qui a introduit un breaking change : https://benlimmer.com/2019/01/14/travis-ci-xvfb/.
Je sais pas trop comment ça va se passer avec les PRs déjà ouverte. Elles ne buildent pas sur le même environnement (même quand on les relance). Il faudra peut être clôturer les PRs et les rouvrir...
> fixes travis build

- main/core/Command/DatabaseIntegrity/ResourceSlugBuilderCommand.php
Ici on fait que garder une copie de la table claro_resource_node et de restaurer de modifier les slugs avec un "?".
J'aurais bien voulu les modifier en plus mais c'est trop compliqué. Les urls en db sont changées et un urlencode ne transforme pas la chaine de caractère comme il faut.
C'est encore une autre forme d'encodage, mais je sais pas laquelle.
> Command for slugs restoration

- main/app/Resources/translations/actions.en.json
- main/app/Resources/translations/actions.fr.json
- main/core/API/Finder/Workspace/WorkspaceFinder.php
- main/core/API/Serializer/Workspace/WorkspaceSerializer.php
- main/core/Controller/APINew/Workspace/WorkspaceController.php
- main/core/Entity/Workspace/Workspace.php
- main/core/Manager/Workspace/WorkspaceManager.php
- main/core/Resources/modules/plugin.js
- main/core/Resources/modules/tools/workspaces/components/tool.jsx
- main/core/Resources/modules/workspace/actions/archive.js
- main/core/Resources/modules/workspace/actions/unarchive.js
- main/core/Resources/modules/workspace/components/card.jsx
- main/core/Resources/modules/workspace/components/list.jsx
- main/core/Resources/modules/workspace/components/metrics.jsx
- main/core/Resources/modules/workspace/modals/about/components/about.jsx
- main/core/Resources/translations/platform.en.json
- main/core/Resources/translations/platform.fr.json
- main/core/Resources/translations/workspace.en.json
- main/core/Resources/translations/workspace.fr.json
- les actions Archiver/Désarchiver un espace sont maintenant disponibles dans l'outil "Espaces d'activités". NB. Il n'est pas possible d'archiver les modèles.
- Il est possible d'afficher les espaces archivés dans "Espaces d'activités gérés" de l'outil "Espaces d'activités". Par défaut, ils sont masqués, il y a un nouveau filtre pour les afficher.
- L'info est également disponible grâce à une icône sur les cartes des espaces archivés et dans la modale "A propos" des espaces (accessible via l'action "Voir les informations").
> [CoreBundle] exposes archived workspaces management

- main/app/Resources/modules/data/types/file/components/input.jsx
Si on utilise pas la fonction d'autoupload, c'est un objet file en JS et les props sont pas exactement les même.
Aussi le isEmpty pose problème pour une raison inconnue =/. Après ça me semble plus simple sans, je vois pas dans quel cas ça peut être utile.
Fix https://github.com/claroline/Distribution/issues/6263
> [AppBundle] File upload fix if not auto upload.

- main/core/Entity/Log/Log.php
- main/core/Event/Log/LogGenericEvent.php
- main/core/Listener/Log/LogListener.php
- main/core/Resources/views/log/view_details_owner.html.twig
J'ai pour le moment des erreurs bizarres avec les tables dynamique, donc je corrige/simplifie ce qui peut l'être à coté pour avancer quand même (new entity found in... c'est l'erreur de l'autre pr)
Donc y a surement un pb avec les metadatas des entités.
Les relation Many to Many entre la table de log et celle de role ne sont jamais utilisées.
Les getters ne sont pas utilisés et l'info est de toute façon stockée dans les détails.
A priori ce changement n'a aucun impact sur la plateforme, c'est juste plus simple.
Même chose avec le owner. La différence entre le owner et le doer est pas claire. C'est …
> [Logging] Simplify the Log entity.

- plugin/agenda/Finder/EventFinder.php
| Fixed issues | #6448
@elorfin 
L'agenda ne permet pas d'afficher les events dont endDate = null ni les events dont startDate > endDate (logique).
Par contre ils sont récupérés dans la requête et affichés dans le widget d'ou les events fantômes de l'issue.
> [AgendaBundle] Only fetches event where end > begin.

- main/app/Command/BaseCommandTrait.php
- main/core/Command/Traits/AskRolesTrait.php
| Fixed issues | -
The traits are wrongly referencing themselves, which breaks on PHP 7.4:
> Fix invalid self-references in traits
